questdb/questdb

roadmap.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/nfsdb/nfsdb/33)
=> Use checkboxes instead of crossing out for readability

roadmap.md
R, Python, Ruby can be done through the C client. Native JVM and .Net.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/nfsdb/nfsdb/34)
=> Added a more clients

README.md
Do you mind putting a link to Homebrew in the README, for user friendliness?
=> README: add link to Homebrew

README.md, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cutlass/http/HttpMultipartContentParser.java, core/src/main/java/io/questdb/cutlass/text/TextMetadataDetector.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/model/IntrinsicModel.java, core/src/main/java/io/questdb/log/LogFactory.java, core/src/main/java/io/questdb/std/ConcurrentHashMap.java, core/src/main/resources/site/conf/questdb.conf, core/src/test/java/io/questdb/cairo/IntervalBwdDataFrameCursorTest.java, core/src/test/java/io/questdb/cairo/IntervalFwdDataFrameCursorTest.java, core/src/test/java/io/questdb/cairo/RecordChainTest.java, core/src/test/java/io/questdb/cairo/map/CompactMapTest.java, core/src/test/java/io/questdb/cutlass/line/LineProtoLexerTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, ui/app/styles/_base.scss
This MR just fixes random typos.
=> contrib: fix minor typos

core/src/main/java/io/questdb/ServerMain.java
to implement dirty draft of server life cycle events
=> Extract start and shutdown server action into separate protected methods

core/src/main/java/io/questdb/griffin/engine/functions/math/RoundDoubleFunctionFactory.java, core/src/main/java/io/questdb/std/Numbers.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundDoubleFunctionFactoryTest.java
Adding support for negative scale for round().
=> feat: Adding negative scale support for round()

core/src/main/java/io/questdb/griffin/engine/functions/math/RoundDoubleFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/RoundHalfEvenDoubleFunctionFactory.java, core/src/main/java/io/questdb/std/Numbers.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundDoubleFunctionFactoryConstTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundDoubleFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundDownDoubleFunctionFactoryConstTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundDownDoubleFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundHalfEvenDoubleFunctionFactoryConstTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundHalfEvenDoubleFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundUpDoubleFunctionFactoryConstTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/RoundUpDoubleFunctionFactoryTest.java, core/src/test/java/io/questdb/std/NumbersTest.java
feat: round_half_even() implementation
=> Round half even

core/src/main/bin/questdb.sh, core/src/main/java/io/questdb/griffin/engine/functions/date/AddDaysToTimestampFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/AddHoursToTimestampFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/AddMonthsToTimestampFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/AddYearsToTimestampFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/DayOfMonthFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/DayOfWeekFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/DayOfWeekSundayFirstFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/DaysBetweenFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/DaysPerMonthFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/IsLeapYearFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/MicrosOfSecondFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/MillisOfSecondFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/MinuteOfHourFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/MonthOfYearFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/MonthsBetweenFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/SecondOfMinuteFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/YearFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/YearsBetweenFunctionFactory.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
Making Timestamp functions available in SQL
=> Timestamp sql functions

benchmarks/src/main/java/org/questdb/SqlKeywordsBenchmark.java, core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/main/java/io/questdb/griffin/model/IntrinsicModel.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java
Benchmark                                                   Mode  Cnt  Score   Error  Units
SqlKeywordsBenchmark.testEqualsLowerCaseAsciiInsertKeyword  avgt    5  5.043 ± 0.201  ns/op
SqlKeywordsBenchmark.testEqualsLowerCaseAsciiSelectKeyword  avgt    5  5.696 ± 0.017  ns/op
SqlKeywordsBenchmark.testIsInsertKeyword                    avgt    5  4.169 ± 0.003  ns/op
SqlKeywordsBenchmark.testIsSelectKeyword                    avgt    5  4.230 ± 0.029  ns/op
=> binary hack for parsing case insensitive keyword

benchmarks/src/main/java/org/questdb/AbsBenchmark.java, core/src/main/java/io/questdb/griffin/engine/groupby/DistinctSymbolRecordCursorFactory.java
=> fix(griffin): distinct symbol record should additionally be implementing "string" interface

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java, core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/main/java/io/questdb/std/NanosecondClock.java, core/src/main/java/io/questdb/std/NanosecondClockImpl.java
this is only server side impl so far
=> feat(http): measure server exec time on server to report on client.

ui/src/js/console/globals.js, ui/src/js/console/index.js, ui/src/js/console/query.js, ui/src/partials/console.hbs, ui/src/styles/_editor.scss
New timings:
Better error messages:
Default state:
=> feat(console): add timings + improve error messages

core/src/main/java/io/questdb/griffin/SqlKeywords.java
Missed this one in the previous pr.
=> chore: remove unused i++ new value

CONTRIBUTING.md, README.md
Changes on the documentation:
- Update pre-requesites
- Update `java -version`
- Mention `-Dprofile.install-local-nodejs`
- Update pre-requesites
=> docs: update references from java 8 to 11

.gitignore, ui/package-lock.json, ui/package.json, ui/utils/deploy.js
The `deploy` script will now output the `ui` artifacts into a `public.zip` archive.
=> chore(ui): deploy artifacts as a zip in the site folder

.all-contributorsrc, README.md
The changes are:
- Improve all-contributors config
- Fix typos
- Remove last mention of Java 8
- Better instructions for "building & running"
=> docs: improvements for README.md

core/pom.xml
For now build failed with more details regarding possible solution.
=> Fix #315. Validate jdk11 version on build

core/src/main/java/io/questdb/std/Numbers.java
Removing branches for ~10% performance improvement.
=> Removing branches from round()

ui/src/js/console/docsearch.js, ui/src/js/console/grid.js
Force Algolia popup to open links in a new tab.
=> fix(console): open documentation links in a new tab - fixes #299

ui/src/js/console/console-controller.js, ui/src/js/console/index.js, ui/src/partials/nav.hbs
Fix regression introduced in commit c83c83037.
=> fix(console): revert change to correct regression with the Splitter

core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/main/java/io/questdb/griffin/model/IntrinsicModel.java, core/src/test/java/io/questdb/griffin/OrderByAdviceTest.java, core/src/test/java/io/questdb/griffin/TimestampQueryTest.java, core/src/test/java/io/questdb/griffin/WhereClauseParserTest.java
…ualsTo and MoreThanOrEqualsTo fix #323
=> fix(griffin) -  partial/short date in where clause  >=, > ,<, <=  #323 #265

ui/src/components/Button/index.tsx, ui/src/components/Link/index.tsx, ui/src/components/Text/index.tsx, ui/src/components/ToggleButton/index.tsx, ui/src/components/index.ts, ui/src/index.hbs, ui/src/js/console/import-controller.js, ui/src/js/console/import-detail.js, ui/src/scenes/Footer/index.tsx, ui/src/scenes/Layout/index.tsx, ui/src/styles/_base.scss, ui/webpack.config.js
The Footer is now part of the React world too. The remaining components are:
- Ace
- Import
- Grid
- Graph
=> refactor(console): migrate Footer to React

core/src/main/java/io/questdb/cairo/AbstractIntervalDataFrameCursor.java, core/src/main/java/io/questdb/cairo/IntervalBwdDataFrameCursor.java, core/src/main/java/io/questdb/cairo/IntervalFwdDataFrameCursor.java, core/src/test/java/io/questdb/cairo/IntervalFwdDataFrameCursorTest.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
In case of multiple equal timestamps, find the first when binary searching
=> fix(AbstractIntervalDataFrameCursor): binary search scan

ui/src/scenes/Schema/Table/index.tsx, ui/src/scenes/Schema/index.tsx, ui/src/utils/questdb.ts
=> fix(Console): update showTables() and showColumns() to new API

ui/package-lock.json, ui/package.json, ui/src/components/Button/index.tsx, ui/src/components/ToggleButton/index.tsx, ui/webpack.config.js
This is saving an extra 15KB on the bundle.
=> chore(console): remove unnecessary dependency from the bundle

ui/assets/console-configuration.json, ui/package-lock.json, ui/package.json, ui/src/scenes/Editor/Menu/index.tsx, ui/src/scenes/Editor/QueryPicker/index.tsx
=> chore(console): update popperjs to latest in order to prevent rendering loop

ui/assets/console-configuration.json
=> chore(config): reset Console config to default values

ui/src/components/Toast/index.tsx, ui/src/scenes/Editor/Menu/index.tsx, ui/src/scenes/Editor/QueryResult/index.tsx, ui/src/scenes/Notifications/Notification/index.tsx, ui/src/scenes/Result/index.tsx, ui/src/styles/_base.scss, ui/src/styles/_grid.scss
- Rename "Saved Queries" to "Example Queries"
- Show Query Result timings by default
- Format number according to user locales
- Animation in Toast notification stands out more now
- Fix horizontal scrollbar issue in grid
=> feat(console): minor improvements for the demo

README.md, ui/src/scenes/Editor/Ace/questdbMode.ts
=> feat(console): add "group" to the list of keywords in QuestDBMode (code editor)

README.md, ui/src/scenes/Schema/Row/index.tsx, ui/src/scenes/Schema/Table/index.tsx, ui/src/scenes/Schema/index.tsx, ui/src/utils/questdb.ts
=> feat(console): show dedicated icon for indexed columns in the schema view

ui/src/styles/_typography.scss, ui/src/styles/main.scss, ui/webpack.config.js
=> chore(console): remove unused assets from the bundle (~140KB saved)

core/src/main/java/io/questdb/cairo/SymbolMapWriter.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/cairo/RecordCursorPrinter.java, core/src/test/java/io/questdb/griffin/AbstractGriffinTest.java, core/src/test/java/io/questdb/griffin/AlterTableAlterSymbolColumnCacheFlagTest.java
=> feature(griffin) - support alter symbol column cache flag

ui/src/components/PopperHover/index.tsx, ui/src/components/PopperToggle/index.tsx, ui/src/index.tsx, ui/src/scenes/Editor/Loader/index.tsx, ui/src/scenes/Editor/QueryPicker/index.tsx, ui/src/scenes/SideMenu/index.tsx
The QueryPicker width is now 600px and it will automatically fit the screen when
its width is smaller.
----
#
=> feat(console): improve responsiveness for QueryPicker component

.travis.yml
Followup PR of #274
Relates to https://github.com/Homebrew/homebrew-core/pull/56603
=> Update travis to build with jdk11

ui/src/components/Text/index.tsx, ui/src/scenes/Editor/QueryResult/index.tsx, ui/src/scenes/Notifications/Notification/index.tsx
=> feat(console): add "network" section to QueryResult + move "count" and "compiler" to right column

README.md
=> docs(readme): update to latest version number + swap "npm" for "node"

ui/assets/console-configuration.json, ui/src/components/Emoji/index.tsx, ui/src/components/Link/index.tsx, ui/src/components/index.ts, ui/src/scenes/Footer/index.tsx, ui/src/scenes/GithubBanner/index.tsx, ui/src/store/Console/reducers.ts, ui/src/store/Console/types.ts, ui/src/styles/_base.scss, ui/src/theme/index.ts, ui/src/types/styled.d.ts
=> feat(console): add github banner with a toggle flag in the config

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/griffin/KeyedAggregationTest.java
Also inverted isValidColumnName() method. It was always used with ! operator
=> fix(griffin): fixed internal error while aggregating on hour with where clause.

ui/src/scenes/Schema/Table/index.tsx
=> fix(console): remove columns reset when collapsing table - fixes #448

core/src/main/java/io/questdb/TelemetryJob.java, core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java, core/src/main/java/io/questdb/tasks/TelemetryTask.java
I also renamed the column "ts" to "created" so it is less confusing
=> fix(telemetry): correct column type for created

README.md
=> docs: simplify documentation for Docker + add ref to hub.docker.com

benchmarks/pom.xml, core/src/main/java/io/questdb/griffin/engine/functions/regex/NotMatchCharFunctionFactory.java, core/src/main/java/module-info.java, core/src/test/java/io/questdb/griffin/engine/functions/regex/NotMatchCharFunctionFactoryTest.java, core/src/test/resources/META-INF/services/io.questdb.griffin.FunctionFactory
Tested via web UI and unit test case,works fine.
=> Text Function !~ doesnt work when used with single character #505

README.md
=> docs(README): align wording with v2 documentation/website

README.md
=> docs(README): fix dead links

ui/src/telemetry/index.ts
=> fix(telemetry): remove 1 week limit when lastUpdated is null

core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cutlass/http/processors/StaticContentProcessor.java
server will create version.txt in public directory, which will contain timestamp of public.zip inside questdb.jar. Next time server starts it will compare versions again and will overwrite "public" contents when jar has newer version.
=> chore(server): introduced version of web console and removed -f command line arg

README.md
Update command so it matches the new .jar filename as of 5.0.3
=> Update start command

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
=> fix(griffin): fixed 'with' clause behaviour in set operations (union, except, intersect), in recursive 'with' and in sub-queries

core/src/main/java/io/questdb/cairo/TableReaderSelectedColumnRecord.java, core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java, core/src/main/java/io/questdb/cutlass/text/TextLoader.java, core/src/main/java/io/questdb/cutlass/text/types/BadTimestampAdapter.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/table/DeferredSymbolIndexFilteredRowCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/SymbolIndexFilteredRowCursor.java, core/src/main/java/io/questdb/griffin/engine/table/SymbolIndexFilteredRowCursorFactory.java, core/src/main/java/io/questdb/std/CharSequenceObjHashMap.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
I also fixed a problem, raised by users, where uploading "bad" timestamp in CSV would result in exception and perceived curl hang (no response from server)
=> fix(griffin): fixed incorrect column referencing from index-based filter implementation

README.md
=> docs(README): remove downloads badge

core/src/main/java/io/questdb/TelemetryJob.java
=> fix(telemetry): try/catch CairoException when attempting to insert a new row

README.md
=> chore(README): bump version number in build instructions

.all-contributorsrc
=> chore: correct typo in all-contributors config file

core/src/main/java/io/questdb/TelemetryJob.java
=> fix(telemetry): do no crash when TelemetryJob can't lock internal tables

README.md
=> docs(readme): update references to new Slack URL

core/src/main/java/io/questdb/TelemetryJob.java
=> fix(telemetry): add check to prevent null pointer exception when freeing resources

README.md
Update version number in readme since last release.
=> docs(readme): update version number

README.md
=> fix(readme): correct broken link to website

README.md, ci/snapshot-pipeline.yml, ci/test-pipeline.yml
The CI badge is failed state because the badge is tracking master, not the branch. Last build failed because of mis-configured variables in the pipeline, next build should succeed.
=> docs(readme): add Azure Pipelines and Docker Hub badges

ci/snapshot-pipeline.yml, ci/test-pipeline.yml
=> chore(ci): correct triggers for snapshot & test pipelines

core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/http/RetryIODispatcherTest.java, core/src/test/java/io/questdb/cutlass/http/SendAndReceiveRequestBuilder.java
=> Add test for double quote parser bug 

core/src/main/java/io/questdb/log/Log.java, core/src/main/java/io/questdb/log/LogFactory.java, core/src/main/java/io/questdb/log/LogLevel.java, core/src/main/java/io/questdb/log/Logger.java, core/src/main/java/io/questdb/network/AbstractIODispatcher.java, core/src/main/resources/qlog.conf, core/src/test/java/io/questdb/log/LogFactoryTest.java
The motivation for adding new level is to enable some log output from components where even ERROR logging is disabled.
=> feat(log): added new ADVISORY log level, one above ERROR

ui/package-lock.json, ui/package.json
=> chore(ui): bump sql-grammar to 1.0.7

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
__Changes:__
* Added `bug` and `New feature` labels to issue templates
__Additions:__
* External link to Stack Overflow community
=> chore: add lablels, SO link to issue templates

core/pom.xml
=> chore(build): make jlink pickup jar vs dir, to enable build() function to work

core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessorState.java
Changes to add filename parameter in /exp
=> added filename parameter in /exp

README.md
Should not be merged before https://github.com/questdb/questdb.io/pull/391
=> docs: update URL for web console docs

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/TxReader.java, core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/test/java/io/questdb/cairo/TableWriterTest.java, core/src/test/java/io/questdb/griffin/AlterTableAttachPartitionTest.java
instead of renaming to .detached
=> fix: delete not attached partition folders on writer open

README.md, core/README.md
This PR trims down the repo README and moves build instructions out into core doc
=> chore: update README, move build details to core/REAMDE

ui/src/components/Button/index.tsx, ui/src/scenes/Editor/Ace/index.tsx, ui/src/scenes/Editor/Menu/index.tsx, ui/src/store/Query/actions.ts, ui/src/store/Query/reducers.ts, ui/src/store/Query/types.ts
add clean all shortcut - Ctrl+K
=> feat(console): change maximum visible notifications to not overlap data grid

core/src/main/java/io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunction.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunctionFactoryTest.java
=> fix(griffin): fixed interpolated avg()

README.md
__Description:__
Highlight our wonderful contributors on our repo's README badges
=> chore: replace Docker pulls with contributors

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/std/AssociativeCache.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
=> fix(pgwire): fixed infinite loop when client is slow to read cursor

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
testMultistatement is ignored for now
=> Postgres JDBC driver cursor mode. Fixes #806

.all-contributorsrc, README-CN.md, README.md, i18n/README.zh-cn.md, i18n/languages.md
This PR adds i18n for the repo docs with a Simplified Chinese 🇨🇳 translation of our project README.
All-contributors bot config is adjusted so new additions **should be** unified across both documents, but this needs to verified.
__Other changes:__
* Removed badges from both READMEs to reduce clutter at the top of the documents.
* link in TSBS section points to benchmark page instead of blog post
=> docs: Add CN README

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/TimestampQueryTest.java
=> fix(sql): removed unnecessary timestamp requirement for slave join models

README.md
This PR updates the project README with details for milestones and discussions
=> chore: add discussions, milestones to README

core/src/main/java/io/questdb/log/LogFileWriter.java, core/src/main/java/io/questdb/log/LogRollingFileWriter.java
=> chore(log): fix log crash on empty sink

core/src/main/resources/io/questdb/site/conf/server.conf
This is a minor typo fix for #1164
=> chore: typo fix in server conf file, 9013 -> 9003 for health endpoint

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Fix `select count() from x sample by 1h` query
=> fix(sql): fix select count() with sample by

core/src/main/java/io/questdb/ServerMain.java
=> style(core): log server info on startup (#838)

ci/test-pipeline.yml
=> typo in "on_demand_instance"

ci/test-pipeline.yml
pipeline will cleanup arm agent, even if the tests fails.
=> feat(ci): added condition to build agent cleanup stage

ci/test-pipeline.yml
This will reduce build time and download failures from maven central
=> feat(ci): added cache to maven builds

ci/test-pipeline.yml
Added condition to always start arm build
=> feat(ci): added condition to always start

core/src/main/java/io/questdb/cairo/O3CopyJob.java, core/src/main/java/io/questdb/cairo/O3PurgeDiscoveryJob.java, core/src/main/java/io/questdb/cairo/O3PurgeJob.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java
the error is specific to Windows platform and can lead to data corruption on O3 ingestion
=> fix(o3): fixed race condition that can occur between O3 copy jobs and purge job

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/main/java/io/questdb/griffin/PostOrderTreeTraversalAlgo.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/std/GenericLexer.java, core/src/test/java/io/questdb/griffin/ExpressionParserTest.java, core/src/test/java/io/questdb/griffin/FunctionParserCastFunctionsNullTest.java, core/src/test/java/io/questdb/griffin/RpnBuilder.java, core/src/test/java/io/questdb/griffin/engine/functions/cast/CastGeoHashFunctionFactoryTest.java, core/src/test/java/io/questdb/std/GenericLexerTest.java
=> feat(sql): improve expression parsing of geohash type constant

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastCharToStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndSymbolListFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillNullRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java, core/src/test/java/io/questdb/griffin/SqlCompilerTest.java, core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
- fix NPE in rnd_symbol()
- fix char insert to geohash column
=> feat(sql): geohashes first(), last() with fill

.all-contributorsrc, i18n/README.ar-dz.md, i18n/README.zh-cn.md, i18n/languages.md
I added the Arabic translation 🇩🇿 (i18n) for the README file
=> docs: i18n - Added the Arabic version of README

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java, core/src/test/java/io/questdb/griffin/AsOfJoinTest.java, core/src/test/java/io/questdb/griffin/JoinTest.java, core/src/test/java/io/questdb/griffin/SecurityTest.java
Fixes: https://github.com/questdb/questdb/issues/1275
=> fix(sql): fix lt join for equal timestampts

ui/src/scenes/Footer/index.tsx
Fix for footer copyright text
---
closes #1226
=> chore(ui): minor edit to UI footer

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Fixes: https://github.com/questdb/questdb/issues/1299
=> fix(sql): ignored latest-by column filter if it is indexed

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/vm/api/MemoryMAR.java, core/src/test/java/io/questdb/griffin/O3CommitLagTest.java
This to ensure that Commit With Lag keeps only most recent records in Lag
=> fix(cairo): move o3 uncommitted step to always move all uncommitted rows

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
=> fix(sql): fixed column index dereference in "latest by" SQLs

benchmarks/src/main/java/org/questdb/StrPosBenchmark.java, core/src/main/java/io/questdb/cairo/TableUtils.java
Removed Java11 API call from benchmarks
=> fix(test): we should use Java8 API where possible

benchmarks/src/main/java/org/questdb/LineTCPSenderMainVarLenStrings.java, ci/templates/steps.yml, pom.xml
=> chore(ci): fix jacoco in ci on root pom

ui/src/js/console/quick-vis.js, ui/src/styles/_quick-vis.scss
=> chore: enable tooltips for charts

README.md
Add a OS theme-aware (light/dark) SVG logo to QuestDB's README
=> chore(ui): add theme-aware questdb logo

core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/resources/io/questdb/cutlass/line/tcp/LineTcpO3Test.server.conf, pkg/ami/marketplace/assets/server.conf
Fixes setting names and values in the config files.
A follow-up for the clean up done in https://github.com/questdb/questdb.io/pull/612
=> chore(ilp): update prop names and values in config files

ui/src/scenes/Schema/Table/ContextualMenu/services.ts
There's a typo in SQL syntax for creating table schema.
=> chore(ui): fix create table schema

core/src/main/java/io/questdb/cairo/sql/InsertStatement.java, core/src/main/java/io/questdb/griffin/InsertRowImpl.java, core/src/main/java/io/questdb/griffin/InsertStatementImpl.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/model/InsertModel.java, core/src/test/java/io/questdb/griffin/AlterTableAlterSymbolColumnCacheFlagTest.java, core/src/test/java/io/questdb/griffin/InsertTest.java, core/src/test/java/io/questdb/griffin/SimulatedDeleteTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
Support for multiple row inserts.
=> feat(sql) SQL for bulk insert

core/src/main/java/io/questdb/cutlass/http/HttpResponseSink.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
=> fix(http): fixed serialization of `float` `infinity` to json

CONTRIBUTING.md
I lost good few hours troubleshooting random local test crashes before I figured it out.  
[>> AV link](https://help.eset.com/eis/13/en-US/idh_config_epfw_scan_main_page.html)
@bsmth Feel free to rewrite .
=> docs: add warning about potential antivirus effect on tests

pkg/ami/marketplace/Makefile
=> feat(aws,marketplace,ci): fixed questdb version calculation

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/pool/WriterPool.java, core/src/test/java/io/questdb/cairo/pool/WriterPoolTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
testRunAlterWhenTableLockedWithInserts
=> chore(test): increased timeouts to avoid test flapping

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java, core/src/main/java/io/questdb/std/BoolList.java, core/src/test/java/io/questdb/std/BoolListTest.java
fixing race condition while adding a new column
=> fix(ilp): fixing race condition while adding a new column

core/src/main/java/io/questdb/cairo/pool/ReaderPool.java
=> fix(core): fixed race condition releasing (and potentially leaking) table reader

core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/griffin/InsertTest.java, core/src/test/java/io/questdb/griffin/NoopGroupByTest.java, core/src/test/java/io/questdb/griffin/O3CommitLagTest.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/SqlCompilerTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java, core/src/test/java/io/questdb/griffin/TrickTableReloadTest.java, core/src/test/java/io/questdb/griffin/UnionTest.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactoryTest.java
Fixed [#1726](https://github.com/questdb/questdb/issues/1726)
=> fix(sql): partitioning without designated timestamp should not be possible.

core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java, core/src/test/java/io/questdb/cutlass/text/TextLoaderTest.java
=> fix(cutlass): adjusts column order during csv import

core/src/test/java/io/questdb/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/ImportIODispatcherTest.java
Fixes #1554 and #1812 
Work in progress - I'll also fix testImportDropReimportDifferentSchemaTextQuery in this branch .
=> chore(test): fix flaky io dispatcher test

core/src/test/java/io/questdb/cutlass/http/RetryIODispatcherTest.java
Refs: #1559
Speeds up `testInsertsIsPerformedWhenWriterLockedAndDisconnectedLoop` and adds more assertions
=> chore(test): add more assertions to retry insertion test

ci/templates/hosted-cover-jobs.yml, ci/templates/hosted-jobs.yml, ci/templates/steps.yml, ci/test-pipeline.yml, core/src/main/java/io/questdb/griffin/BatchCallback.java, core/src/test/java/io/questdb/TestListener.java
Code coverage include pattern fixes cherrt-picked from https://github.com/questdb/questdb/pull/1820
=> chore(sql): fix code coverage issue

core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpCommitTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/std/DirectLongListTest.java
=> chore(test): add random seed logging to ILP fuzzer

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/test/java/io/questdb/PropServerConfigurationTest.java
=> chore(core): reduced default ILP connection pool capacity

ui/src/scenes/Footer/BuildVersion/index.tsx, ui/src/scenes/Schema/Table/ContextualMenu/index.tsx, ui/src/utils/copyToClipboard.ts, ui/src/utils/index.ts
Fixes https://github.com/questdb/questdb/issues/1958
Refactored copy to clipboard logic to make it cross browser. Tested on latest Chrome, Safari and Firefox.
=> fix(ui): fix copy to clipboard for safari

ui/src/scenes/Editor/Menu/index.tsx
This PR adds a new button above the query editor.
The button links to `https://slack.questdb.io/`
=> feat(ui): add link to Slack community in web console

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/griffin/AlterTableAttachPartitionTest.java
Add an assert that o3TimestampMem is of expected size in O3 commit.
=> chore(test): assert ts column size

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByDeferredListValuesFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueListRecordCursor.java, core/src/main/java/io/questdb/std/IntHashSet.java, core/src/test/java/io/questdb/griffin/LatestByTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
=> feat(sql): optimise latest by symbol column with no index

core/pom.xml, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/griffin/AbstractO3Test.java, utils/pom.xml
Updating junit to 4.13.2 fixed the coverage issue .
=> fix(tests): re-enable test timeouts with working code coverage

core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java
`PageFrameSequence#await()` method wasn't awaiting for the reduce counter to be incremented to the number of dispatched tasks. It could be the case (a very infrequent one) that one of the workers reduced a page frame, then marked the task as done, but haven't incremented reduce counter yet.
The race manifested itself as the following AssertionError:
```
java.lang.AssertionError
at io.questdb@6.3.1/io.questdb.cairo.sql.async.PageFrameSequence.await(PageFrameSequence.java:126)
...
```
This commit adds the missing await loop.
=> fix(sql): fix uncommon potential race in parallel filter execution

core/src/main/java/io/questdb/cairo/RebuildColumnBase.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/test/java/io/questdb/cairo/IndexBuilderTest.java, core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
Add SQL frontend to exclusive index rebuild
```
REINDEX TABLE table_alpha COLUMN column_name LOCK EXCLUSIVE
REINDEX TABLE table_alpha COLUMN column_name PARTITION  '2021-12-17' LOCK EXCLUSIVE
REINDEX TABLE table_alpha LOCK EXCLUSIVE
```
https://github.com/questdb/rfc/discussions/9
=> feat(sql): sql command to reindex symbol column

README.md, i18n/README.ar-dz.md, i18n/README.zh-cn.md
Make it more clear of how to start on macOS.
=> Readme: Added missed commands.

core/src/main/java/io/questdb/cutlass/http/WaitProcessor.java
=> chore: fix flapping test leaking fd in http

README.md, i18n/README.ar-dz.md, i18n/README.zh-hk.md, i18n/languages.md
Added new zh-hk translation
Fixed incorrect languages order in zh-cn and line breaking in zh-cn and ar-dz.
=> chore(readme): added new translation

core/src/test/java/io/questdb/network/NetTest.java
=> chore: fix flapping test testSendAndRecvBuffer

core/src/test/java/io/questdb/griffin/DropIndexTest.java
Fixes https://dev.azure.com/questdb/questdb/_build/results?buildId=8636&view=ms.vss-test-web.build-test-results-tab&runId=54804&resultId=100403&paneView=debug
=> chore(test): fix flaky test DropIndexTest.testDropIndexSimultaneously

core/src/main/java/io/questdb/griffin/engine/functions/str/ConcatFunctionFactory.java, core/src/test/java/io/questdb/griffin/engine/functions/str/ConcatFunctionFactoryTest.java
=> fix(sql): nulls in concat function args are ignored

core/src/main/java/io/questdb/ServerMain.java
Fixes #2348
Follow up for https://github.com/questdb/questdb/pull/2345, which missed a spot
=> chore(core): flush error log on network error

core/src/test/java/io/questdb/test/tools/TestUtils.java
=> test(sql): fix flaky copy test

core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountGroupByFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountLongGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/InterpolationGroupByFunction.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/FunctionParserTest.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactoryTest.java
=> feat(sql): support int and long columns in count_distinct()

core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/TxReader.java, core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
Fixes error on update or insert after truncate on non-partitioned table . 
Fixes #2425
=> fix(sql): fix update or insert after truncate

core/pom.xml
* update CSV import UI with info box about COPY command [#23](https://github.com/questdb/ui/pull/23)
link to [changelog](https://github.com/questdb/ui/blob/main/packages/web-console/CHANGELOG.md#003---2022-08-23)
=> chore(core): bump web-console version to 0.0.3

core/src/main/c/freebsd/files.c
=> fix(core): fix missing native function on freebsd

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/griffin/O3Test.java
=> fix(core): fix segfault crash on o3 sort of string null values

core/src/main/java/io/questdb/griffin/engine/functions/constants/StrConstant.java, core/src/main/java/io/questdb/std/Chars.java, core/src/main/java/io/questdb/std/GenericLexer.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/EscapeTest.java, core/src/test/java/io/questdb/griffin/ExpressionParserTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java, core/src/test/java/io/questdb/std/GenericLexerTest.java
=> fix(sql): add single quotes escaping within string literals

core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java
Unexpected errors need better visibility.
=> chore(http): change log level to critical for unexpected errors

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSampleByCursor.java, core/src/test/java/io/questdb/griffin/SampleBySqlParserTest.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
=> fix(sql): fix UnsupportedOperationException thrown on sample by with invalid values

core/pom.xml
- Add popup to show keyboard shortcuts [a3a10c9b](https://github.com/questdb/ui/commit/a3a10c9b8678de761a1e9ce1ab380837d9121e2a)
- Add info about an available update to QuestDB
[changelog](https://github.com/questdb/ui/blob/main/packages/web-console/CHANGELOG.md)
=> chore(core): bump web-console version to 0.0.5

core/src/main/java/io/questdb/cairo/TableWriter.java
- Log O3 context to help us understand the shape of the incoming data. This can potentially help us tune `lag` parameters
=> chore(core): add debug information around O3 data shape

README.md
This changes some wording in the README.md file as there are some stuff in my opinion that could have been improved.
=> docs(README.md) Change some wording

core/src/main/java/io/questdb/cairo/RecordChain.java, core/src/main/java/io/questdb/cairo/TxReader.java, core/src/main/java/io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/groupby/MapSymbolColumn.java, core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/orderby/RecordTreeChain.java, core/src/main/java/io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/orderby/SortedRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/FilteredRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByRecordCursorFactory.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Also improves close discipline in record cursor factories
=> fix(sql): fix unexpected NPE thrown in query with analytical function and filter

core/src/main/java/io/questdb/cutlass/text/TextLoader.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpO3Test.java
Attempting to fix CI crash on windows
=> test(ilp): fixing access violation in test

core/src/main/java/io/questdb/griffin/DatabaseSnapshotAgent.java, core/src/main/java/io/questdb/std/Chars.java, core/src/test/java/io/questdb/cairo/TableReaderTest.java
=> test(core): fixed flaky testAddColumnPartitionConcurrent

core/src/main/java/io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
=> feat(sql): Support row_number() over() and row_number() over(order by)

core/pom.xml
- Fix broken query marker in editor gutter on Windows [#67](https://github.com/questdb/ui/pull/67)
- Fix position of highlighted row in results grid, when moving it with keyboard arrow down button [#66](https://github.com/questdb/ui/pull/66)
[changelog](https://github.com/questdb/ui/blob/main/packages/web-console/CHANGELOG.md#008---2022-10-19)
=> feat(ui): bump web-console version to 0.0.8

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ReplaceStrFunctionFactory.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java, core/src/test/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactoryTest.java, core/src/test/resources/server.conf, pkg/ami/marketplace/assets/server.conf
=> chore(sql): add buffer size checks to lpad and rpad functions

README.md, i18n/README-PT.md, i18n/README.ar-dz.md, i18n/README.es-es.md, i18n/README.it-it.md, i18n/README.ja-ja.md, i18n/README.ua-ua.md, i18n/README.zh-cn.md, i18n/README.zh-hk.md, i18n/languages.md
Hey,
- I have translated the readme file to Japanese .
- Added the links to the Japanese readme in all the other readme files as well.
- All the links are functional.
- Naming of the readme done as per the guidelines.
Happy merging !
=> docs(core): Translated the readme to Japanese. 

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java, core/src/test/java/io/questdb/griffin/CopyTest.java, core/src/test/resources/csv/test-quotes-rawts.csv
=> fix(sql): fix copy from file with raw timestamp

core/src/main/java/io/questdb/griffin/SqlException.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/griffin/SqlParserUpdateTest.java, core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
fixes https://github.com/questdb/questdb/issues/2625
=> fix(sql): fix spurious ambiguous column name error with sample by and `joins`

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpParser2Test.java, core/src/test/java/io/questdb/cutlass/line/tcp/load/LineData.java
=> test(ilp): fix ILP fuzz update test sending floats instead of strings

core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/WhereClauseParserTest.java
=> fix(sql): fix empty result returned for query with no-op filter

ci/dangerfile.js
this allows using `feat(wal): blah`, `fix(wal): blah` commit messages
=> chore(build): add new "wal" commit message sub-type

core/src/main/java/io/questdb/cairo/pool/ReaderPool.java, core/src/main/java/io/questdb/cairo/pool/WriterPool.java
Swaps CAS with much cheaper volatile reads where possible.
=> chore(core): simplify atomic operations in reader pool

core/src/main/java/io/questdb/cutlass/line/udp/LineUdpLexer.java, core/src/main/java/io/questdb/griffin/CharacterStore.java, core/src/main/java/io/questdb/std/GenericLexer.java, core/src/main/java/io/questdb/std/str/AbstractCharSequence.java, core/src/main/java/io/questdb/std/str/DirectByteCharSequence.java, core/src/main/java/io/questdb/std/str/DirectCharSequence.java, core/src/test/java/io/questdb/griffin/engine/functions/cast/CastTest.java, core/src/test/java/io/questdb/std/str/AbstractCharSequenceTest.java
=> fix(sql): fix possible errors when casting strings to double

core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/griffin/InsertTest.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
Follow up for https://github.com/questdb/questdb/pull/2724 to implement PostgreSQL `insert` syntax:
https://www.postgresql.org/docs/current/sql-insert.html
=> chore(sql): support PostgreSQL `insert` ... `with` syntax

core/src/main/java/io/questdb/cairo/wal/WalEventReader.java, core/src/main/java/io/questdb/cairo/wal/WalUtils.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessorState.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/main/java/io/questdb/griffin/engine/functions/str/TrimConstFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/str/TrimFunction.java, core/src/main/java/io/questdb/griffin/model/IntervalUtils.java, core/src/main/java/io/questdb/jit/CompiledFilterIRSerializer.java, core/src/main/java/io/questdb/std/Chars.java, core/src/main/java/io/questdb/std/Numbers.java, core/src/test/java/io/questdb/cairo/IndexBuilderTest.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java, core/src/test/java/io/questdb/griffin/engine/functions/str/LTrimFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/str/RTrimFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/str/TrimFunctionFactoryTest.java
- fix code formatting issues
- added @ formatter:off to Numbers.java (works with intellij default settings only)
=> style(core): code formatting

core/src/main/java/io/questdb/Bootstrap.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/processors/QueryCache.java, core/src/test/java/io/questdb/ServerMainTest.java
Fixes https://github.com/questdb/questdb/issues/2777
=> fix(core): fix shutdown errors when HTTP is disabled

core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/HttpHeaderParser.java, core/src/main/java/io/questdb/cutlass/http/HttpMultipartContentParser.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/LocalValue.java, core/src/main/java/io/questdb/cutlass/http/WaitProcessor.java, core/src/main/java/io/questdb/network/IODispatcherLinux.java, core/src/main/java/io/questdb/std/WeakObjectPoolBase.java, core/src/test/java/io/questdb/cutlass/http/DispatcherWriterQueueTest.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/http/RetryIODispatcherTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AlterTableLineTcpReceiverTest.java
This patch is a side effect of https://github.com/questdb/questdb/issues/1815#issuecomment-1325032438. It includes a number of minor improvements in HTTP code and tests.
=> test(http): improve failure handling

core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableReaderMetadata.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/std/ObjList.java, core/src/test/java/io/questdb/cairo/CairoTestUtils.java, core/src/test/java/io/questdb/cairo/TableReaderMetadataTest.java, core/src/test/java/io/questdb/cairo/TableReaderReloadFuzzTest.java, core/src/test/java/io/questdb/cairo/TableReaderTest.java, core/src/test/java/io/questdb/cairo/TxnTest.java, core/src/test/java/io/questdb/griffin/AlterTableDetachPartitionTest.java, core/src/test/java/io/questdb/griffin/O3PartitionPurgeTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
Fuzz test for TableReader.reload() and some code cleanup.
=> chore(core): table reader reload fuzz test

core/pom.xml, utils/pom.xml
=> test(pgwire): upgrade postgres jdbc driver

core/src/test/java/io/questdb/cutlass/http/SendAndReceiveRequestBuilder.java
=> chore(http): fix flapping test by increasing timeout

core/src/main/java/io/questdb/cairo/TableNameRegistryFileStore.java, core/src/test/java/io/questdb/cairo/wal/TableNameRegistryTest.java
=> test(core): fix flaky test `testConcurrentReadWriteAndReload`

core/pom.xml
Releasing exciting new look and feel from https://github.com/questdb/ui/pull/78
=> feat(ui): bumping Web Console to 0.0.11

core/pom.xml
Web Console changes are in https://github.com/questdb/ui/pull/95
=> chore(ui): web console release

core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverTest.java
=> test(wal): make ILP WAL rename / drop tests more stable

core/src/main/java/io/questdb/cairo/sql/RecordCursorFactory.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java, core/src/test/java/io/questdb/cairo/pool/ReaderPoolTest.java, core/src/test/java/io/questdb/griffin/engine/analytic/AnalyticFunctionTest.java
Closes #2620
Closes #2705
Also fixes an invalid assertion in `ReaderPoolTest#testConcurrentRead()`.
=> fix(sql): make sure that order by is not ignored by row_number() function

core/pom.xml
reference updated version of the Web Console:
https://github.com/questdb/ui/pull/111
=> feat(ui): grid improvements

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/mp/SOCountDownLatch.java, core/src/test/java/io/questdb/test/ServerMainForeignTableTest.java, core/src/test/java/io/questdb/test/cutlass/text/CairoConfigurationWrapper.java
Fixes error 
```
2023-04-02T14:57:41.628661Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.griffin.wal.WalWriterFuzzTest.testWalWriteRollbackTruncateHeavy : 
io.questdb.cairo.CairoException: [0] Partition '2022-02-24' does not exist in table 'testWalWriteRollbackTruncateHeavy_nonwal' directory. Run [ALTER TABLE testWalWriteRollbackTruncateHeavy_nonwal DROP PARTITION LIST '2022-02-24'] to repair the table or restore the partition directory.
```
found in fuzz tests
=> fix(core): fix no partition error after truncate and rollback

core/src/main/java/io/questdb/cutlass/http/DefaultHttpServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/MimeTypesCache.java, core/src/test/java/io/questdb/test/cutlass/http/MimeTypesCacheTest.java
ServerMain may not start if "mime.types" is on classpath but inside a jar. This could happen in tests.
=> test(core): load mime.types from java + file

core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceJob.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/cairo/wal/TableRenameSupportExecutionContext.java, core/src/main/java/io/questdb/griffin/SqlExecutionContext.java, core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java, core/src/test/java/io/questdb/test/cutlass/text/SqlExecutionContextStub.java, core/src/test/java/io/questdb/test/griffin/UpdateTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
=> fix(sql): fix UPDATE sql timeout issue for WAL tables

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/test/java/io/questdb/test/griffin/JoinTest.java
=> fix(sql): NullPointerException on join with function filter

core/src/main/java/io/questdb/cairo/pool/AbstractMultiTenantPool.java, core/src/test/java/io/questdb/test/cairo/pool/ReaderPoolTest.java
Concurrent queries might fail spuriously because of a bug in one of our pool implementation.
The issue could be seen also when multiple concurrent ILP/PGWire/REST connections are created for ingestion but it is very unlikely to happen. Much easier to hit the problem with concurrent queries.
The underlying issue is that multi tenant pools (TableReader/Metadata/WalWriter pools) can throw EntryUnavailableException even when the pool is not exhausted.
If there is a race between threads to allocate a new entry, the thread which lost the race should wait for the entry to be created by the winning thread, and compete for owning that entry instead of throwing EntryUnavailableException.
=> fix(core): fix spurious SQL errors under concurrent SQL execution

core/src/test/java/io/questdb/test/griffin/O3MaxLagFuzzTest.java
Fixes broken test that plagued few a PRs we are releasing
=> chore(core): fixed test that flapped on Windows only

core/src/main/java/io/questdb/cairo/TableWriter.java
Fix assertion error found in fuzz tests.
The error happens when all records are copied into the lag instead of being applied to the table, which is a valid case when all the records before `commitToTimestamp` are fast applied from the lag to the current partition already.
=> chore(core): fix wal apply error

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
=> fix(sql): fix unhandled error when compiling group-by SQLs that contain table aliases

core/docker-entrypoint.sh, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerTest.java
=> chore(core): revert breaking changes

core/src/main/java/io/questdb/ServerMain.java, core/src/test/java/io/questdb/test/AbstractBootstrapTest.java, core/src/test/java/io/questdb/test/ServerMainIlpAuthTest.java
=> fix(ilp): remove wrong db/ segment from ILP auth config path

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerTest.java
=> fix(sql): fix StringIndexOutOfBoundsException in sub-select parsing

core/src/main/java/io/questdb/cairo/sql/RecordCursorFactory.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/functions/bind/CompiledFilterSymbolBindVariable.java, core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java, core/src/main/java/io/questdb/griffin/engine/functions/constants/SymbolConstant.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstSymbolGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/GroupByTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
=> fix(sql): fix AssertionError in SAMPLE BY and GROUP BY queries over symbol columns

core/pom.xml
Web Console change log: https://github.com/questdb/ui/blob/main/packages/web-console/CHANGELOG.md
=> chore(ui): web console version bump to 0.2.2

benchmarks/pom.xml, core/Dockerfile, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
=> build: 7.2

core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverTest.java
=> test(core): fix flaky testRenameTableSameMeta

core/pom.xml
Changelog https://github.com/questdb/ui/blob/main/packages/web-console/CHANGELOG.md#024---2023-06-29
=> chore(ui): web console bump to 0.2.4

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java
simple renaming, no functional changes
=> chore(core): role -> service account

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/GroupByRewriteTest.java
Addresses https://github.com/questdb/questdb/issues/3526
=> fix(sql): better handling invalid SUM function parameters 

core/src/main/java/io/questdb/cairo/TableConverter.java, core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
Reset _txn file LAG parameters on conversion to and from WAL type.
=> fix(core): fix wal to non-wal table conversion leaving table non-writable

core/src/main/java/io/questdb/cairo/O3PartitionJob.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/griffin/O3SquashPartitionTest.java
=> fix(core): fix physical rows written metric on partition split

core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/main/java/io/questdb/griffin/engine/functions/CharFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/AbstractCastToSymbolFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastCharToSymbolFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/NullIfStrFunctionFactory.java, core/src/main/java/io/questdb/std/Chars.java, core/src/test/java/io/questdb/test/griffin/UpdateTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/NullIfFunctionFactoryTest.java
=> fix(sql): fix exception updating symbol column with char value

core/src/main/java/io/questdb/cairo/VacuumColumnVersions.java, core/src/test/java/io/questdb/test/cairo/TableReaderTest.java, core/src/test/java/io/questdb/test/griffin/VacuumColumnVersionTest.java
=> fix(core): fix vacuum command deleting live table columns

core/pom.xml
Changelog: https://github.com/questdb/ui/commit/5acf913317bcfc8a88620e2605c82d5487b5a39c#diff-5bf9fcf08dd4448faaf894e793c3f3e44a60438a26999a96d00a25f868272aa9R19
=> chore(ui): web console bump to 0.2.5

benchmarks/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
=> build: 7.3

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
=> fix(sql): fix error on order by empty string & join condition pushdown

README.md
adding link to quickstart repository
=> docs(core): adding link in README

core/src/main/java/io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, utils/pom.xml, utils/src/test/java/io/questdb/cliutil/Table2IlpTest.java
=> fix(pgwire): fix pg wire network send error

i18n/README.it-it.md
Updated the README translation in Italian
=> chore(ui): Update README.it-it.md

core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/test/griffin/CreateTableDedupTest.java
closes https://github.com/questdb/questdb/issues/3688
=> fix(sql): allow quotes around dedup keys

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/test/java/io/questdb/test/cairo/SecurityContextTest.java
=> chore(core): add authorizeSelectOnAnyColumn method

core/src/main/java/io/questdb/std/DirectIntList.java, core/src/main/java/io/questdb/std/DirectLongList.java, core/src/test/java/io/questdb/test/std/DirectIntListTest.java, core/src/test/java/io/questdb/test/std/DirectLongListTest.java, core/src/test/java/io/questdb/test/std/VectTest.java
=> chore(core): introduce internal off-heap data structures

core/src/main/java/io/questdb/std/Chars.java, core/src/main/java/io/questdb/std/str/StringSink.java, core/src/test/java/io/questdb/test/std/StringSinkTest.java
These methods are used in ent tests and it's worth having them for the sake of API consistency.
=> chore(core): readd StringSink#lastIndexOf() methods

core/src/main/java/io/questdb/cairo/sql/RecordCursorFactory.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
=> chore(core): remove the isSelectCacheable() flag

core/pom.xml
- add the missing data types: ipv4, byte, binary, long256, uuid by @insmac in https://github.com/questdb/ui/pull/191
- allow writing multiple files to the same target table by @insmac in https://github.com/questdb/ui/pull/192
- incorrect timestamp check icon when selected by @insmac in https://github.com/questdb/ui/pull/191
- multiple designated timestamps could be selected by @insmac in https://github.com/questdb/ui/pull/191
- an unnecessary second scrollbar appeared in the UI by @insmac  in https://github.com/questdb/ui/pull/191
=> feat(ui): multiple features and fixes

benchmarks/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
Release https://github.com/questdb/questdb/releases/tag/7.3.2
=> build: 7.3.2

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/main/java/io/questdb/cairo/security/SecurityContextFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/CurrentUserFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpThreadStacksFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/SessionUserFunctionFactory.java, core/src/test/java/io/questdb/test/cairo/SecurityContextTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGSecurityTest.java
Also fixes hardcoded value returned from `session_user()`.
=> chore(core): add admin action security check

README.md, i18n/README.ar-dz.md, i18n/README.es-es.md, i18n/README.hn-in.md, i18n/README.it-it.md, i18n/README.ja-ja.md, i18n/README.pt.md, i18n/README.tr-tr.md, i18n/README.ua-ua.md, i18n/README.zh-cn.md, i18n/README.zh-hk.md, i18n/languages.md
- missing link to Hindi translation
- broken link to the Turkish translation 
- add Hindi translation to languages.md
=> docs(core): add Hindi link to README(s)

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
=> chore(core): split method to to independently being able to check DEDUP enable/disable

core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
=> fix(core): call correct method to authenticate enabling dedup

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
=> fix(pgwire): fix pgwire transaction flag not cleaned on context reuse

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/KeywordAsTableNameTest.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
adding back some code which was removed accidentally
=> chore(core): support enabling/disabling account

core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/std/Files.java
See: https://github.com/docker/for-mac/issues/7004
and a minimized reproducer: https://github.com/jerrinot/flocktest
=> fix(core): workaround for broken file locking on Docker Desktop on MacOS

core/src/main/java/io/questdb/cairo/wal/WalEventReader.java, core/src/test/java/io/questdb/test/ConcurrentTcpSenderBootstrapTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
Fix edge case when WAL table can be left suspended when WALE files have all the data but `_event` and `_event.i` files have inconsistency between them. This resulted in error like 
```
2023-10-04T10:09:36.188169Z C i.q.c.w.ApplyWal2TableJob job failed, table suspended [table=tenant_47~498, error=segment /var/lib/questdb/db/tenant_47~498/wal3/0/_event.i does not have txn with id 379, offset=25401, indexFileSize=3400, maxTxn=424, size=-1, errno=0]
```
where `_event.i` file size of `3400` is enough to get transaction `379` but not enough to read to the maximum transaction of `424`.
=> fix(core): fix wal apply suspending table on edge condition

core/src/main/java/io/questdb/griffin/JsonPlanSink.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/JsonPlanSinkTest.java
=> fix(sql): fix json plan redundant double quote

benchmarks/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
release https://github.com/questdb/questdb/releases/tag/7.3.3
=> build: 7.3.3

README.md
=> docs(core): Update README.md

core/src/main/java/io/questdb/cairo/CairoException.java, core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/test/cairo/SecurityContextTest.java
Security context hook for checking access to REST, PG and ILP endpoints.
=> chore(core): endpoint permissions

i18n/README.es-es.md
Adding a section for cloud, based on the EN version.
=> docs(core): add section about the cloud to Spanish README

i18n/README.ar-dz.md, i18n/README.es-es.md, i18n/README.hn-in.md, i18n/README.it-it.md, i18n/README.ja-ja.md, i18n/README.pt.md, i18n/README.tr-tr.md, i18n/README.ua-ua.md, i18n/README.zh-cn.md, i18n/README.zh-hk.md
- broken link to the Hindi translation
=> chore(docs): fix broken link in Hindi README

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/test/griffin/DistinctTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/CountTest.java
=> fix(sql): fix ArrayIndexOutOfBoundsException in select distinct with duplicate columns

core/src/test/java/io/questdb/test/std/bytes/DirectByteSinkTest.java
Fixed a flaky test introduced in https://github.com/questdb/questdb/pull/3864.
=> chore(core): fixed flaky DirectByteSinkTest

core/src/main/c/windows/timer.h
=> chore(core): fix license header

core/src/main/java/io/questdb/cairo/CairoEngine.java
required by https://github.com/questdb/questdb-enterprise/pull/200
=> chore(core): reformatting

core/src/main/java/io/questdb/cairo/TableWriter.java
Fixes file descriptor leak found by fuzz test. A leak can happen when the WAL table is dropped and the WAL Purge job deletes the segment files simultaneously as TableWriter applies it.
```
2023-11-05T15:23:43.181707Z  E i.q.t.TestListener ***** Test Failed *****io.questdb.test.griffin.wal.WalWriterFuzzTest.testWalAddRemoveCommitDropFuzz duration_ms=2880 : 
java.lang.AssertionError: file descriptors, expected: [16,13,17,18], actual: [16,13,17,70,18] expected:<4> but was:<5>
```
=> fix(core): fix random file descriptor leak on WAL table drop

core/src/main/java/io/questdb/cutlass/Services.java, core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/HttpRequestProcessor.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/test/java/io/questdb/test/cutlass/http/HttpMinTestBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
cookies processed on /exec endpoint only
=> chore(core): cookies processed on /exec endpoint only

core/src/main/resources/io/questdb/site/conf/server.conf
introduce Enterprise options to server.conf to help enterprise users configure the product
=> chore(core): add ent conf entries to server.conf

core/pom.xml
Bumping Web Console to the newest version - changelog: https://github.com/questdb/ui/pull/237
=> chore(ui): bump web console to 0.3.2

core/src/test/java/io/questdb/test/cairo/CairoEngineTest.java
fixes https://github.com/questdb/questdb/issues/3987
=> test(core): fix flaky engine test

core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/StringAggGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/StringAggGroupByFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/StringAggGroupByFunctionFactoryTest.java
=> feat(sql): string_agg function support in keyed group by queries

core/src/test/java/io/questdb/test/griffin/SqlExceptionTest.java
Add test case for UnsupportedCast SqlException error in SqlExceptionTest
=> test(sql): add new SqlException test case

benchmarks/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
release https://github.com/questdb/questdb/releases/tag/7.3.6
=> build: 7.3.6

benchmarks/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
https://github.com/questdb/questdb/releases/tag/7.3.7
=> build: 7.3.7

core/src/main/java/io/questdb/griffin/engine/functions/conditional/NullIfDoubleFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/NullIfFunctionFactoryTest.java
Issue #4062 `nullif` not working on double.
=> feat(sql): add `nullif(double, double)` SQL function

core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstNotNullStrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/LastNotNullStrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/LastStrGroupByFunction.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/FirstAndLastStrGroupByFunctionFactoryTest.java
=> fix(sql): fix handling of keyed string aggregation of first(), first_not_null(), last(), last_not_null() functions

core/src/main/java/io/questdb/cairo/CairoException.java, core/src/main/java/io/questdb/cairo/TxReader.java, core/src/main/java/io/questdb/cairo/wal/CheckWalTransactionsJob.java, core/src/main/java/io/questdb/std/FilesFacadeImpl.java, core/src/test/java/io/questdb/test/FilesTest.java, core/src/test/java/io/questdb/test/cairo/TableNameRegistryTest.java, core/src/test/java/io/questdb/test/griffin/SnapshotTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByAllocatorTest.java, core/src/test/java/io/questdb/test/std/TestFilesFacadeImpl.java
related to https://github.com/questdb/questdb/issues/4119
=> fix(core): reduce unnecessary error logging when table is dropped

core/src/main/java/io/questdb/griffin/QueryRegistry.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
=> chore(core): fix flaky query cancellation tests

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/sql/TableReferenceOutOfDateException.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/cairo/CairoTestConfiguration.java, core/src/test/java/io/questdb/test/cairo/ConfigurationOverrides.java, core/src/test/java/io/questdb/test/cairo/Overrides.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGMultiStatementMessageTest.java
=> test(sql): introduce cairo.sql.max.recompile.attempts config to make test stable

core/src/main/java/io/questdb/Bootstrap.java, core/src/test/java/io/questdb/test/BootstrapTest.java
Bootstrap refactoring for extension
required by https://github.com/questdb/questdb-enterprise/pull/354
=> chore(core): bootstrap refactoring for extension

core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java, core/src/test/java/io/questdb/test/cutlass/http/HttpSecurityTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
Required by https://github.com/questdb/questdb-enterprise/pull/374
=> chore(core): remove basic auth realm from HTTP 401 (Unauthorized) responses

README.md
Added link for the Taxi Dataset real-time dashboards
=> chore(ui): Update README.md

core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java, core/src/test/java/io/questdb/test/cutlass/http/HttpSecurityTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
This is not user-facing issue.
Tandem PR: https://github.com/questdb/questdb-enterprise/pull/378
=> chore(http): fix basic auth handling

core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java, core/src/test/java/io/questdb/test/std/str/DirectUtf8SinkTest.java
=> fix(core): fix wal table is suspended after invalid drop partition SQL

core/src/main/java/io/questdb/cutlass/json/JsonLexer.java
Doh. Fixes test crashes. Production code does not release text loader often.
=> fix(core): fix double-free in text loader

core/src/main/java/io/questdb/client/Sender.java
it should be 1_000 ms, not 10_000 ms.
=> chore(ilp): fix auto_flush_interval default

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java, core/src/test/java/io/questdb/test/cutlass/http/SettingsEndpointTest.java
required by https://github.com/questdb/questdb-enterprise/pull/392
tandem, but can be merged without https://github.com/questdb/questdb-enterprise/pull/392
=> chore(core): json types in web console settings

core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpSenderTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByUtf8SinkTest.java
Some of the recently merged PRs caused compilation failures. 
This change is fixing that.
=> chore(build): test compilation issues

core/src/main/java/io/questdb/griffin/engine/functions/str/LPadFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/LPadStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/RPadFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/RPadStrFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/LPadFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/LPadStrFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/RPadFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/RPadStrFunctionFactoryTest.java
=> fix(sql): fix potentially incorrect values produced by LPad/RPad functions

i18n/README.zh-hk.md
Fixed broken image and wrong PR base in https://github.com/questdb/questdb/pull/4330
=> docs(core): [I18N] Update README.zh-hk.md for TSBS benchmark and its explainer (2)

i18n/README.zh-cn.md
Add `zh-cn` version translation.
=> docs(core): fix i18n zh-cn questdb-compares broken image

core/src/main/java/io/questdb/cairo/AbstractTableNameRegistry.java, core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/TableNameRegistry.java, core/src/main/java/io/questdb/cairo/wal/WalPurgeJob.java
Also refactors table registry API to check if table is marked as dropped by directory name
=>  fix(core): remove table 'lock' file on drop

i18n/README.tr-tr.md
I have updated Turkish readme file according to english version of it on `doc/how questdb compares `  branch.  Related with #4297
=> Turkish README File Update on doc/how questdb compares

core/src/main/java/io/questdb/cairo/ColumnTypeDriver.java, core/src/main/java/io/questdb/cairo/O3CopyJob.java, core/src/main/java/io/questdb/cairo/O3OpenColumnJob.java, core/src/main/java/io/questdb/cairo/StringTypeDriver.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java, core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java, core/src/main/java/io/questdb/cairo/wal/CopyWalSegmentUtils.java, core/src/main/java/io/questdb/griffin/UpdateOperatorImpl.java, core/src/test/java/io/questdb/test/cairo/VarcharTypeDriverTest.java, core/src/test/java/io/questdb/test/griffin/AbstractO3Test.java, core/src/test/java/io/questdb/test/griffin/O3Test.java
Added an assertion to the affected code path.
=> fix(core): rare segfault during o3 commit of a non-wal table

.all-contributorsrc, README.md, i18n/README.ar-dz.md, i18n/README.es-es.md, i18n/README.hn-in.md, i18n/README.it-it.md, i18n/README.ja-ja.md, i18n/README.pt.md, i18n/README.tr-tr.md, i18n/README.ua-ua.md, i18n/README.vi-vn.md, i18n/README.zh-cn.md, i18n/README.zh-hk.md, i18n/languages.md
I have added Vietnamese support and configured other READMEs for that.
=> chore(docs): Vietnamese README translation

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/SqlUtil.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
fixes https://github.com/questdb/questdb/issues/4366
=> fix(sql): fix error in some CASE statements when ELSE branch is missing

core/src/main/java/io/questdb/griffin/engine/functions/CharFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/IPv4Function.java, core/src/main/java/io/questdb/griffin/engine/functions/Long128Function.java, core/src/main/java/io/questdb/griffin/engine/functions/Long256Function.java, core/src/main/java/io/questdb/griffin/engine/functions/StrFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/SymbolFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastCharToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastDateToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastDoubleToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastFloatToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastIPv4ToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastIntToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastLongToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastStrToVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastTimestampToVarcharFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/UpdateTest.java
Refs #4360 (fixes varchar update bug item)
=> chore(sql): fix nulls interpreted as empty varchars in update statements

README.md, i18n/README.it-it.md
Hi, I have finally updated (and improved) the italian documentation according to the english version on `doc/how questdb compares` branch. This is related to #4297 
Also in the english readme there was written port `9000` in the influxdb line protocol instead of port `9009 `and I also fixed that.
I hope that all is correct :)
P.s: how is it possible to add my profile to the contributor in the `README` file?
=> chore(docs): Italian README File Update on doc/how questdb compares

core/src/main/java/io/questdb/client/Sender.java, core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpSenderTest.java
This PR introduces a new parameter to configuration string `auto_flush_bytes`.
The parameter configures `Sender` to auto-flush when it accumulates a given number of bytes. Only the TCP transport allows this parameter since the HTTP transport does not support byte-based flushes.
TCP transport uses a fixed-size buffer, it means this parameter has the same effect as `min_size_buf` and it's introduced only for compatibility with other clients. When both `auto_flush_bytes` and `min_size_buf` are used then they must be set the same value. 
**Example:**
This program will flush in 1kB increments. 
```java
public class HttpExample {
public static void main(String[] args) {
try (Sender sender = Sender.fromConfig("tcp::addr=localhost:9009;auto_flush_bytes=1024;")) {
for (int i = 0; i < 1_000_000; …
```
=> feat(ilp): client configuration string supports auto_flush_bytes

benchmarks/pom.xml, compat/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
release https://github.com/questdb/questdb/releases/tag/7.4.1
=> build: 7.4.1

benchmarks/pom.xml, compat/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
release https://github.com/questdb/questdb/releases/tag/7.4.2
=> build: 7.4.2

core/src/main/java/io/questdb/std/Chars.java, core/src/test/java/io/questdb/test/std/str/CharsTest.java, core/src/test/java/io/questdb/test/std/str/PathTest.java
tandem: https://github.com/questdb/questdb-enterprise/pull/427
=> chore(core): sync OSS and Ent

core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java
=> chore(core): zero extra null varchar bytes

core/Dockerfile, core/pom.xml
- upgrade to web console 0.4.2
- also changed Dockerfile because of GLIBC upgrade
Tested docker file changes by building the docker image locally, script worked.
Also did manual testing for the web console, no issues found.
=> chore(ui): upgrade to web console 0.4.2

core/src/main/java/io/questdb/cairo/wal/CopyWalSegmentUtils.java, core/src/test/java/io/questdb/test/fuzz/FuzzChangeColumnTypeOperation.java
=> chore(core): fix incorrect WAL file trimming leading to unsafe access error

core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java
ORDER BY with LIMIT queries are faster if the query supports random access.
Implementation details: 
The old code was optimized for tree traversal. When building a tree chain, `LimitedSizeLongTreeChain.put()` would unconditionally set the comparator's left value to the current record and then call `comparator.compare()` with the minimum/maximum record. This approach is logical if you are preparing to traverse the tree. However, we can assume that, typically, the LIMIT is significantly smaller than the total number of entries returned by the inner cursor. Therefore, we usually won't insert anything into the tree chain. If that is the case, then `put()` will exit at the initial guard, and it makes sense to cache the more stable minimum/maximum record on the left side of the comparator.
=> perf(sql): optimize ORDER BY with LIMIT

core/src/main/java/io/questdb/cairo/ColumnTypeDriver.java, core/src/main/java/io/questdb/cairo/StringTypeDriver.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java, core/src/test/java/io/questdb/test/cairo/VarcharTypeDriverTest.java
Also: Documented the contract of setAppendPosition() since it's rather non-intuitive.
=> test(core): fix size estimation returned by driver.testSetAppendPosition()

core/pom.xml
=> chore(core): upgrade to web console 0.4.3

ci/templates/self-hosted-jobs.yml, ci/templates/start-self-hosted-job.yml, ci/test-pipeline.yml, core/README.md, core/src/test/java/io/questdb/test/cairo/TableReaderMetadataTest.java, core/src/test/java/io/questdb/test/griffin/O3FailureTest.java, core/src/test/java/io/questdb/test/griffin/O3SquashPartitionTest.java, core/src/test/java/io/questdb/test/griffin/O3Test.java
We added recently (since version 8.0.0) zfs compression support and this PR will add a new x86_64 self-hosted linux instance with a zfs data volume
=> chore(build): add zfs self hosted agent

README.md
Add capacity planning section for production workloads
=> docs(core): refresh README.md

core/pom.xml
Web Console release notes: https://github.com/questdb/ui/pull/304
- show login dialog for QuestDB OSS when authentication is enabled [#300](https://github.com/questdb/ui/pull/300)
- fix OAuth2 redirect URI [#303](https://github.com/questdb/ui/pull/303)
=> chore(build): upgrade to web console 0.4.5

core/src/test/java/io/questdb/test/ServerMainShowPartitionsTest.java
Fixes #3811
This commit addresses multiple issues identified in the test testServerMainShowPartitions():
1. Thread Safety: Previously, the test used an ArrayList inside an AtomicReference. Multiple threads could dereference and modify the ArrayList concurrently, leading to unpredictable behavior.
2. Timeout Management: The test had a relatively short timeout of 3 seconds. If the worker threads were delayed due to a CI box hiccup, they could attempt to access partitions from a table that the main thread had already dropped, resulting in errors.
3. Error Handling Inconsistency: There was an issue where if the error occurred as described in point 2, it would not always be caught. This could happen if the main thread checked the 'errors' list before the worker threads had a chance to log …
=> test(sql): stabilize flaky test - testServerMainShowPartitions()

README.md
Includes the [community forum](https://community.questdb.io) 🎉
=> chore(docs): updates README with new community

README.md
=> docs(core): update readme paragraph

core/pom.xml
updating web console that brings this fix: https://github.com/questdb/ui/pull/310
=> fix(ui): fix Charts when using together with OAuth

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/test/cutlass/pgwire/BasePGTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
=> fix(pgwire): fix insert as select statement running twice on pgwire when using prepared statements

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/griffin/DistinctWithLimitTest.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/LimitTest.java
=> perf(sql): optimize queries with virtual columns, filter, and limit

core/src/main/c/share/zlib-1.2.8/gzlib.c
=> chore(build): fix C build, accidental change

core/src/main/c/share/zlib-1.2.8/gzlib.c, core/src/main/java/io/questdb/DynamicUsernamePasswordMatcher.java, core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cutlass/auth/UsernamePasswordMatcher.java, core/src/main/java/io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java
required by https://github.com/questdb/questdb-enterprise/pull/474
=> chore(core): remove state from pwd matcher to fix flapping test

core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/ContainsEqIPv4StrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/ContainsEqIPv4Utils.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/ContainsEqIPv4VarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/ContainsIPv4StrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/ContainsIPv4Utils.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/ContainsIPv4VarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/NegContainsEqIPv4StrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/NegContainsEqIPv4VarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/NegContainsIPv4StrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/NegContainsIPv4VarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/IPv4VarcharNetmaskFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/IPv4Test.java
=> feat(sql): support non-constant arguments in IPv4 contains and netmask functions

core/pom.xml
bumping the Web Console version to fix ☝️
=> fix(ui): fix incorrect txn number display in the "table suspended" window

benchmarks/pom.xml, compat/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
release https://github.com/questdb/questdb/releases/tag/8.1.1
=> build: 8.1.1

core/src/main/java/io/questdb/cutlass/line/tcp/LineWalAppender.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java
Previously, when an ILP client attempted to insert a non-UUID string into a UUID column, QuestDB internals would return an ImplicitCastingException.
This resulted in the HTTP server returning a HTTP 500 status code instead of the more appropriate HTTP 400.
Clients interpret an HTTP 500 status code as a transient error and would retry. This change prevents a retry loop by explicitly validating that the received value is an actual UUID.
Fixes #4932
=> fix(ilp): ILP clients should not retry when inserting a bad UUID value

core/src/main/java/io/questdb/network/Net.java, core/src/test/java/io/questdb/test/std/VectTest.java
this test class alone was leaking 150MB+ of native memory
=> test(core): fix mem leak in VectTest

ci/test-pipeline.yml
Fixing #5049 that had wrong yaml indentation
=> ci(build): disable ci auto triggers on draft PRs (fix 2)

benchmarks/pom.xml, compat/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
release: https://github.com/questdb/questdb/releases/tag/8.1.3
=> build: 8.1.3

core/src/main/java/io/questdb/cairo/TableReader.java
Fixes fuzz test failure, no impact on the production code
=> chore(core): reorder partition access control and scoreboard tnx release to fix fuzz test

core/src/main/java/io/questdb/cairo/DatabaseCheckpointAgent.java, core/src/main/java/io/questdb/cairo/MetadataCache.java, core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java, core/src/test/java/io/questdb/test/AbstractCairoTest.java, core/src/test/java/io/questdb/test/cairo/MetadataCacheTest.java
Ent PR: https://github.com/questdb/questdb-enterprise/pull/491
=> chore(core): fix broken checkpoint recovery

core/src/main/java/io/questdb/cairo/MetadataCache.java, core/src/main/java/io/questdb/cairo/TableNameRegistryRW.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java, core/src/test/java/io/questdb/test/griffin/model/IntrinsicModelTest.java
fix problem introduced in #5144
=> chore(core): fix code not executing as expected with asserts disabled

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/main/java/io/questdb/griffin/QueryRegistry.java, core/src/main/java/io/questdb/griffin/engine/functions/activity/QueryActivityFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpMemoryUsageFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpThreadStacksFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/FlushQueryCacheFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/SimulateCrashFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/SimulateWarningsFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndLogFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/table/HydrateTableMetadataFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/test/TestNPEFactory.java, core/src/test/java/io/questdb/test/cairo/SecurityContextTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/activity/CancelQueryFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/activity/QueryActivityFunctionFactoryTest.java
replacing admin only check with permission check hooks.
required by https://github.com/questdb/questdb-enterprise/pull/521
=> chore(core): replace admin-only checks with permissions

core/src/main/java/io/questdb/std/str/Utf8s.java
fast-path for strings known to be ascii.
improves Clickbench Q27 on my local from 470ms to 410ms.
=> perf(sql): performance improvement in length(varchar) function

core/pom.xml
pickup web console 0.6.4
---------------------------------
- Support for ID token in Auth [#355](https://github.com/questdb/ui/pull/355)
- News Image zoom [#350](https://github.com/questdb/ui/pull/350)
- Highlight integer numbers that include `_` (underscore) separator
[#353](https://github.com/questdb/ui/pull/353)
- Handle and display error received while scrolling the grid
[#348](https://github.com/questdb/ui/pull/348)
=> chore(core): pickup web console 0.6.4

core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java
Changes:
- `close()` reset fields in the same order as they are declared in the class. it's easier for maintainability since there is a nice symmetry between fields declaration and `close()`
- added some forgotten fields: `sqlAffectedRowCount` and `msgBindParameterFormatCodes`
- `close()` no longer delegates to clearState(). instead it clears all fields on its own. again, it's easier to see a forgotten field.
=> chore(pgwire): improve PGPipelineEntry state clearing before returning back to object pool

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/cairo/wal/OperationExecutor.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/engine/functions/table/WaitWalTableFunctionFactory.java, core/src/test/java/io/questdb/test/sqllogictest/AbstractSqllogicTestRunner.java, core/src/test/resources/sqllogictest/test/sql/test_alter_backup_wal_table.test, core/src/test/resources/sqllogictest/test/sql/test_update_rename_wal_table.test
=> chore(sql): fix backup SQL error when table is concurrently changed

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
Fix https://github.com/questdb/questdb/issues/5266
=> fix(sql): fix rewriteOrderBy issue case when orderBy column is not in projection.

README.md
=> docs(core): update kafka url

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableWriter.java
=> fix(core): improve storage error handling to avoid resource leaks

ci/templates/hosted-cover-jobs.yml, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java
=> chore(pgwire): followup for 5296 with a better fix

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/SqlCodeGeneratorTest.java
Fix https://github.com/questdb/questdb/issues/5251
=> fix(sql): fix the missing of ORDER BY position's resolve in the JOIN-UNION QueryModel.

core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
Fix https://github.com/questdb/questdb/issues/5308
=> fix(sql): fix errors for certain queries that use the window function on join with select same columns

core/src/main/java/io/questdb/cairo/O3OpenColumnJob.java
Found by fuzz test
On index file open error during writing to the table there is a chance to leak mapped memory, it's not properly closed in the error handling.
=> fix(core): fix memory leak when handing file open error

compat/src/test/java/io/questdb/compat/ParquetTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
also fixing flapping `testPreparedStatementWithNowFunction[LEGACY]`
=> test(core): flapping ParquetTest.testAllTypesColTopMiddlePartition() fixed

core/pom.xml
- speed up rendering of the metric widgets
=> chore(ui): update web console to 0.7.2 (fixes for 0.7.0)

core/src/main/java/io/questdb/cairo/TableWriter.java
fixes #5348
the issue found by a fuzz test
=> fix(core): edge-case memory leak during disk failure fixed

core/src/main/java/io/questdb/network/AbstractIODispatcher.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
=> fix(http): fix connection leak under memory pressure

core/src/test/java/io/questdb/test/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpReceiverUpdateFuzzTest.java
Add logging to trace table busy exception
=> test(ilp): add more logging in LineTcpReceiverUpdateFuzzTest

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/functions/window/BaseDoubleWindowFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/window/BaseLongWindowFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/window/DenseRankFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/LagDoubleFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/LeadDoubleFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/RankFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/RowNumberFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/window/WindowFunction.java, core/src/main/java/io/questdb/griffin/model/WindowColumn.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java, core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionTest.java
- Refactor the `rank()`  window function to make it more efficient and conform to standard SQL behavior
- introduce `dense_rank()` window function
---
As for the ScalarFunction in the Order By Clause, we do not support it currently.
=> feat(SQL): refactor `rank()` windowFunction and introduce `dense_rank()` windowFunction

core/pom.xml
- Add button to copy query plans and result sets to clipboard in markdown format [#393](https://github.com/questdb/ui/pull/393)
- Escape table name for SHOW CREATE TABLE [#398](https://github.com/questdb/ui/pull/398)
=> chore(ui): upgrade web console to 0.7.6

core/src/main/java/io/questdb/griffin/engine/functions/math/GreatestNumericFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/LeastNumericFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/finance/GreatestNumericFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/finance/LeastNumericFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionTest.java
fix https://community.questdb.com/t/unexpected-window-function-behavior/777
Note: The changes to `WindowFunctionTest` make the MR appear larger than it actually is, due to code rearrangement.
=> fix(sql): Function args in `GreatestNumericFunction` and `LeastNumericFunction` should be deep-cloned

core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationBuilderImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationImpl.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
includes changes from https://github.com/questdb/questdb/pull/5500
=> chore(sql): consistently remove 'public.' prefix

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewReloadOnRestartTest.java, core/src/test/java/io/questdb/test/griffin/AlterTableDropPartitionTest.java
Makes the partition drop atomic. If the partition has splits, it's all splits or none are dropped 
Fixes #5485
=> fix(core): make partition drop atomic

compat/src/test/csharp/Program.cs, compat/src/test/php/runner.php, compat/src/test/python/runner_asyncpg.py, compat/src/test/python/runner_psycopg2.py, compat/src/test/python/runner_psycopg3.py, compat/src/test/resources/test_cases.yaml, compat/src/test/rust/scenarios/src/main.rs, core/src/main/java/io/questdb/cutlass/pgwire/BadProtocolException.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGWireServerModern.java
fixes: https://github.com/questdb/questdb/issues/5512
Additionally logs errors reported to PGWire client in the LOG. So that we have a copy and can fix issues proactively.
=> fix(pgwire): fix handling of sparse bind variables

core/src/main/java/io/questdb/griffin/engine/table/SelectedRecordCursorFactory.java
`SelectedRecordCursorFactory` is now optimized to avoid unnecessary wrapping of the base factory when projected column indexes directly match the base factory's indexes. This optimization maintains proper metadata handling (column renaming and potential removal of trailing columns) while providing a small but consistent performance improvement in Clickbench benchmarks.
=> perf(sql): speed-up of simple projections

core/pom.xml
- add storage details, persistent expand states, symbol details [#409](https://github.com/questdb/ui/pull/409)
- flakiness improvements for CI [#407](https://github.com/questdb/ui/pull/407)
=> chore(ui): upgrade web console to 0.7.8

core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
fix a little parser issue.
close #5544
=> fix(sql): improve error handling for malformed SQL queries

core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java
edge-case protocol violation when a pipeline starts with Close message
=> fix(pgwire): fix edge-case protocol violation when a pipeline starts with Close message

ci/templates/hosted-jobs.yml, ci/test-pipeline.yml, core/src/main/java/io/questdb/Bootstrap.java
Fixes #5386
Fixes CI code coverage
=> fix(core): fix startup logging to only check existing dirs for supported file system

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java, core/src/main/java/io/questdb/griffin/engine/join/JoinRecordMetadata.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationImpl.java, core/src/main/java/io/questdb/griffin/model/ExpressionNode.java, core/src/main/java/io/questdb/std/Chars.java, core/src/test/java/io/questdb/test/griffin/engine/join/JoinPrefixedTablesTest.java
=> fix(sql): fix internal error for some SQLs involving system tables

core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileColumnPool.java, core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileFixFrameColumn.java, core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java, core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java
=> test(core): fix resource leak in `ColumnTypePool` when create column throws exception

core/pom.xml
- hide edit from instance badge for readonly settings [#439](https://github.com/questdb/ui/pull/439)
=> chore(ui): bump web console to 0.7.13

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/sql/InsertOperation.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/TypesAndInsertModern.java, core/src/main/java/io/questdb/griffin/InsertRowImpl.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/InsertAsSelectOperationImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/InsertOperationImpl.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Fixes potential memory leak in plain INSERTs: timestamp and record SQL functions were never closed
=> fix(sql): potential memory leak in plain INSERTs

core/src/test/java/io/questdb/test/cairo/fuzz/WalWriterFuzzTest.java, core/src/test/java/io/questdb/test/fuzz/FuzzTransactionGenerator.java
Fixes https://github.com/questdb/questdb/issues/5731
=> test(core): fix fuzz tests by not generating replace commits on tables with TTLs

README.md
removed some of the illiquid symbols
=> docs(sql): demo queries updated

core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstArrayGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstArrayGroupByFunctionFactory.java, core/src/test/java/io/questdb/test/cairo/ArrayTest.java, core/src/test/java/io/questdb/test/cairo/fuzz/ParallelGroupByFuzzTest.java
Support the simpliest group by function that takes an array as an argument
```SQL
select first(array_column), timestamp
from tbl
sample by 1h
```
=> chore(sql): first(double[]) group by function

benchmarks/pom.xml, compat/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
release https://github.com/questdb/questdb/releases/tag/9.0.1
=> build: 9.0.1

video-tutorial-by-TaniyaKatigar.md
Hello QuestDB Team!
I’ve created a beginner-friendly video tutorial on setting up QuestDB and running the first queries.
🎥 Watch the Video
I hope this helps new developers get started with QuestDB faster. Kindly consider this for the contributor program and T-shirt if it qualifies 😊
Thanks,
Taniya Katigar
=> feat(docs): Added beginner-friendly video tutorial on setting up QuestDB – by Taniya Katigar

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Close https://github.com/questdb/questdb/issues/6023
=> fix(sql): fix the `SAMPLE BY` fill values alignment issue when column projection is present.

core/pom.xml
- add pulse to example queries button if not visited [#457](https://github.com/questdb/ui/pull/457)
- perform uniqueness check on column names trimmed and case-insensitive [#454](https://github.com/questdb/ui/pull/454)
=> chore(ui): upgrade web console to 1.0.2

benchmarks/pom.xml, compat/pom.xml, core/pom.xml, examples/pom.xml, pom.xml, utils/pom.xml
https://github.com/questdb/questdb/releases/tag/9.0.2
=> build: 9.0.2

core/src/test/java/io/questdb/test/fuzz/FuzzValidateSymbolFilterOperation.java
Fuzz tests use a fault-injector to simulate file system failures.
This means `engine.getTableMetadata(tableToken)`
can throw `io.questdb.cairo.CairoException: [316] could not open read-only [file=/var/folders/71/5myfy97j1pqgbz_z1v70yb2r0000gn/T/junit5538203268730321834/dbRoot/db/testManyTransactions_0~12/_meta]`
This exception causes `FuzzValidateSymbolFilterOperation` to fail and this fails the whole fuzz test. 
This change is making the operation more lenient.
The point of the operation is to validate that when a query execution if successful and returns results, then their results are correct. We don't care about unsuccessful attempts (caused by failure injector)
=> test(sql): fix flaky FuzzValidateSymbolFilterOperation

core/src/main/resources/io/questdb/site/conf/server.conf
Cherry-picks https://github.com/questdb/questdb/pull/6205 to the `master-ent-next` branch.
=> chore(core): added missing replication settings to server.conf
