questdb/questdb

core/src/main/java/io/questdb/griffin/engine/functions/cast/ToLongTimestampFunctionFactory.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/functions/cast/ToLongTimestampFunctionFactoryTest.java
Add web console `to_long` function. Tested with `select to_long(to_timestamp(1262596503400000L)) from long_sequence(1)`
=> Add timestamp to long

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableReaderRecord.java, core/src/main/java/io/questdb/cairo/TableReaderSelectedColumnRecord.java, core/src/main/java/io/questdb/cairo/TableReaderSelectedColumnRecordCursor.java, core/src/main/java/io/questdb/cairo/sql/Record.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/main/java/io/questdb/griffin/engine/functions/SymbolFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolCursorFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/LatestBySubQueryRecordCursorFactory.java, core/src/test/java/io/questdb/cairo/TableReaderTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java, core/src/test/java/io/questdb/griffin/engine/functions/SymbolFunctionTest.java, core/src/test/java/io/questdb/mp/SOUnboundedCountDownLatchTest.java
- WhereClauseParser parser was not cleared, which caused unwanted "where" clause being applied at a wrong level. Fixed #214 
- removed branching from TableReaderRecord to improve read performance
- hardened convention that Symbol function and field do not implement getStr() interface
- fixed sub-query based filters to deal with both String and Symbol columns in a systemic way
=> fix(griffin): few SQL fixes detailed below

.circleci/config.yml, .gitignore, CONTRIBUTING.md, README.md, core/pom.xml, ui/README.md, ui/webpack.config.js
This commit also adds a new `maven` profile to keep the possibility of running
`maven` tasks without having to install `Node.js` locally`.
Documentation changes:
1. README.md
- Update requirements
- Simplify "Building & Running"
- Fix typos
2. CONTRIBUTING.md
- Update repository overview
- Update artificats creation
- Add section for Local frontend development
- Add FAQ
- Update requirements
- Fix typos
3. ui/README.md
- Coordinate changes on requirements with the rest of the documentation
Notes:
Thanks to @patrickSpaceSurfer for his work on `pom.xml`, he wrote the new `install-local-nodejs` profile (the commit is now squashed).
=> chore(maven): use system version of nodejs/npm to fix the build on FreeBSD

core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessor.java, core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java, core/src/main/java/io/questdb/cutlass/text/TextLoader.java, core/src/main/java/io/questdb/cutlass/text/TextMetadataParser.java, core/src/main/java/io/questdb/cutlass/text/types/TimestampAdapter.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/text/TextLoaderTest.java
Allow specifying partition type and their indexes from the `/imp` rest endpoint via query string parameters `partitionBy={DAY,MONTH,YEAR,NONE}` and `timestamp=columnName`.
Example command:
```sh
curl -i -F schema='[{"name": "date", "type": "TIMESTAMP", "pattern": "yyyy-MM-dd"}]' -F data=@agg1d.csv 'http://localhost:9000/imp?name=agg1d&partitionBy=YEAR&timestamp=date&overwrite=true'
```
=> feat(imports): add partitionBy and timestampIndex

core/Dockerfile-linux, core/Dockerfile-linux-arm64, core/Dockerfile-windows, core/README.md
A typo? The correct server port is 8812.
I will fix this in questdb.io as well, once this is approved.
=> Fix PSQL port in docker container and documentation (8892 -> 8812).

ui/src/js/console/index.js
Before:
``` shell
= du -h dist
19M     dist
```
After:
``` shell
= du -h dist
4.8M    dist
```
=> fix(console): remove webpack-resolver to fix regression when bundling the app

core/src/main/java/io/questdb/griffin/engine/functions/math/AbsDoubleFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/AbsIntFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/AbsShortFunctionFactory.java, core/src/main/java/module-info.java, core/src/test/java/io/questdb/griffin/engine/functions/math/AbsDoubleFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/AbsIntFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/AbsLongFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/AbsShortFunctionFactoryTest.java, core/src/test/resources/META-INF/services/io.questdb.griffin.FunctionFactory
Adding support for `abs(double)`.
Replacing branching `value < 0 ? -value : value` by `Math.abs(value)` intrinsic.
=> abs(double) implementation + unbranching

ui/src/components/PopperHover/index.tsx, ui/src/scenes/Schema/Row/index.tsx
This PR fixes the sizing issues with the 'i' icon in the table view. This was
caused by inadequate "height, width: 100%" CSS. In this commit we also simplify
the PopperHover component and remove unnecessary divs.
=> fix(console): simplify DOM structure and CSS for 'i' icon in order to prevent sizing issues

ui/prettier.config.js
By default prettier (through ESLint) checks that the line ending is "lf". By
default, Git on Windows converts line endings on checkout to "crlf". This causes
many warnings since Prettier will see this as incorrect.
This change sets the check to `auto`.
=> fix(console): disable warning for end of line check

README.md
=> fix(readme): prevent logo from being squeezed on mobile devices

README.md, ui/src/components/Tooltip/index.tsx, ui/src/scenes/Editor/index.tsx, ui/src/scenes/Footer/index.tsx, ui/src/scenes/Sidebar/index.tsx
Modify the tooltip content for the Import tab when running in read-only mode:
The button is also disabled.
=> feat(console): disable "Import" section when readOnly mode is on

core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampSequenceFunctionFactory.java, core/src/main/java/io/questdb/std/StationaryMicrosClock.java, core/src/test/java/io/questdb/griffin/FunctionParserTest.java, core/src/test/java/io/questdb/griffin/InsertTest.java, core/src/test/java/io/questdb/griffin/engine/functions/date/TimestampSequenceFunctionFactoryTest.java, core/src/test/java/io/questdb/test/tools/StationaryMicrosClock.java
To summarise, this is what it's fixed on  the PR:
1. insert as select without nominating timestamp
2. timestamp_sequence can take systimestamp()
3. invalid argument(s) for function is not longer reported as unknown function
=> fix(griffin) - insert as select without nominating timestamp - fixed #364 #349

ui/src/scenes/Editor/Ace/index.tsx, ui/src/scenes/Editor/Loader/index.tsx
This fixes a regression introduced in last commit.
The Loader was also improved and will only show after a certain amount of time,
this prevent flickering.
=> fix(console): update z-index on Loader bar to prevent the Menu bar for overlapping it

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/griffin/AsOfJoinTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
where clause failed to properly move inside of sub-query and was discarded, leading to incorrect SQL output. Query like this wasn't working:
```sql
(select a.seq hi, b.seq lo from test a lt join test b) where hi > lo + 1;
```
=> fix(griffin): where clause outside of join sub-query was discarded

ui/src/scenes/Editor/Ace/index.tsx
This fixes quite a big issue discovered by @TheTanc, currently error message look like:
This remove the overflow truncation and the full message is now displayed:
=> fix(console): do not truncate error messages in toast notification

ui/package-lock.json, ui/package.json, ui/src/components/Splitter/index.tsx, ui/src/scenes/Editor/Ace/index.tsx
We also use the ResizeObserver ponyfill for older versions of FF.
=> fix(console): add extra checks on TouchEvent to prevent issues on Firefox (fixes #410)

ui/src/components/Button/index.tsx, ui/src/components/Hooks/useTransition.ts, ui/src/components/PopperHover/index.tsx, ui/src/components/PopperToggle/index.tsx, ui/src/components/ToggleButton/index.tsx, ui/src/index.tsx, ui/src/scenes/Schema/index.tsx, ui/src/store/Console/reducers.ts, ui/src/store/Console/types.ts
=> fix(console): use pointer-events to prevent Chrome from triggering wrong events on mouseleave for tooltips (PopperHover)

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/griffin/AlterTableAddColumnTest.java, core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
similar logic to the one used when renaming columns
=> fix(griffin) - prevent invalid characters in column name when creating table or adding column. Fixed #412

ui/src/js/console/index.js
The rationale for doing this was to prevent macOS users from going back when scrolling the grid horizontally. This PR removes this for now, in the future, we will implement a better solution that does not mess with the History API.
=> fix(console): do not prevent the browser from using the history API

ui/src/scenes/Editor/Menu/index.tsx, ui/src/scenes/Editor/QueryPicker/Row/index.tsx, ui/src/store/Console/types.ts
The QueryPicker button "Example Queries" is now properly aligned (center).
The Rows in QueryPicker aligns text vertically, without an offset for the code.
When there no name for a query, we also remove its margin to avoid adding
unnecessary gaps.
=> fix(console): improve query picker styles

core/src/main/java/io/questdb/ServerMain.java
This also fixes one of the issues detailed in #457.
=> fix(server): always copy conf/date.formats when not present, fix regression introduced in #445

core/Dockerfile-linux, core/Dockerfile-windows
The Docker base CMD was missing `--add-exports` which is causing issues at
runtime (cf. #475).
=> fix(docker): add --add-exports flag to Docker base command - fixes #475

benchmarks/pom.xml
JMH annotation processor was not picked up automatically. Added it explicitly. Tested on IDE as well as terminal, working as expected.
=> Error while running JMH benchmark #503

core/pom.xml, core/src/main/java/io/questdb/griffin/OperatorExpression.java
Also removed duplicate operator expression.
=> fix(griffin): maven test runner (surefire) was picking up default encoding and thus failing tests

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/griffin/DropTableTest.java
do not drop table unless trailing tokens are as expected
=> fix(griffin): drop table fix. Fixed #559

core/src/main/bin/questdb.sh
following reported issue with Java 11 on OSX producing error:
```
JAVA: /Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home/bin/java
Invalid -Xlog option '-Xlog:gc*,gc+ref=debug,gc+heap=debug,gc+age=trace:file=var/"questdb"/log/questdb-%p-%t.gc:tags,uptime,time,level', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
=> fix: removed GC logging

core/src/main/assembly/binaries.xml
=> fix: fixed name of directory inside of 'no-jre' archive to match name of the archive

artifacts/README.md, artifacts/amazonlinux/Dockerfile, artifacts/amazonlinux/run
This will be done by CI soon, in the meantime, it is possible to manually trigger the build using this Dockerfile/sh script.
=> chore: add amazonlinux instructions + sh script to produce QuestDB's binary

.circleci/config.yml, CONTRIBUTING.md, README.md, benchmarks/pom.xml, core/Dockerfile-linux, core/Dockerfile-windows, core/pom.xml, core/src/main/java/io/questdb/std/Long256HashSet.java
- building binaries from maven profile
- building web console (nodejs) from maven profile
- removed profile activation elements; profiles must now be included on `mvn` command using `-P profile1,profile2`
- added profile for FreeBSD
- `mvn clean` will remove public.zip. If someone wants to build JAR without web console, they can do that without worrying that build might pick up residual artifact
- web console builds in the correct order with respect to packaging the JAR
- added Maven Central deployment configuration. The remaining artifacts are username, password and PGP key
- updated README and CONTRIBUTING documents to reflect the above changes and move them into Java 11 reality
=> chore: maven build refactoring

artifacts/amazonlinux/Dockerfile, artifacts/amazonlinux/run
The Dockerfile for Amazon Linux 2 was relying on the old maven syntax, this is now fixed.
=> chore(build): update AmazonLinux2 Dockerfile to new syntax + add missing node

ci/test-pipeline.yml
This will make compilation errors more obvious to the users.
=> chore(ci): add dedicated, separated task for compiling with Maven

core/src/main/java/io/questdb/DefaultServerConfiguration.java, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cutlass/http/DefaultHttpContextConfiguration.java, core/src/main/java/io/questdb/cutlass/http/DefaultHttpServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/HttpContextConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpMinServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpResponseSink.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/HttpServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/processors/HealthCheckProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/StaticContentProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpServer.java, core/src/main/java/io/questdb/cutlass/line/udp/LineProtoReceiver.java, core/src/main/java/io/questdb/cutlass/line/udp/LinuxMMLineProtoReceiver.java, core/src/main/java/io/questdb/cutlass/pgwire/PGWireServer.java, core/src/main/java/io/questdb/griffin/DefaultSqlInterruptorConfiguration.java, core/src/main/java/io/questdb/griffin/HttpSqlExecutionInterruptor.java, core/src/main/java/io/questdb/griffin/SqlInterruptorConfiguration.java, core/src/main/resources/qlog.conf, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
- Refactored server-main to use list of objects that need to be released instead of having them as individual class members.
- Introduced min http server running on port 9003 are returning HTTP 200 to every request.
- I had to refactor configuration quite a lot so that min http server can be nicely configured
- I spotted that "interruptor" was part of HttpContext, which we have one instance per connection. This is excessive and I decided to move "interruptor" inside JsonProcessor and TextProcessor, which we have one instance per thread rather than connection. This also improved usage locality.
=> feat(http): min http server for health monitoring

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/EntryUnavailableException.java, core/src/main/java/io/questdb/cairo/pool/ReaderPool.java, core/src/main/java/io/questdb/cairo/pool/WriterPool.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessor.java, core/src/test/java/io/questdb/cairo/pool/ReaderPoolTest.java, core/src/test/java/io/questdb/cairo/pool/WriterPoolTest.java, core/src/test/java/io/questdb/cutlass/http/RetryIODispatcherTest.java
Throw EntryUnavailableException so that the operation to be retried, similarly as writing is retried.
Move EntryUnavailableException up on cairo package level.
=> When table lock not successful wait instead of failing the request

core/src/main/java/io/questdb/std/DirectLongList.java, core/src/main/java/io/questdb/std/IntList.java, core/src/test/java/io/questdb/std/IntListTest.java
When the `binarySearch` function reaches a range smaller than 65 elements, the function `scanSearch` is called to scan sequentially the elements which is fast than continuing the binary search.
But the scanSearch doesn't take in account the current range considered `[low, high[` and completely scan the list which defeats the purpose of the binary search algorithm.
=> fix(std/IntList): avoid a complete scan of the list in the binarySearch

ci/snapshot-pipeline.yml
This PR changes the mirror where maven is hosted to a non broken and https one. I
also created new env vars to separate dependency versions to the pipeline itself.
=> chore(ci): change broken maven mirror + improve vars

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/griffin/SimulatedDeleteTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
=> fix(griffin): where clause is not moved inside nested query if the query has limit

README.md
Update the TSBS link to point to the blog announcement describing the changes
=> chore: typo blog publish date

core/Dockerfile-linux, core/Dockerfile-linux-arm64, core/pom.xml, core/src/main/java/io/questdb/log/LogFactory.java, ui/package-lock.json
The database volume can be taken outside of docker container:
```
mkdir tmp && cd tmp
docker run -v "$(pwd):/root/.questdb/" questdb/questdb
```
This would create all the directory infrastructure inside the `pwd`
To override default logger configuration create:
```
vi conf/log.conf
```
and paste this as a starting point:
```
writers=file,stdout,http.min
#w.file.class=io.questdb.log.LogFileWriter
#w.file.location=log/questdb.log
#w.file.level=INFO
w.stdout.class=io.questdb.log.LogConsoleWriter
w.stdout.level=INFO
w.http.min.class=io.questdb.log.LogConsoleWriter
w.http.min.level=ERROR
w.http.min.scope=http-min-server
```
=> fix(log): enable logger configuration for docker container

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/main/java/io/questdb/griffin/OperatorExpression.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseAndIntFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseAndLongFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseNotIntFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseNotLongFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseOrIntFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseOrLongFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseXorIntFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/BitwiseXorLongFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/BitwiseTest.java, core/src/test/java/io/questdb/griffin/ExpressionParserTest.java, core/src/test/java/io/questdb/griffin/PowerTest.java
=> feat(sql): bitwise ops implementation

core/src/main/java/io/questdb/griffin/engine/functions/date/OffsetTimestampFunctionFromOffset.java, core/src/main/java/io/questdb/griffin/engine/functions/date/OffsetTimestampFunctionFromRules.java, core/src/main/java/io/questdb/griffin/engine/functions/date/ToTimezoneTimestampFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/date/ToUTCTimestampFunctionFactory.java, core/src/main/java/io/questdb/std/datetime/DateLocale.java, core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/functions/date/ToTimezoneTimestampFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/date/ToUTCTimestampFunctionFactoryTest.java, core/src/test/java/io/questdb/std/datetime/microtime/TimestampsTest.java
List of supported time zone names is the same as by Java itself, we use the same database:
https://code2care.org/pages/java-timezone-list-utc-gmt-offset
=> feat(sql): to_timezone() and to_utc() timestamp functions

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TypeOfFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/NegByteFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/NegFloatFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/NegLongFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/NegShortFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/functions/catalogue/TypeOfFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/math/NegFunctionFactoryTest.java
=> feat(sql): unary '-' (negation) implementation for all numeric types

README.md, i18n/README.zh-cn.md
This PR removes the Translations section and adds a language switcher to the top of the README
=> docs: minor edit to translation links

core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/griffin/WhereClauseParserTest.java
In environments where the QuestDb classes are not loaded by the system
class loader and no context class loader is explicitly set, functions
will not be found when initializing a ServiceLoader without passing
a class loader expicitly.
This change will always work assuming that SQL functions are loadable
from the same class loader as FunctionFactory, that is, there is no support
for plugging in external functions by passing a class loader capable of loading
those classes. I think that assumption is true for QuestDb as I can't find
any mention of class loaders in the QuestDb doc, and it would be challenging to
make this work because the external class loader would also need to correctly
load the functions bundled with QuestDb.
This fixes https://github.com/questdb/questdb/issues/1168
=> Initialize ServiceLoaders from the FunctionFactory class loader

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/griffin/O3CommitLagTest.java
=> fix(cairo): row count wrong when partition starts in lag

core/src/main/bin/questdb.sh
As requested in #1264 , a pull request to add FreeBSD support to `questdb.sh`. Ended up merging Darwin and FreeBSD cases, as foreshadowed, simplifying the Darwin case in the process.
=> Added FreeBSD support, fixing issue #1264

core/src/main/java/io/questdb/cairo/GeoHashes.java, core/src/main/java/io/questdb/griffin/engine/functions/constants/GeoHashConstant.java, core/src/main/java/io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndGeoHashFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/functions/geohash/GeoHashFromCoordinatesFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/geohash/GeoHashQueryTest.java
=> Add make_geohash function

core/src/main/java/io/questdb/cutlass/line/CairoLineProtoParserSupport.java, core/src/main/java/io/questdb/cutlass/line/udp/CairoLineProtoParser.java, core/src/test/java/io/questdb/cutlass/line/CairoLineProtoParserSupportTest.java, core/src/test/java/io/questdb/cutlass/line/udp/CairoLineProtoParserTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertOtherTypesTest.java
Reviewed and added clarifications on the way it is implemented at present, and then fixed some corner cases.
=> review ILP/UDP value parser and fix corner cases

ui/src/scenes/Editor/Ace/questdbMode.ts
This PR adds support for syntax highlighting of geohash literals:
* `#ezzn5kxb`
* `##11011101010111001010010001010`
=> feat(ui): basic syntax highlighting for geohashes in web console

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/std/Files.java, core/src/main/java/io/questdb/std/str/NativeLPSZ.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/griffin/SqlCompilerTest.java, core/src/test/java/io/questdb/griffin/TableBackupTest.java
To start QuestDB you give it the root folder through parameter `-d /some/path/root`. This folder will end up having the following structure (`ls /some/path/root`):
1. **conf**, contains QuestDB's configuration files: server.conf, log-file.conf, date.formats, mime.types
2. **db**, contains one folder per table and the `_tab_index.d` (contains a number which is used to assign tables a unique id on creation).
3. **public**, contains the console (localhost:9000). This folder and contents are recreated by QuestDB on start (and you have to put them there yourself if you run from the IDE instead of from a release).
4. **log**, contains the logs of the running instance.
This "command" takes the current state of QuestDB, i.e. its configuration and all of its tables, with the data as it is at the …
=> feat(sql): include conf files and tab index in backups

core/src/main/java/io/questdb/cairo/GeoHashes.java, core/src/test/java/io/questdb/cairo/GeoHashesTest.java
We create a buffer to hold "123" and then attempt to parse a geohash
7 chars in len. We have control over the first 3 chars, which parse
well, then the next 4 are random bytes which are unlikely to parse as
valid geohash chars in base 32.
=> chore(sql): fix geohash flapping test

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpServerTest.java
When an ILP row which adds a new column is a first Out Of Order row the timestamp of the result rows can be wrong when data is committed
=> fix(cairo): fix wrong timestamp when first o3 row cancelled

core/src/main/c/share/vcl/vectori512s.h
=> chore: fix typo in vectori512s.h

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/cutlass/line/CairoLineProtoParserSupport.java, core/src/main/java/io/questdb/cutlass/line/LineProtoLexer.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/NewLineProtoParser.java, core/src/main/java/io/questdb/cutlass/line/udp/AbstractLineProtoReceiver.java, core/src/main/java/io/questdb/cutlass/line/udp/CairoLineProtoParser.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/cutlass/line/CairoLineProtoParserSupportTest.java, core/src/test/java/io/questdb/cutlass/line/LineProtoLexerTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContextTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpInsertByteGeoHashTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpInsertOtherTypesTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/NewLineProtocolParserLexerTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/NewLineProtocolParserTest.java, core/src/test/java/io/questdb/cutlass/line/udp/CairoLineProtoParserTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertByteGeoHashTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertGeoHashTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertIntGeoHashTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertLongGeoHashTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertOtherTypesTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertShortGeoHashTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertTest.java
ILP (influx line protocol) messages can be sent through TCP and UDP, both paths should result in an equivalent parse of the content.
`<table_name>(,<sym>=<S>)* <field>=<V>(,<field>=<V>)* <timestamp_nano><eol>`
- table_name: name of the table to insert into, if it does not exist it will be created.
- sym/field: name of a symbol and a field respectively. 
- S: value of the symbol. It will look like a string, but without quotes around it. Strings are not tolerated, nor any other type.
- V: value of the field, which can be absent/empty, to signify null.
- timestamp_nano: a long, `not 'i'` terminated, representing the epoch UTC in nanosecond precision (unlike field value's whose precision is in millisecond and must end in 'i').
- eol: '\n'.
When **V**s arrive, we need to guess their type by …
=> feat(ilp): fix various edge cases, behaviour of type parsers tcp/udp is closer, allow empty field value as null, support other types

benchmarks/src/main/java/org/questdb/LineTCPSenderMain.java, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/AbstractIndexReader.java, core/src/main/java/io/questdb/cairo/BitmapIndexWriter.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/SymbolColumnIndexer.java, core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java, core/src/main/java/io/questdb/cairo/SymbolMapWriter.java, core/src/main/java/io/questdb/cairo/TableBlockWriter.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java, core/src/main/java/io/questdb/cairo/vm/api/MemoryM.java, core/src/main/java/io/questdb/cutlass/line/tcp/SymbolCache.java, core/src/main/java/io/questdb/std/Files.java, core/src/main/java/io/questdb/std/MemoryTag.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cairo/BitmapIndexTest.java, core/src/test/java/io/questdb/cairo/CairoMemoryTest.java, core/src/test/java/io/questdb/cairo/FullFwdDataFrameCursorTest.java, core/src/test/java/io/questdb/cairo/TableWriterTest.java, core/src/test/java/io/questdb/cairo/vm/ContinuousMemoryMTest.java, core/src/test/java/io/questdb/cutlass/http/RetryIODispatcherTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/SymbolCacheTest.java, core/src/test/resources/server.conf
This change introduces fine-grained controls for overallocation when ingesting data. These are configuration options:
- Memory page size per column for O3 operations. Please be aware O3 will use 2x of this RAM per column
```
cairo.o3.column.memory.size=16M
```
- mmap sliding page size that TableWriter uses to append data for each column
```
cairo.writer.data.append.page.size=16M
```
- mmap page size for mapping small files, such as _txn, _todo and _meta. The default value is OS page size (4k Linux, 64K windows, 16k OSX M1). If you override this value it will be rounded to the nearest (greater) multiple of OS page size
```
cairo.writer.misc.append.page.size=4k
```
- mmap page size for appending index key data; key data is number of distinct symbol values times 4 bytes
``` …
```
=> chore(o3): make column memory size configurable

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/cutlass/line/CairoLineProtoParserSupport.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/NewLineProtoParser.java, core/src/main/java/io/questdb/cutlass/line/udp/CairoLineProtoParser.java, core/src/test/java/io/questdb/cutlass/line/CairoLineProtoParserSupportTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpInsertOtherTypesTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpServerTest.java, core/src/test/java/io/questdb/cutlass/line/udp/CairoLineProtoParserTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpInsertOtherTypesTest.java
Refs: #1257
Documentation PR: https://github.com/questdb/questdb.io/pull/554
Extends ILP to support timestamp field type. Timestamp field values are determined based on the `t` suffix similar to how it's done with `i` suffix for long values.
The previous (undocumented) behavior was to interpret values like `1465839830100399000t` of symbol type in case of UDP and of boolean type (true) in TCP. Hence, this change should not be considered as a breaking change (although, marking it as a breaking change won't hurt).
=> feat(ilp): support timestamp fields

pom.xml, utils/README.md, utils/pom.xml, utils/src/main/java/io/questdb/cliutil/TxFileStruct.java, utils/src/main/java/io/questdb/cliutil/TxSerializer.java, utils/src/test/java/io/questdb/cliutil/TxSerializerTest.java
Serializes binary `_txn` file to / from readable JSON format. Primary usage to investigate storage issues
Usage 
```
io.questdb.cliutil.TxSerializer -d <json_path> | -s <json_path> <txn_path> 
```
- `-d` option prints contents of `_txn` file to std output in JSON format
- `-s` option transforms existing JSON file into binary _txn format
=> chore: added command line utils project with TxSerializer

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/mig/EngineMigration.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpMemoryUsageFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpThreadStacksFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/engine/functions/catalogue/DumpMemoryUsageTest.java, core/src/test/java/io/questdb/griffin/engine/functions/catalogue/DumpThreadStacksTest.java
Added function to help user-side diagnostics. When HTTP server is responsive but we suspect high CPU utilization from one or more of our threads use the following to dump thread stacks to log:
```sql
select dump_thread_stacks
```
Sample output is:
```
2021-10-06T12:03:01.216001Z A dump-thread-stacks 
'main': RUNNABLE
at java.management@11.0.8/sun.management.ThreadImpl.getThreadInfo1(Native Method)
at java.management@11.0.8/sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:190)
at app/io.questdb/io.questdb.griffin.engine.functions.catalogue.DumpThreadStacksFunctionFactory$DumpThreadStacksFunction.getBool(DumpThreadStacksFunctionFactory.java:66)
at app/io.questdb/io.questdb.cairo.sql.VirtualRecord.getBool(VirtualRecord.java:59)
at …
```
=> feat(sql): dump thread stacks function + changes output of dump memory usage function + added more logging

core/src/main/java/io/questdb/MessageBusImpl.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/log/LogFactory.java, core/src/main/java/io/questdb/log/LogRecordSink.java, core/src/main/java/io/questdb/mp/RingQueue.java, core/src/main/java/io/questdb/std/DirectObjectFactory.java, core/src/main/java/io/questdb/tasks/TableWriterTask.java, core/src/test/java/io/questdb/log/LogFactoryTest.java
This is something I wanted to do for a while, technical debt if you will. Often we have RingQueues with messages that are really a piece of memory. We use to allocate each message individually, which is wasteful. The new API offers to allocate and manage single memory address, which is then distributed to individual queue slot.
N.B. ignore the commit message, I accidentally reused from a previous commit
=> feat(core): introduced new Direct ring queue API

ci/templates/steps.yml
This is where Azure saves coverage report, not root folder
=> chore(ci): restore coverage file path to be in core/

benchmarks/src/main/java/org/questdb/StrPosBenchmark.java, core/src/main/java/io/questdb/griffin/engine/functions/str/StrPosCharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/StrPosFunctionFactory.java, core/src/test/java/io/questdb/griffin/engine/functions/str/StrPosFunctionFactoryTest.java
A follow-up for #1506
Includes the following:
* Introduces const variations for strpos functions since it's going to be a popular case for users
* Adds missing checks for zero char into `StrPosCharFunctionFactory`
* Adds tests to cover new code
* Updates the strpos benchmark
Results on my local (Ubuntu 20.04, OpenJDK 11.0.11):
```
Benchmark                              Mode  Cnt    Score     Error  Units
StrPosBenchmark.testBaseline           avgt    3   11.539 ±   0.596  ns/op
StrPosBenchmark.testCharConstOverload  avgt    3  504.146 ± 230.001  ns/op
StrPosBenchmark.testCharOverload       avgt    3  509.196 ±  62.726  ns/op
StrPosBenchmark.testStrConstOverload   avgt    3  567.364 ±  60.399  ns/op
StrPosBenchmark.testStrOverload        avgt    3  540.781 ±  75.134  ns/op
```
P.S. The …
=> chore(sql): improve strpos function

core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/std/Files.java, core/src/main/java/io/questdb/std/FilesFacade.java, core/src/test/java/io/questdb/griffin/O3CommitLagTest.java, core/src/test/java/io/questdb/griffin/O3Test.java
Fixes #1521
Linux (and probably other POSIX-compliant systems) requires mmap's offset to be page size aligned. Under certain conditions O3 writes led to unmapped pages being open with unaligned offset value.
=> fix(cairo): fix mmap offset page alignment in o3

ui/src/scenes/Editor/Ace/index.tsx, ui/src/scenes/Editor/Ace/utils.ts, ui/src/scenes/Editor/Menu/index.tsx, ui/src/store/Query/actions.ts, ui/src/store/Query/reducers.ts, ui/src/store/Query/selectors.ts, ui/src/store/Query/types.ts
I'm new to the project, so any suggestion would be appreciated. In case of complex discussions, I guess it would be better to chat on Slack.
This PR is a first approach to https://github.com/questdb/questdb/issues/1482. Looking at the code I found two approaches:
- `grid.js` having the responsibility of the last executed query (DISCARDED)
 The idea was to include a `lastQuery` parameter similar to the current `query` variable, which stores the last executed query.  However, this is discarded because the process of running the actual query happens in the editor.
- Editor storing the last executed query (IMPLEMENTED)
 In this approach, `grid.js` simply executes whatever query is passed and the responsibility is only on the editor side.
  
   Both running a new query and refreshing the …
=> Make refresh button execute correct query

ui/src/scenes/Editor/Ace/index.tsx
Fix `F9` and `CMD`+`Enter` shortcuts that are broken due to typos.
=> chore(ui): fix keyboard shortcuts

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/EmbeddedApiTest.java
Fixes #1575
**Important note**. Obviously, in the original scenario readers may face `table does not exist` SqlException in case when a writer didn't create the table yet. This is the expected behavior and this fix does not change it.
=> fix(cairo): fix table locked on concurrent reads and create table

core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverTest.java, core/src/test/java/io/questdb/griffin/AlterTableAddColumnTest.java
- space should be escaped in field / tag name in ILP
- column name should be double quoted in SQL
=> chore: allow column names with spaces

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/test/java/io/questdb/griffin/InsertTest.java, core/src/test/java/io/questdb/griffin/SimpleTableTest.java
When statement is parsed it is expected that complete part `with time zone` should be
skipped.
=> fix(sql) Column alias 'time' does not work

ui/src/js/console/grid.js, ui/src/styles/_grid.scss
Adds a column type indication to results grid, aligned with the overall positioning (left/right) of header text.
This slightly changes the column width calculation, because we have to make sure the type is always visible even in a dense layout (a lot of columns).
=> feat(ui): add column type to grid

benchmarks/src/main/java/org/questdb/LineTCPSenderMain.java, benchmarks/src/main/java/org/questdb/RawTCPILPSenderMain.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java, core/src/main/java/io/questdb/std/str/DirectByteCharSequence.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContextTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpParser2Test.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpParserTest.java
Fixes #1595
We do not sanitize table name, which originates from ILP. The following is not disallowed:
```
../../tab,tag=val
```
```
\0\0\0tab,tag=val
```
```
\0\0\0,tag=val
```
etc...
Additionally disallowing the following characters in table names and columns: `\`,`/`,`.` and `\0`
=> fix(ilp): sanitize table name to avoid FS corruption

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/griffin/AlterTableAddColumnTest.java
Should fix #1612 . 
I think this type of error can happen for other types of statements due to how sql is parsed and because sql is usually tested without ';' at end of statement .
=> fix: fix ALTER TABLE ADD COLUMN parse error #1612

core/src/main/java/io/questdb/cairo/vm/MemoryPARWImpl.java, core/src/main/java/io/questdb/cairo/vm/api/MemoryR.java, core/src/main/java/io/questdb/std/DirectLongList.java, core/src/main/java/io/questdb/std/Hash.java, core/src/test/java/io/questdb/HashTest.java, core/src/test/java/io/questdb/cairo/map/CompactMapTest.java, core/src/test/java/io/questdb/cairo/map/FastMapTest.java, core/src/test/java/io/questdb/std/DirectLongListTest.java
Fixes #1635
Run time of new `testCollisionPerformanceStringKeys` before the change - 7mins, after 2 secs
=> fix(sql): tweak hash function to speed up FastMap

core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpParser2Test.java
According to the code of `parseMeasurement` method original message should be printed alongside with error, but because of a few mistakes in the code, it never happens.  
IMHO that is a good idea to print the original message aside, so I fixed the given issue.
=> Original message was skipped in LineTcpParser2Test during error

core/pom.xml
Bump NodeJS to [12 LTS](https://nodejs.org/download/release/latest-v12.x/).
=> chore: bump nodejs version to lts

ci/cbinary-pipeline.yml
fix Azure pipeline which builds binaries to run Make after CMake on all the platform
=> chore(ci): fix binary pipeline to run make on all platforms

core/src/main/c/share/vcl/instrset.h
=> chore: fix typo in instrset.h

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/pool/WriterPool.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/cairo/pool/WriterPoolTest.java, core/src/test/java/io/questdb/griffin/AlterSystemLockUnlockWriterTest.java
We seems to set incorrect reason when writer is otherwise not locked
```
2021-12-11T13:49:48.3931700Z testWriterRelease4(io.questdb.cutlass.line.tcp.LineTcpReceiverTest)  Time elapsed: 0.284 sec  <<< ERROR!
2021-12-11T13:49:48.4033190Z io.questdb.cairo.CairoException: [2] Could not lock 'weather' [reason='not owned by anyone']
2021-12-11T13:49:48.4133950Z 
```
=> fix(core): fixed flapping test 'testWriterRelease4'

core/src/main/java/io/questdb/cairo/pool/WriterPool.java, core/src/main/java/io/questdb/cutlass/line/udp/LineUdpParserImpl.java, core/src/test/java/io/questdb/cairo/pool/WriterPoolTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AlterTableLineTcpReceiverTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverTest.java
another attempt to fix test, same as https://github.com/questdb/questdb/pull/1670
The rationale for this PR was that all of our existing PRs were failing for reasons unrelated to the PR. We have a lot of flapping tests.
Following the async alter table PR the writer maintenance job was introduced in the TcpILP tests:
- testWriterRelease* tests were intermittently disrupted by maintenance job expiring writers (10s idle timeout)
- removal of maintenance job from thread pool upset some of the `alter table` tests
- both tests use the same test code, so I made using writer maintenance job optional per test
- tests were failing with message "cannot lock table, reason `unlocking`". This made no sense. I refactored use of lock reason
- refactoring lock reason perhaps saved us some yet unreported …
=> fix(core): fixed numerous flapping tests

core/src/main/java/io/questdb/log/HttpLogRecordSink.java, core/src/main/java/io/questdb/log/LogAlertSocket.java, core/src/main/java/io/questdb/log/LogRecordSink.java, core/src/main/java/io/questdb/log/TemplateParser.java, core/src/test/java/io/questdb/log/HttpLogRecordSinkTest.java, core/src/test/java/io/questdb/log/LogRecordSinkTest.java, core/src/test/java/io/questdb/log/TemplateParserTest.java
Revisit sink so that by default the put method is ascii, and there are additional means of putting utf8 text.
=> fix(log): fix the way alert appender deals with template encoding

benchmarks/src/main/java/org/questdb/RawTCPILPSenderMain.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableStructureAdapter.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContextTest.java
Fixes #1661
Apologies, IntelliJ reformatted test file. The only change there is added test `testNewTableNullType`
=> fix(ilp): reject `null` fields when table does not exist

core/src/main/java/io/questdb/log/LogAlertSocket.java, core/src/main/java/io/questdb/log/LogAlertSocketWriter.java, core/src/test/java/io/questdb/log/LogAlertSocketTest.java, core/src/test/java/io/questdb/log/LogAlertSocketWriterTest.java, core/src/test/java/io/questdb/log/MockAlertTarget.java
Tests were unnecessarily slow to run. They don't connect anywhere useful but still wait on connect timeout. Before the change:
After this PR:
circled is calendar reload, which happens once for the entire test group, e.g. when running this class together with others the exec time will be in millis
=> chore(test): speeding up tests (and test name adjustment)

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/griffin/InsertTest.java
Aims to make the error reason more obvious to the end user.
=> chore(sql): improve error message for o3 insert on non-partitioned table

core/Dockerfile, core/pom.xml
Next official QuestDB docker image release will use JDK17
=> feat(build): have docker image use jdk17 to build questdb

core/src/main/java/io/questdb/BuildInformationHolder.java, core/src/main/java/io/questdb/log/LogAlertSocketWriter.java, core/src/test/java/io/questdb/log/LogAlertSocketWriterTest.java
Alert manager log test flapping because it reads and questdb version from runtime and asserts against static text.
The fix is to control version information in test so it does not depend on the runtime version.
Test was failing on CI here: https://dev.azure.com/questdb/questdb/_build/results?buildId=4257&view=logs&jobId=bd06cbe1-a964-5048-ec4d-b96ff4693915&j=bd06cbe1-a964-5048-ec4d-b96ff4693915&t=ad06c901-2e90-5184-2bb4-5f8df27de5c6
=> fix(test): flapping log test

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/griffin/O3CommitLagTest.java
fix move uncommitted to use adjusted offset to read variable size length
=> fix(cairo): fix o3 commit corrupts data in var columns

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/table/CompiledFilterRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/DeferredSingleSymbolFilterDataFrameRecordCursorFactory.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/griffin/CompiledFilterTest.java, core/src/test/java/io/questdb/griffin/engine/table/DataFrameRecordCursorFactoryTest.java, core/src/test/resources/server.conf, pkg/ami/marketplace/assets/server.conf
A follow-up to #1592
Limits max size of page frames used in SQL queries. The max page frame size is set to 8M by default. This leads to a maximum of 64MB of RAM allocated for the row id array used in JIT compiled filters.
I also run `SqlJitCompilerBenchmark` on my machine and didn't spot a noticeable difference in the benchmark results with this change.
Also updates descriptions and types for SQL JIT settings.
=> feat(griffin): limit max page frame size

core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/griffin/JoinTest.java, core/src/test/java/io/questdb/griffin/LatestByParallelTest.java, core/src/test/java/io/questdb/griffin/MemoryLeakTest.java, core/src/test/java/io/questdb/griffin/SecurityTest.java, core/src/test/java/io/questdb/griffin/SimulatedDeleteTest.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java, core/src/test/java/io/questdb/griffin/TruncateTest.java, core/src/test/java/io/questdb/griffin/WithClauseTest.java, core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
Refs #1553 - the next step would be to fix all of the ignored tests for latest by that we have in `SqlCodeGeneratorTest`
Adds support for new latest by syntax:
```
select * from tab where x > 0 latest on timestamp partition by y
```
Note that support for the `start at`/`end at` clauses is not included. As suggested in the original GH issue, users should define the timestamp filter in where clause.
Support for the old latest by syntax is kept for backward-compatibility purposes, yet it should be marked as deprecated.
=> chore(sql): new latest by syntax

core/src/main/java/io/questdb/std/SimpleReadWriteLock.java, core/src/test/java/io/questdb/std/SimpleReadWriteLockTest.java
`SimpleReadWriteLock` didn't have tests and, since I wrote them while working on a blog post, it makes sense to add them to upstream.
=> chore(std): add tests for SimpleReadWriteLock

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/pool/ReaderPool.java, core/src/test/java/io/questdb/cutlass/http/ImportIODispatcherTest.java
Fix `txn_scoreboard` leak which eventually leads to all SELECT queries being locked with `max txn-inflight limit reached` error.
Problem happens when `TableReader` is taken from the pool, it re-reads transaction and fails to reload partitions. If failure happens at this point scoreboard is not released and reader is kept locked out of the pool.
Failure to release partition structure is quite likely on busy read/write system because of flaw in O3 purge partition logic which to be fixed separately.
=> fix(cairo): fix reader and txn scoreboard leak

core/src/main/java/io/questdb/cairo/O3PurgeDiscoveryJob.java, core/src/main/java/io/questdb/cairo/O3PurgeJob.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/griffin/O3PartitionPurgeTest.java
Partition purge jobs did not work properly for cases where not every commit is out of order commit. 
This change will only remove a partition if there are no readers with transaction number below next available partition version. 
It also addresses inconsistency that when reader reads transaction 10 it will look at partition folders .9 and not .10
=> fix(cairo): fix o3 partition purge jobs

ui/.prettierignore
It is really getting on my nerves:
- slows down commits
- fails unrelated commits
- fails on third-party libraries in `cmake-`
- rewrites test resources
- fails on auto-generated doc in `core/target`
I'm disabling it for `core` entirely
=> chore: removing "prettier" from "core"

ci/cbinary-pipeline.yml
Windows binary builds with the MinGW tool. 
 It introduces additional runtime dependencies we don't want to deploy.
```
libstdc++-6.dll
libgcc_s_seh-1.dll
libwinpthread-1.dll
```
Currently, `libwinpthread` is unlinked, `libgcc` linked statically. The `libstdc++` cannot be linked statically as it blows up symbols tables. We try to avoid c++ runtime dependency in the source code.  If dependency was accidentally introduced we want to be notified by build pipeline.
This PR introduces a simple check with `objdump` and `grep` tools.
=> chore(ci): check windows binaries for cpp runtime dependency

ui/package-lock.json
This change is mainly to upgrade `follow-redirects` version in
transitive dependencies, to one which has fixed the following
vulnerability:
https://github.com/advisories/GHSA-74fj-2j2h-c42q
QuestDB is not directly related to the vulnerability, because package in
question is only relevant during development (used in `webpack-dev-server`)
=> chore(ui): update package-lock.json

core/src/main/java/io/questdb/std/Os.java, core/src/test/java/io/questdb/std/OsTest.java
While looking at newly flapped test `testAlterTableAddIndexContinuesAfterStartTimeoutExpiredAndTimeout` I released that `Os.sleep(millis)` implementation is buggy.
If this implementation was to be spuriously interrupted, it could finish prematurely (e.g. before specified interval elapses).\
Therefore this fixes the test I mentioned above as well as some other tests perhaps.
=> fix(core): sleep bug

core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/test/java/io/questdb/cairo/TableReaderTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/std/OsTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
Fixed error messages such as:
```
io.questdb.cairo.CairoException: [0] Partition '1970-01-01T00.0' does not exist in table 'w' directory. Run [ALTER TABLE w DROP PARTITION LIST '1970-01-01T00.0'] to repair the table or restore the partition directory.
```
Test class change looks abysmal due to automatic re-formatting. The only real change there is new test `testReaderReloadWhenColumnAddedBeforeTheData`
=> fix(core): fixed incorrect _txn content to be occasionally written to the file

core/src/main/c/share/txn_board.cpp, core/src/main/java/io/questdb/cairo/TxnScoreboard.java, core/src/test/java/io/questdb/cutlass/http/RetryIODispatcherTest.java
Refs: #1559
Fresh table reader instances were using 0 transaction numbers in scoreboard acquire/release calls which led to races in the scoreboard's min value initialization. The init() method in scoreboard was swapping 0 min value with L_MIN and a later table reader was swapping this L_MIN value with its current transaction number. This could have led to min being set to a value greater than 0 while there are some fresh reader instances that haven't released their txn 0 yet. As the result of this race, the assertion in releaseTxn() was failing.
To fix this race, the TxnScoreboard Java class now adds 1 to all received txn values before calling the C++ implementation.
=> fix(cairo): fix scoreboard race for new table readers

core/src/main/java/io/questdb/griffin/engine/functions/date/ToTimestampFunctionFactory.java, core/src/main/java/io/questdb/std/datetime/microtime/TimestampFormatUtils.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
=> fix(sql): support timestamp formats used by python drivers

core/src/main/java/io/questdb/cairo/pool/ReaderPool.java, core/src/test/java/io/questdb/test/tools/TestUtils.java, core/src/test/resources/log-file.conf
Closes #1813
Full disclosure: the error I was able to reproduce was different. It was related to my local logger setup. This setup was rotating log files, interfering with closed file counter in the test.
On my M1 test ran 30 min without failure.
Reduced effort in each test to assert memory leak. Memory tags only evaluated when total usage before and after does not match. I feel instances where exact memory exchange between tags are non-existent.
=> refactor(core): cleaner algo to resolve race condition between pool return and close

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/load/LineData.java
This change includes ILP tags in fuzz testing.
Currently the fuzz test sends only columns to QuestDB.
It also adds quotes around string values.
Previously they were treated as symbols because of the missing quotes.
Current message format used by the test:
```
weather0 location=us-midwestC,terület=europeY,temperature=80.0,humidity=25.0,hőmérséklet=13.0,notes=noteU,ветер=63.0 1465839830102302000
```
New format exercising tags and uses proper string fields:
```
weather0,location=us-midwestC,city=LondonU terület="europeY",temperature=80.0,humidity=25.0,hőmérséklet=13.0,notes="noteU",ветер=63.0 1465839830102302000
```
=> chore(ilp): support tags in fuzz test

core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/DropTableTest.java
Before this change, the statement:
```
drop table mytable
```
would fail, which meant having to do a try/catch in client code.
After this change, we support in addition the statement:
```
drop table if exists mytable
```
which will drop the table if exists, and do nothing when not.
=> feat(sql): New syntax 'drop table if exists table-name' to not fail when the table does not exist

core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/load/LineData.java, core/src/test/java/io/questdb/cutlass/line/tcp/load/TableData.java
Enhancing fuzz test to be able to send space in symbol values.
Spaces in symbol values are making the ILP message malformed and the line should be dropped on the server side.
The test validates that those lines are dropped and the valid lines are ingested.
=> chore(ilp): fuzz test to send space in symbol values

core/src/main/java/io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/SymbolFunctionRowCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/SymbolIndexFilteredRowCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/SymbolIndexRowCursorFactory.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Fixes the following problems for queries with a not equals filter over an indexed symbol column (e.g. `select * from tab where sym != 42`):
* The underlying record cursor factory was filtering out NULL values leading to different behavior than the same filter non-indexed column
* In case of a filter with bind variables, the factory didn't recalculate the included set properly on bind variable values change
* Each query execution led to `ObjList::indexOf` (array scan, O(N) operation) done on each key. Moreover, `CharSequence::toString` done for each symbol value led to some litter. To fix that `ObjList`s containing symbol values were replaced with `IntHashSet`s with symbol keys.
=> fix(sql): fix not equals filter on indexed symbol column

core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/cairo/CreateTableTest.java, core/src/test/java/io/questdb/griffin/AbstractGriffinTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
Fixes "cast(s as symbol index)" by removing index handling from this element so separate index(column_name) should be used.  
Cast with index doesn't create index in master anyway .
=> chore(sql): fixed cast with index parse error

core/src/main/java/io/questdb/cairo/AbstractFullDataFrameCursor.java, core/src/main/java/io/questdb/cairo/AbstractIntervalDataFrameCursor.java, core/src/main/java/io/questdb/cairo/pool/ReaderPool.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java, core/src/test/java/io/questdb/cairo/TableReaderTailRecordCursorTest.java, core/src/test/java/io/questdb/cairo/pool/ReaderPoolTest.java, core/src/test/java/io/questdb/griffin/AlterTableAttachPartitionTest.java
A SQL execution path was using `TableReader` instance _after_ it was returned to pool. This lead to the same instance being used by multiple threads with flurry of random errors and memory corruption.
Additionally I made it an error to return reader instance to pool twice and fixed tests that did just that.
=> fix(core): fixed TableReader double free events

core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinNoKeyRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/HashJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/LtJoinRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/union/UnionAllRecordCursorFactory.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/JoinTest.java
If  `CROSS JOIN` used in PgWire and client disconnects on without receiving full data set then one of the TableReaders is not released. Fix is to ensure that TableReaders are released even when error happens.
=> griffin: release cursors in cross join

core/src/main/java/io/questdb/griffin/engine/functions/bind/BindVariableServiceImpl.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
Fixes the bug mentioned in this comment: https://github.com/questdb/questdb/issues/1359#issuecomment-929566532. Note that this PR only fixes the bug mentioned in the comment, it doesn't actually fix issue #1359 as a whole.
---
When constructing a `Timestamp` object from a precise source of microseconds, the `Timestamp` represents an epoch time that looks something like this: `1632857409651937`. The driver serializes this `Timestamp` like so: `53713-03-11 14:40:51.937+00`. QuestDB is currently able to parse this just fine.
If instead we construct a `Timestamp` object from microseconds that only have millisecond level precision, the `Timestamp` represents an epoch time that looks like: `1632857409651000` (notice the zero digits at the end). The driver skips over serializing the microsecond …
=> fix(sql): fix parsing of timestamps that have 0 micros

core/src/main/assembly/web-console.xml, ui/post-build.js
Fixes #1866
The font file got corrupted during build process, which changed the line
endings of a `.ttf` file. After that the file was not considered valid
by the browser, and font was not rendered as expected.
This PR adds `**/*.ttf` glob to `<exclude>` statement. That way line
endings are not changed, as by default maven assembly plugin uses
`<lineEndings>keep</lineEndings>`
=> fix(UI): fix errors in WebConsole browser console

core/src/main/java/io/questdb/griffin/OrderByMnemonic.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/griffin/DistinctWhitLimitTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
…subqueries with limit clause ; outer query  ordering skipping
Fixes several issues : 
- too agressive order by removal in subqueries (across limit)
- distinct not applying limit in simple queries - https://github.com/questdb/questdb/issues/1854  
- order by getting ignored if LimitedSizeSortedLightRecordCursorFactory comes from nested model, e.g. 
```
select * from 
( select id from test order by id desc limit 10)
order by id asc  <- this one was ignored
```
=> fix(sql): distinct, order by & limit

core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpCommitTest.java
Fix for ILP commit and fuzz tests.
The test needs to detect when tables are created, this relied on checking for table lock events.
This is incorrect because the lock is acquired before the table is created.
Instead we can check for table unlock events.
The very first unlock happens just after the table has been created.
Closes #1891
=> chore(ilp): ilp tcp commit test fix

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
Fixes positional ORDER BY in combination with column aliases. Such
combination was leading to a translating model being used to look
up the ORDER BY columns. Due to their nature, translating models
may not contain the full list of columns, so such queries ended up
with either "order column position is out of range" error or an NPE
in SqlOptimiser#getOrderByAdvice.
=> fix(sql): fix order by aliased column positions

core/src/main/java/io/questdb/mp/SOCountDownLatch.java
Closes https://github.com/questdb/questdb/issues/1883
Original issue states to review as to how to properly prevent possible over flow from long. Nanos should not be added to the System.nanoTime().
The requested change will determine the await by comparing the elapsed time to the allotted deadline. 
**Docs for System.nanoTime():**
--------------------------------------------------------------------------------
For example, to measure how long some code takes to execute:
long startTime = System.nanoTime();   // ... the code being measured ...   long elapsedNanos = System.nanoTime() - startTime;
To compare elapsed time against a timeout, use
if (System.nanoTime() - startTime >= timeoutNanos) ...
instead of
if (System.nanoTime() >= startTime + timeoutNanos) ...
because of the possibility of …
=> Fixed long overflow problem

CONTRIBUTING.md
Squashing commits can be done through github UI, while merging a PR,
thus this requirement is redundant.
Removing this requirement makes contribution a little bit easier, as
less work needs to be done.
=> docs(CONTRIBUTING): remove section about commit squashing

ui/src/scenes/Editor/Monaco/index.tsx, ui/src/scenes/Editor/Monaco/utils.ts, ui/src/utils/fromFetch.ts
This PR updates web console to support `query` and `executeQuery` URL params.
* `query`:
Adding `?query=select * from 'telemetry'` as URL param to the web
console will fill the web console code editor with `select * from 'telemetry'`, for example:
```
http://localhost:9000/?query=select * from 'telemetry'
```
* `executeQuery`:
Adding `?executeQuery=true` will execute query which is
available in the editor, as soon as the web console loads.
To achieve this, the code looks at URL query params, extracts values of
`query` and `executeQuery` and runs the following:
1. for inserting value of `query` in editor, `appendQuery(query)` is
used. An already existing utility function.
2. to run the query, `toggleRun()` is called. The same function is
already used when user clicks `Run` button. …
=> feat(UI): support `query` and `executeQuery` URL params for inserting and executing queries in web console

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cutlass/text/DefaultTextConfiguration.java, core/src/main/java/io/questdb/cutlass/text/types/InputFormatConfiguration.java, core/src/test/java/io/questdb/cutlass/text/types/TypeManagerTest.java
QuestDB doc says that a custom version of text_loader.json can be loaded from the conf directory if the below property is set:
```
cairo.sql.copy.formats.file=text_loader_custom.json
``` 
This did not work.
The PR fixes the issue by falling back to loading the file from the conf dir if it cannot be found as a resource.
Closes #1928
=> fix(cairo): load text_loader.json as a file if cannot be found as a resource

core/src/main/java/io/questdb/griffin/engine/functions/lt/LtLong256FunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/AbstractFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/eq/EqLong256FunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/lt/LtLong256FunctionFactoryTest.java
=> feat(sql): implement comparison operators for long256 type

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java, core/src/main/resources/io/questdb/site/conf/server.conf, pkg/ami/marketplace/assets/server.conf
Also removes redundant close() method in LineTcpParser and fixes formatting.
=> chore(conf): add default values for ILP props

core/src/main/java/io/questdb/DefaultTelemetryConfiguration.java, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/TelemetryConfiguration.java, core/src/main/java/io/questdb/TelemetryJob.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableMetadataCursorFactory.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/griffin/HideTelemetryTablesTest.java
Closes #1948
Configuration property can make telemetry tables visible:
```
telemetry.hide.tables=false
```
Changes in `TelemetryJob` class are 99% automated formatting. Functional changes were to make telemetry table name constants `public` vs `private` as before.
=> feat(sql): hide telemetry table from `tables()` SQL output

ui/src/scenes/Editor/Menu/index.tsx
Added a button to navigate to Web Console docs. 
In the future this can also trigger an in-app help center, similar to other applications.
=> chore(ui): add help button in web console

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/test/java/io/questdb/cairo/TableWriterTest.java
Closes https://github.com/questdb/questdb/issues/1955
The callback works in "incremental" mode. In that listener is not notified when older partition is created. Notification only fired when time series moves forward in time.
=> feat(core): writer supports notification callback when table is extended

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/cairo/GeoHashes.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/text/TextMetadataParser.java, core/src/main/java/io/questdb/cutlass/text/types/GeoHashAdapter.java, core/src/main/java/io/questdb/cutlass/text/types/TypeManager.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/http/SendAndReceiveRequestBuilder.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Just like with ILP, CSV import supports geohash strings only (no geohash literals), so `u33d8` instead of `#u33d8`.
Also fixes JSON and Text processors failure on RECORD column type.
Docs PR: https://github.com/questdb/questdb.io/pull/772
=> Add geohash support for CSV import and export

ui/src/scenes/Editor/Monaco/questdb-sql/conf.ts
SQL editor has a definition of what a word (token) is - by default it does not allow certain special characters to be present, including brackets. Therefore, the logic that finds a word to highlight at a given position gets nothing, as a token starting with `(` is immediately discarded.
A good use case for having them allowed is a `bad integer` type of issue:
```
CREATE TABLE table_name (
column_name symbol index CAPACITY (200000),
)
```
The above should highlight the `(200000)` as an error.
Allow brackets in word matching regex.
=> fix(ui): adjust regex to allow brackets in editor tokens

ui/src/scenes/Editor/QueryPicker/Row/index.tsx, ui/src/scenes/Editor/QueryPicker/index.tsx, ui/src/store/Console/types.ts
This PR updates the "Example Queries" popup with a support to
display queries in groups.
For example, queries related to geohashing can be under a single group.
Depending on `savedQueries` array in
`assets/console-configuration.json`, the popup can look like so:
the `savedQueries` array in `assets/console-configuration.json` is what
governs this list. The array for what's seen in the screenshot is
roughly this (truncated for brevity):
```json
{
"savedQueries": [
{
"title": "Trading",
"description": "Examples of crypto currency trading queries",
"queries": [
{
"name": "All BTC trades",
"value": "select * from trade where symbol = 'BTC'"
},
// ...
]
},
{
"title": "Geohash",
"description": "Queries for geohashes",
"queries": [
{
"name": "Current positions within a geohash area",
"value": …
```
=> feat(ui): improve "Example Queries" popup to support groups

ui/src/scenes/Editor/Monaco/utils.ts
This PR fixes the issue of the following scenario:
1. open https://demo.questdb.io/
1. clear editor from any queries
1. type 'trades' (no semicolon)
1. press Run
1. open https://demo.questdb.io/?query=select%20*%20from%20trades%20latest%20on%20timestamp%20partition%20by%20symbol&executeQuery=true
1. observe that executed query is the wrong one (just 'trades', not the one from URL query)
`appendQuery` should correctly append and select query when cursor
position is first line which is not empty and there's more content after it.
covered by tests [here](https://github.com/questdb/ui/blob/main/packages/browser-tests/cypress/integration/console/editor.spec.js#L56-L76)
=> fix(ui): fix another `appendQuery` erroneous case

core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
This PR is in response to https://github.com/questdb/questdb/issues/1359 
Two tests have been added to exemplify the use of java.sql.Timestamp, and to verify that my understanding is correct.
=> Add two tests to the PGWire protocol to exemplify use of java.sql.Timestamp 

ui/src/providers/LocalStorageProvider/index.tsx, ui/src/providers/LocalStorageProvider/types.ts, ui/src/scenes/Editor/Menu/index.tsx, ui/src/utils/localStorage/types.ts
This PR adds a little red dot on the "Example Queries" button at the top of the editor.
Once user opens the popup, the red dot disappears. This state is saved in local storage.
=> feat(ui): add red dot indicator on "Example Queries" button

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGWireServer.java, core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/main/java/io/questdb/network/IODispatcher.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/FunctionParserErrorTest.java, ui/src/scenes/Editor/Monaco/utils.ts
Also - disconnect on unexpected errors to fix jdbc client lockup .
It's probably better to report such errors back to client but : 
1. simply returning "internal server error" in cursor phases doesn't seem to work and client still hangs
2. disconnecting should 'fix' potential server state corruption (as was the case with function parser)
=> fix(pgwire): fix persistent function parser issue

core/src/main/java/io/questdb/MessageBusImpl.java, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/mp/RingQueue.java, core/src/main/java/io/questdb/tasks/TableWriterTask.java, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/griffin/TableWriterAsyncCmdTest.java, core/src/test/resources/server.conf
TableWriter can be asked to run commands asynchronously if the writer is busy.
When this happens the command is serialised into a task and put on the writer's async command queue.
Each task owns a slot on the queue's buffer and it uses the memory of that specific slot.
If the serialised command could not fit in the memory assigned to the slot the task tried to reallocate memory.
There were two issues with this:
- the newly allocated memory was never released
- in principle the task should not allocate its own memory, it should use the memory slot given to it by the queue and the pointer should be made final
Removed memory resizing and changed the task to throw an exception on buffer overflow.
ILP deals with the situation the same way.
=> fix(cairo): handling of buffer overflow in async command queue

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/model/ExpressionNode.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/griffin/KeyedAggregationTest.java
Fixes: https://github.com/questdb/questdb/issues/2002
Replaces: https://github.com/questdb/questdb/pull/2018
=> fix(sql): fix ignored where clause (order by hour)

core/src/test/java/io/questdb/griffin/ReplModelReconTest.java
The comment is outdated. The test is not ignored and it is passing.
=> chore(test): remove outdated comment

core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/cutlass/http/DispatcherWriterQueueTest.java, core/src/test/java/io/questdb/cutlass/http/HttpFlushQueryCacheTest.java, core/src/test/java/io/questdb/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGFlushQueryCacheTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGMultiStatementMessageTest.java
`PGJobContextTest.testFlushQueryCache` and `IODispatcherTest.testJsonQueryFlushQueryCache` tests were flaky due to a await based on a hardcoded timeout. This change removes the timeout in favor of an event queue-based await. To keep the queue capacity override isolated, the tests are extracted into separate classes.
=> chore(test): fix flaky query cache flush tests

core/README.md, core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
Fixes #1452 
The original problem description "Expression parser does not always parse CASE statement correctly" is actually that, braces inside `CAST` are not properly matched, thus any nested arithmetic with braces will cause the error.
=> fix(sql): fix brace matching inside cast

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cutlass/line/tcp/DefaultColumnTypes.java, core/src/main/java/io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpReceiverConfiguration.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableStructureAdapter.java, core/src/main/java/io/questdb/cutlass/line/udp/DefaultLineUdpReceiverConfiguration.java, core/src/main/java/io/questdb/cutlass/line/udp/LineUdpParserImpl.java, core/src/main/java/io/questdb/cutlass/line/udp/LineUdpParserSupport.java, core/src/main/java/io/questdb/cutlass/line/udp/LineUdpReceiverConfiguration.java, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/BaseLineTcpContextTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpAuthConnectionContextTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContextTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpParserImplTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpParserSupportTest.java, core/src/test/resources/server.conf
When a new column is added on the fly via ILP ingestion QuestDB decides on the type of the field.
In case of a floating point value we chose to use DOUBLE, for integers we picked LONG.
It makes sense to use the largest types by default as we do not know what range of values will be inserted into the field.
However, if the user knows that they do not require double precision or that the range of integer values could fit in a SHORT, for example, they should have the option to configure which type should be used for new columns.
This helps to save disk space as they can avoid using 64-bit types where 32-bit or even smaller types could suffice.
This PR adds the config options to be able to override the default add column types.
Example config:
```
line.float.default.column.type=FLOAT …
```
=> feat(ilp): allow users to change default column type when ILP adds new column automatically

core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, ui/src/utils/questdb.ts
Closes #359 
The existing codes are already able to detect the errors and an error message will be returned, it's more reasonable to use the status code 400 with it to help the users know that something wrong happened, since checking the status code is always easier than checking the body.
---
#1949 is closed, leaving behind several problems, some are solved in this PR.
However, I still have a question:
- ~I'm not familiar with NGINX so far 😭 I'd appreciate it if you could simply point me in the right direction on how to test it.~ (solved)
> NGINX reverse proxy has to be tested for no adverse effects of changing the code. This step is manual.
=> feat(http): use status code 400 to indicate errors

core/src/main/java/io/questdb/griffin/engine/functions/bind/CompiledFilterSymbolBindVariable.java, core/src/main/java/io/questdb/griffin/engine/table/CompiledFilterRecordCursor.java, core/src/main/java/io/questdb/jit/CompiledFilterIRSerializer.java, core/src/test/java/io/questdb/griffin/CompiledFilterTest.java
Jit compiled filter did not handle SqlExecutionContext change by inlining references to Bind Variable functions, instead of the indexes and names. It lead to errors that incorrect bind variables can be used in PgWire
=> fix(sql): jit to handle sql context bind vars change

core/src/main/java/io/questdb/griffin/engine/functions/cast/CastStrToBooleanFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/FunctionParserCastFunctionsNullTest.java, core/src/test/java/io/questdb/griffin/NullLiteralsTest.java, core/src/test/java/io/questdb/griffin/engine/functions/cast/CastTest.java
This PR follows https://github.com/questdb/questdb/pull/2000 where a test was ignored because these statements threw exceptions:
```
select cast('' AS BOOLEAN) IS NULL --> false;
select cast('' AS BOOLEAN) IS NOT NULL --> true;
```
Pull 2000 contains tests for these statements (where `<non-nullable-type>` in [boolean, short, byte]):
```
select cast(0 AS <non-nullable-type>) IS NULL --> false;
select cast(0L AS <non-nullable-type>) IS NULL --> false;
select cast('' AS <non-nullable-type>) IS NULL --> false;
select cast(NULL AS <non-nullable-type>) IS NULL --> false;
select cast(false AS <non-nullable-type>) IS NULL --> false;
select cast(0 AS <non-nullable-type>) IS NOT NULL --> true;
select cast(0L AS <non-nullable-type>) IS NOT NULL --> true;
select cast('' AS <non-nullable-type>) IS NOT …
```
=> feat(sql): Add function to allow casts from string to boolean

core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/test/java/io/questdb/cairo/TableReaderMetadataCorruptionTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverTest.java
Fix in table meta data validation.
Offset was not checked properly against the size of the meta data.
Offset can be equal to the mem size as after reading the last column name the offset will be pointing just after the last byte of the meta data.
Depending on the column names, this offset could be exactly the size of the allocated meta data mem.
=> fix(cairo): fix meta data validation to avoid occasional error while adding new column

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java, core/src/test/java/io/questdb/griffin/CompiledFilterTest.java, core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java, pkg/ami/marketplace/assets/server.conf
Changes the default prop for SQL JIT compiler to "enabled", since it has proven itself to be stable. From v6.3, JIT compiler is not a beta feature anymore.
Docs PR: https://github.com/questdb/questdb.io/pull/832
=> chore(sql): enable JIT compiler by default

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java, core/src/test/resources/server.conf, pkg/ami/marketplace/assets/server.conf
JIT compiled filters are kept available only when parallel SQL filters are enabled.
Also updates AWS marketplace config artifact with the contents of the default `server.conf`. The reason for that it that they were totally out of sync.
=> chore(sql): add config option to disable parallel SQL filter execution

core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpReceiver.java, core/src/main/java/io/questdb/cutlass/pgwire/AbstractTypeContainer.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGJobContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGWireServer.java, core/src/main/java/io/questdb/cutlass/pgwire/TypesAndSelect.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/std/AbstractSelfReturningObject.java, core/src/main/java/io/questdb/std/SelfReturningObjectFactory.java, core/src/main/java/io/questdb/std/WeakClosableObjectPool.java, core/src/main/java/io/questdb/std/WeakMutableObjectPool.java, core/src/main/java/io/questdb/std/WeakObjectPoolBase.java, core/src/main/java/io/questdb/std/WeakSelfReturningObjectPool.java, core/src/test/java/io/questdb/std/WeakClosableObjectPoolTest.java, core/src/test/java/io/questdb/std/WeakMutableObjectPoolTest.java, core/src/test/java/io/questdb/std/WeakSelfReturningObjectPoolTest.java
A stack overflow could occur in situation when a cached SELECT or INSERT query container object gets returned to a pool. Luckily, such error would only happen with non-default settings for the pool capacities.
The issue is fixed by splitting `WeakAutoCloseableObjectPool` class into two separate classes with clear purposes: `WeakSelfReturningObjectPool` and `WeakCloseableObjectPool`. The first class is the one that is used in PG Wire caches. It doesn't expose `push()` method and instead assumes that the pooled objects return themselves to the pool as a part of the `close()` method call.
=> fix(sql): fix potential stack overflow in PG Wire select and insert cache pooling

core/src/main/java/io/questdb/griffin/engine/functions/groupby/StdDevSampleDoubleGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/StdDevSampleDoubleGroupByFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/griffin/engine/functions/groupby/StdDevSampleGroupByFunctionFactoryTest.java
Add support for standard deviation (sample) aggregate function. Fixes #1809 
The signature of the function is `stddev_samp` as used in [Postgres](https://www.postgresql.org/docs/9.1/functions-aggregate.html).
The current implementation follows the avg group by aggregate function and returns always a double value or null.
Tests have been added in a new file: `StddevSampleGroupByFunctionFactoryTest` and `sttdev_samp` check is added along other aggregate function inside `AvgDoubleGroupByFunctionFactoryTest` following the pattern there!
=> feat(sql): added support for standard deviation (sample) aggregate function

core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceJob.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java
Also removes redundant record and circuit breaker arrays from the page frame sequence. Only a single thread is responsible for dispatching, so it's enough to have a single object.
The race had a chance to show up for LIMIT N filters, i.e. when `await()` method had to correctly await for all dispatched tasks to be reduced and collected.
=> fix(sql): eliminate reduce counter race in page frame sequence used by parallel filters

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/cutlass/pgwire/PGSecurityTest.java
There was a bug where a value of each property was also used as a key for a property created out of thin air by a buggy pgwire parser.
So when a client sends a property with a value set to "user" then a buggy pgwire parser would create also a key "user" out of thin air with a value set as the next key.
Example:
```
2022-05-17T16:39:18.308689Z I i.q.c.p.PGConnectionContext property [name=user, value=admin] <-- this is a legit property
2022-05-17T16:39:18.308707Z I i.q.c.p.PGConnectionContext property [name=admin, value=database] <-- this is a property "invented" by a buggy pgwire parser
2022-05-17T16:39:18.308724Z I i.q.c.p.PGConnectionContext property [name=database, value=qdb] <-- a legit property set by a client
2022-05-17T16:39:18.308789Z I i.q.c.p.PGConnectionContext property …
```
=> fix(pgwire): Fix initial connection properties parser

core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/load/TableData.java
check table contents without timing out
=> chore: removed timeout from ILP test to hopefully prevent flapping tests

core/src/main/java/io/questdb/cairo/sql/PageAddressCacheRecord.java, core/src/test/java/io/questdb/EmbeddedApiTest.java, core/src/test/java/io/questdb/cairo/FullFwdDataFrameCursorTest.java, core/src/test/java/io/questdb/cutlass/http/HttpHealthCheckTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/HttpMinTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/BaseLineTcpContextTest.java, core/src/test/java/io/questdb/cutlass/pgwire/BasePGTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/AbstractO3Test.java, core/src/test/java/io/questdb/griffin/AsyncOffloadTest.java, core/src/test/java/io/questdb/griffin/LatestByParallelTest.java, core/src/test/java/io/questdb/griffin/O3FailureTest.java, core/src/test/java/io/questdb/griffin/O3Test.java, core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java, core/src/test/java/io/questdb/mp/TestWorkerPool.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
I wanted to verify that if we use multiple pools we don't share object instances between them
=> chore(sql): added test with asymmetric pools

core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java
This PR makes `/exp` endpoint only accepts SELECT queries, otherwise, an error will be returned.
Fixes #2045
=> fix(http): make /exp endpoint only allow SELECT

ci/dangerfile.js
Originally wanted to create this PR for #2147 but at the time of `git push` noticed that it's a fork, so can't use it as a base branch.
Aaaanyway
#2147 adds a new check for PRs which validates PR title.
If PR title does not adhere to a specific format, then a comment appears
on the PR with text like this:
> Please update the PR title. Titles need to match this format: <type>: <description>
However, at that point PR can be green and contributor might not know
what exactly goes into `<type>`.
Thus, this PR:
1. makes PR validation failure message more clear, looks like this:
> Please update the PR title. It should match this format: <type>: <description>
> Where <type> is one of: "feat", "fix", "chore", "docs", "style", "refactor", "perf", "test", "build", "ci", "chore", "revert"
2. uses …
=> feat: when PR title validation fails, display what types are available

.github/workflows/danger.yml, ci/dangerfile.js
___ 
Replaces #2147 
This PR adds a github action to validate PR titles using danger.
Here's an example of what it looks like if the title fails.
=> feat: add danger

.github/workflows/danger.yml, ci/dangerfile.js
___
Github doesn't allow secrets to start with `GITHUB_`. Renaming the key to allow it to work.
=> invalid: rename danger secret key

ui/src/scenes/Editor/Monaco/utils.ts
Fixes #2151
Note that to correct the slicing, we only need to change one line (L80 in the modified file), but previously web console behaves kind of strange when meeting multiple semicolons, the other changes are for that.
For example, the following query may include `;` as the beginning of a sql statement, or splitting out a single `;` as a statement. With the modifications in this PR, when a cursor is in the middle of semicolons, the nearest valid statement before the cursor will be executed.
```sql
;;select 1;;;;;
select 2;   ;
select 3;;select
4
```
=> fix(ui): fix sql statement slicing when the cursor is at the end position

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactory.java, core/src/test/java/io/questdb/griffin/engine/functions/cast/CastTest.java, core/src/test/java/io/questdb/griffin/engine/functions/eq/EqDoubleFunctionFactoryTest.java
Fixes #2112
Adding special judgment of 'infinity' in SQL commands to make `Infinity = Infinity` and `-Infinity = -Infinity`, no matter in float or in double.
Updated changed files:
- `EqDoubleFunctionFactory.java`: adding judgment using equality besides using subtraction
- `EqDoubleFunctionFactoryTest.java`: adding tests for direct equal operation
- `CastTest.java`: adding tests for using infinity in SQL commands
=> fix(sql): fix the comparison refer to 'infinity'

core/src/main/java/io/questdb/griffin/UpdateOperator.java, core/src/test/java/io/questdb/griffin/UpdateTest.java
Fixes #2173
QuestDB Record and Memory abstractions are inconsistent in how they encode/decode/cast boolean values.
Memory uses 1 to represent TRUE and 0 to FALSE, Record does the opposite.
UPDATE treated boolean values as bytes.
Basically when took a 0 value from the Record and put it into a Memory object it turned TRUE to FALSE, and the opposite for the byte value 1 where it turned FALSE to TRUE.
The fix is to not treat boolean values as bytes on the Record and Memory APIs, just use getBool() and putBool() instead which will not care about how the boolean values are represented internally.
=> fix(griffin): fix for mixing up TRUE and FALSE while updating BOOLEAN field

core/src/main/java/io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceJob.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/std/MemoryTag.java
`testUpdateBusyTable()` seems to leak memory equivalent to what circuit breaker allocates. In this test circuit breaker is allocated 5 times, which makes it unclear as to what site leaked the instance. 
I'm unable to reproduce the issue locally.
=> chore(test): added more granular memory tracing to help understand flapping test

benchmarks/src/main/java/org/questdb/QMapReadRandomKeyBenchmark.java, benchmarks/src/main/java/org/questdb/QMapReadSequentialKeyBenchmark.java, benchmarks/src/main/java/org/questdb/QMapWriteBenchmark.java
Ubuntu 20.04 64-bit, OpenJDK 17:
```
Benchmark                         Mode  Cnt  Score   Error  Units
QMapWriteBenchmark.baseline       avgt    3  0.277 ± 0.128  us/op
QMapWriteBenchmark.testDirectMap  avgt    3  0.735 ± 0.413  us/op
QMapWriteBenchmark.testHashMap    avgt    3  0.853 ± 0.385  us/op
QMapWriteBenchmark.testQMap       avgt    3  0.791 ± 0.843  us/op
Benchmark                                     Mode  Cnt  Score   Error  Units
QMapReadSequentialKeyBenchmark.baseline       avgt    3  0.010 ± 0.003  us/op
QMapReadSequentialKeyBenchmark.testDirectMap  avgt    3  0.324 ± 0.191  us/op
QMapReadSequentialKeyBenchmark.testHashMap    avgt    3  0.268 ± 0.091  us/op
QMapReadSequentialKeyBenchmark.testQMap       avgt    3  0.360 ± 0.042  us/op
Benchmark …
```
=> chore(benchmark): add j.u.HashMap for comparison in map benchmarks

core/src/main/java/io/questdb/log/Logger.java, core/src/test/java/io/questdb/log/LogFactoryTest.java
Fixed:
[https://dev.azure.com/questdb/questdb/_build/results?buildId=7788&view=logs&j=2a8db[…]-53bd-306b-3f5b3836e6eb&t=856b52a7-8d37-5a6e-f64c-b8e55c77b9fc](https://dev.azure.com/questdb/questdb/_build/results?buildId=7788&view=logs&j=2a8db746-6336-53bd-306b-3f5b3836e6eb&t=856b52a7-8d37-5a6e-f64c-b8e55c77b9fc)
```
Failed tests:
LogFactoryTest.testRollingFileWriterByHour:311->testRollOnDate:724 ‘mylog-2015-05-04-03.log’ does not contain: mylog-2015-05-03
LogFactoryTest.testRollingFileWriterByMonth:321->testRollOnDate:724 ‘mylog-2016-02.log’ does not contain: mylog-2015
```
=> chore: fixed flapping logger test

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpReceiverConfiguration.java, core/src/main/java/io/questdb/cutlass/line/udp/DefaultLineUdpReceiverConfiguration.java, core/src/main/java/io/questdb/cutlass/line/udp/LineUdpLexer.java, core/src/main/java/io/questdb/cutlass/line/udp/LineUdpParserImpl.java, core/src/main/java/io/questdb/cutlass/line/udp/LineUdpReceiverConfiguration.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/BaseLineTcpContextTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContextTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpParserImplTest.java, core/src/test/resources/server.conf
Adds 2 configuration options:
```
#line.auto.create.new.columns=true
#line.auto.create.new.tables=true
```
Done for production hardening where new tables should not be created dynamically when a client sends bad formatted data to ILP socket.
As a side enhancement `TableReader` when created will check that table folder exists on first failure opening metadata. This is to fix retrying to open metadata file and timing out on deleted / non existing tables
=> feat(ilp): make ILP implicit schema optional

ui/src/scenes/Footer/BuildVersion/index.tsx, ui/src/scenes/Footer/BuildVersion/services.ts
The main purpose of this PR is to fix an issue wherein `select build()` is fired repeatedly upon resizing panels (caused by the side effect hook being called on each re-render).
Instead of copying to clipboard, the button now links to either release notes (when using a ready-made version) or commit hash (i.e. on a custom local build). 
Release info:
Custom build info:
=> fix(ui): Fix `select build()` being called repeatedly

core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpNetworkIOJob.java, core/src/main/java/io/questdb/cutlass/line/tcp/SymbolCache.java, core/src/main/java/io/questdb/std/ObjIntHashMap.java, core/src/test/java/io/questdb/cairo/SymbolMapTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/SymbolCacheTest.java, core/src/test/java/io/questdb/std/ObjIntHashMapTest.java
Symbol cache was set to the current symbol count on initialization and never shrinked back. This might lead to multiple large contiguous on-heap arrays kept in `LineTcpNetworkIOJob#unusedSymbolCaches` which may become problematic for JVM's compacting garbage collectors.
=> chore(ilp): make sure to reset symbol cache capacity when ILP connection is closed

core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java, core/src/main/java/io/questdb/cutlass/line/Sender.java, core/src/test/java/io/questdb/cutlass/line/interop/TestInterop.java
This PR adds support for custom timestamp columns accepting both microseconds since UNIX epoch as a long and ISO 8601 formatted UTC timestamp.
=> feat(cutlass): add support for custom timestamp columns

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml
- add notes in the template to facilitate higher-quality github bug reports
- disable blank github issues to reduce the chance of receiving freestyle github issues from the users
- add a link to our slack community for users who have generic questions, increasing the slack visibility
=> chore(docs): improve github issue template

core/src/main/java/io/questdb/griffin/engine/groupby/MonthTimestampSampler.java, core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java, core/src/test/java/io/questdb/griffin/engine/groupby/MonthTimestampSamplerTest.java, core/src/test/java/io/questdb/griffin/engine/groupby/SampleByTest.java
For certain timestamps, `MonthTimestampSampler#nextTimestamp()` was returning the provided timestamp instead of the timestamp larger by N months. Apart from that, `MonthTimestampSampler#round()` could also return incorrect values. See the added tests for more details.
All of the above issues led to an infinite loop in `SampleByFirstLastRecordCursor#getNextState()`.
=> fix(sql): fix infinite loop in SAMPLE BY month over first or last values and indexed column filter

core/Dockerfile, core/docker-entrypoint.sh, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/SimulateCrashFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/functions/catalogue/SimlateCrashFunctionTest.java
Tested with:
- legacy questdb root folder on /root/.questdb
- questdb will run as root
- if there are problems with `/root/.questdb` mount detection there is a environment variable flag that will disable the check: `IGNORE_DATA_ROOT_MOUNT_CHECK`
- in this case setting `IGNORE_DATA_ROOT_MOUNT_CHECK` to true, `QUESTDB_DATA_DIR` to `/root/.questdb` and `RUN_AS_ROOT` to true should have the same effect
- new questdb root folder on /var/lib/questdb
- if data in /var/lib/questdb is own by other than questdb:questdb it will change ownership to questdb:questdb, this should help with migration
- different entrypoint overwrite (docker-entrypoint.sh is bypassed)
- different arguments to /app/bin/java
- different commands that start with /app/bin/java
- with other user than questdb, works but should …
=> feat: run as questdb user in docker

core/src/main/java/io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java, core/src/test/java/io/questdb/griffin/LatestByTest.java, core/src/test/java/io/questdb/griffin/TimestampQueryTest.java
Otherwise, it throws a NPE:
```
java.lang.NullPointerException
at io.questdb/io.questdb.griffin.engine.functions.bool.InSymbolFunctionFactory$Func.getBool(InSymbolFunctionFactory.java:125)
at io.questdb/io.questdb.griffin.engine.table.LatestByValueFilteredRecordCursor.findRecord(LatestByValueFilteredRecordCursor.java:102)
at io.questdb/io.questdb.griffin.engine.table.LatestByValueFilteredRecordCursor.of(LatestByValueFilteredRecordCursor.java:86)
at io.questdb/io.questdb.griffin.engine.table.LatestByValueFilteredRecordCursorFactory.getCursorInstance(LatestByValueFilteredRecordCursorFactory.java:73)
at io.questdb/io.questdb.griffin.engine.table.AbstractDataFrameRecordCursorFactory.getCursor(AbstractDataFrameRecordCursorFactory.java:54)
at …
```
=> fix(sql): LatestByValueFilteredRecordCursor to initialize filter before use

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/pool/WriterPool.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFirstLastRecordCursorFactory.java, core/src/main/java/io/questdb/log/Log.java, core/src/main/java/io/questdb/log/Logger.java, core/src/main/java/io/questdb/log/SyncLogger.java, core/src/main/java/io/questdb/mp/Worker.java, core/src/test/java/io/questdb/log/LogAlertSocketTest.java, core/src/test/java/io/questdb/network/NetTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
With this change, instance log alerting can be based on ` C ` (critical log level) entries instead of ` E ` (error level) which produces lots of false positives.
cc @mariusgheorghies 
Also removes unused `Log#isDebugEnabled()` method and improves code style slightly.
=> feat(core): use critical level to log all unhandled errors

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TxReader.java, core/src/test/java/io/questdb/cairo/TableReadFailTest.java, core/src/test/java/io/questdb/cairo/TableReaderTest.java
`TableReader` may miss last transaction on reload when it is taken from `ReaderPool`. This happens when the updated transaction record is read before returning to the pool at which point reader does not reload it's state according to the newly read transaction.
The outcome is that reader doesn't see the data of last transaction regardless how many time it's reloaded. For the end user adding few lines to the table using ILP these lines can be invisible until the server restart or another transaction committed.
=> fix(cairo): fix issue when SELECTS do not see committed data

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/network/AbstractIODispatcher.java, core/src/main/java/io/questdb/network/IOContext.java
Removing the piece of code checking if anything left in the buffer unprocessed when ILP disconnect happens.
This check was put in place hoping it will help to find the root cause of ILP fuzz test timeouts but it did not help.
Instead now it is causing trouble because when ILP authentication fails the buffer is not compacted.
We can see a misleading error on the log after every ILP auth failure.
=> chore(ilp): removing dumpBuffer()

core/src/main/java/io/questdb/std/Numbers.java, core/src/test/java/io/questdb/std/NumbersTest.java
The negative sign has to be applied to a double.
The original code applied the sign to long. Which means negative zero was parsed as non-negative zero.
=> fix(core): Parse negative zero

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpReceiver.java, core/src/main/java/io/questdb/cutlass/pgwire/DefaultPGWireConfiguration.java, core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java, core/src/main/java/io/questdb/std/ThreadLocal.java, core/src/main/java/io/questdb/std/str/Path.java, core/src/test/java/io/questdb/std/str/PathTest.java
`Path.clearThreadLocals()` did not guarantee that it will not call `malloc()`, which usually happened where thread local was `null` in the first place.
Calling `malloc` on shutdown could be troublesome, because system could be shutting down because of `malloc()` failure in the first place. Shutdown code path should be free of `malloc()` calls.
Additionally:
- reduced default PG context pool size from 64 to 4. 
- replaced `RuntimeException` handling with `Throwable` and reducing size of `RecordChain` when exception occurs
=> chore: Our own ThreadLocal does not allocate new instance when closing

core/src/main/java/io/questdb/cutlass/line/Sender.java
TCP port 9001 is default in (some) tests only.
The product uses 9009 by default.
=> fix(ILP): change default Sender port

core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursor.java, core/src/test/java/io/questdb/griffin/LimitTest.java
Closes #2308
`DataFrameRecordCursor#skipTo()` implementation was wrongly assuming same row indexes in `dataFrameCursor` and `rowCursor` while in reality the `rowCursor` might be using an index (hence, implicitly filtering the rows).
Note: there are some optimization opportunities for such limit -N + indexed filter queries we could implement. Namely, we could potentially use a backward-direction index reader.
=> fix(sql): incorrect result for negative limit query with indexed symbol filter

core/docker-entrypoint.sh
find command should always return 0, useful when used in kuberenetes and we mount configmaps into conf/ directory
=> fix(build): fixed docker entry point exiting prematurely on chown errors

ci/dangerfile.js
This PR adds more rules to `ci/dangerfile.js`.
If a contributor would submit a PR with a title which is considered
invalid by those rules, the CI would post a comment like this below:
---
Please update the PR title to match this format:
`type(subType): description`
Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `build`, `ci`, `chore`, `revert`
And `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`
For Example:
```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
---
same thing in screenshot:
=> chore(build): augment PR title validation rules

core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java
testImportWithSkipRowAtomicityImportsNoRowsWhenNonTimestampColumnCantBeParsed() was running 20-30s on M1. Now it's <5s.
This slowness caused a timeout on CI: we were unlucky and the test was running on a cloud box with super slow I/O.
=> chore(sql): test speedup

core/src/main/java/io/questdb/griffin/model/IntervalUtils.java, core/src/test/java/io/questdb/griffin/InsertTest.java, core/src/test/java/io/questdb/griffin/model/IntrinsicModelTest.java
=> fix(sql): fix incorrect timezone arithmetic in `insert` SQL

core/src/main/java/io/questdb/PropServerConfiguration.java
Changes default thread pool counts to make use of all available CPU cores instead of half of them as we do it now. Includes:
* Minimal size of shared worker thread pool is now 2. That's to avoid starvation (incl. health check) due to a long running query.
* A few spare cores are left for >8 and >16 cores cases. That's to leave some room to breathe to JVM & OS.
=> feat(core): use all available cores by default

core/src/main/java/io/questdb/PropServerConfiguration.java
This PR changes internal default of  pg.net.connection.queue.timeout setting from 5s to 300s to make it consistent with value in server.conf .
=> chore(conf): make default value of pg.net.connection.queue.timeout consistent with server.conf file

core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/griffin/OrderByWithFilterTest.java, core/src/test/java/io/questdb/griffin/SqlParserTest.java
Fixes parser not accepting ASC or DESC for last order by column in over clause .
Example: 
```sql
create table weather
(
timestamp timestamp,
temperature float
) timestamp(timestamp) partition by year;
select timestamp, temperature from 
( 
Select temperature, timestamp, 
row_number() over (partition by timestamp_floor('y', timestamp) order by temperature desc )  rid 
from weather2 
) inq 
where rid = 0 
order by timestamp
```
returns 
_',' or ')' expected_ 
error
=> fix(sql): fix order in over clause not accepting direction

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/griffin/UpdateOperator.java, core/src/test/java/io/questdb/griffin/UpdateTest.java
`TableUtils.setNull` did not respect geohash null value to be -1 instead of 0 as for other column types.
Also `TableReader` when reading partition with missing column did not set the column to have column top but instead relied on `NullMemoryMR.Instance` to return null values which are different for `Short` and `GeoShort` types.
=> fix(core): fix default geohash value to be NULL instead of 0 for existing rows when column added

core/src/main/java/io/questdb/WorkerPoolAwareConfiguration.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGWireServer.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlExecutionContext.java, core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java, core/src/test/java/io/questdb/cutlass/line/udp/LinuxLineUdpProtoReceiverTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
This PR fixes an inconsistency in the SqlCodeGenerator and PageFrameReduceJob worker count configuration that could lead to errors/crashes during processing.
Replaces: https://github.com/questdb/questdb/pull/2399
=> fix(sql): inconsistency in worker count configuration for asynchronous filters

core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/test/java/io/questdb/griffin/CopyTest.java
Fixes upper case handling for the following keywords: DATE, DAY, DECADE, LEVEL, Minute, Search_Path, Second, System, DateStyle.
=> fix(sql): fix case sensivity for certain keywords

core/src/main/java/io/questdb/griffin/engine/groupby/AbstractSampleByNotKeyedRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java, core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
Fixes #2441
The issue was twofold. First, both AsyncFiltered* cursors could throw a filter-caused exception on `of()` call. This broke the `close()` contract in all factories dealing with a base cursor. Second, `AbstractSampleByNotKeyedRecordCursorFactory` was not closing the base cursor properly.
As a result, an exception thrown by the filter or an early client disconnection led to situation when the async filtered cursor wasn't properly closed.
=> fix(sql): fix potential resource leak in non-keyed sample by with filter

examples.manifest.yaml, examples/src/main/java/com/example/sender/AuthExample.java, examples/src/main/java/com/example/sender/AuthExampleAnnotated.java
to be used in documentation
also updated questdb (client) library versions
=> docs(ilp): add an example with auth, but without TLS

examples/src/main/java/com/example/sender/AuthExample.java
otherwise the license gets rendered in a documentation code sample
=> docs(ilp): remove license header from the auth example

core/pom.xml, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java, core/src/test/java/io/questdb/griffin/AlterTableAttachPartitionTest.java, core/src/test/java/io/questdb/griffin/AlterTableDetachPartitionTest.java
`cairo.detach.root` defaulted to `cairo.root`. So considering the dirs are the same, documenting manual partition shuffling is easy. When they are not the same - shuffling of partition becomes a mess, which is hard to document. I struggled to find a reason why anyone would want these dirs to be different. Hence why I removed the configuration.
=> chore(core): removed "cairo.detach.root" config property

core/src/main/java/io/questdb/Metrics.java, core/src/main/java/io/questdb/cairo/TableWriterMetrics.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/processors/HealthCheckMetrics.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryMetrics.java, core/src/main/java/io/questdb/cutlass/http/processors/QueryCache.java, core/src/main/java/io/questdb/cutlass/pgwire/PGJobContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGWireMetrics.java, core/src/main/java/io/questdb/metrics/Counter.java, core/src/main/java/io/questdb/metrics/Gauge.java, core/src/main/java/io/questdb/metrics/GaugeImpl.java, core/src/main/java/io/questdb/metrics/MemoryTagGauge.java, core/src/main/java/io/questdb/metrics/NullCounter.java, core/src/main/java/io/questdb/metrics/NullGauge.java, core/src/main/java/io/questdb/metrics/VirtualGauge.java, core/src/main/java/io/questdb/std/AssociativeCache.java, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/cutlass/http/HttpFlushQueryCacheTest.java, core/src/test/java/io/questdb/cutlass/http/HttpHealthCheckTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/HttpMinTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/pgwire/PGFlushQueryCacheTest.java, core/src/test/java/io/questdb/griffin/AbstractGriffinTest.java, core/src/test/java/io/questdb/std/AssociativeCacheTest.java
Fixes #2286
Fixes #2349
Fixes `flush_query_cache()` function tests flakiness. The tests no longer rely on memory consumption, but instead check the new metric values.
=> feat(sql): add gauge metrics for current cached query count

core/src/main/java/io/questdb/cairo/SymbolMapWriter.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/cairo/TableWriterTest.java
`TableWriter.rollback()` did not set corresponding null setters when there was O3 transaction rolled back.
This may lead to writing wrong values or even crash on subsequent writes to the table.
=> fix(core): fixes table rollback() that may lead to incorrect writes or crash

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilterAtom.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cairo/AbstractCairoTest.java, core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java, core/src/test/java/io/questdb/griffin/CompiledFilterTest.java, core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java, core/src/test/resources/server.conf, pkg/ami/marketplace/assets/server.conf
In case of a large table that doesn't fit to OS page cache (think, free RAM), performance of queries that use parallel filter may be limited with the capabilities of the single ("query owner") thread.
Here is an example scenario:
```sql
SELECT col_a, col_b, ..., col_N
FROM tab
WHERE ts in '2016-02-10' and col_a = 'foobar';
```
Here the filter only touches col_a which has all chances to fit to page cache, so filtering itself may be fast. Yet, the owner thread would have to accumulate all selected column values into the send buffer which may lead to page faults on almost each mmapped memory access, especially if filtered rows aren't located in the same pages (think, they're spread in terms of time).
When `cairo.sql.parallel.filter.pretouch.enabled=true`, all threads that participate in …
=> feat(sql): add column pre-touch for parallel filter

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java
Removed busy spin around CAS error on ILP sequence from both ends, sender and writer.
=> fix(ilp): reduce ILP queue contention

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/WalWriter.java, core/src/main/java/io/questdb/cairo/sql/PageAddressCacheRecord.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceJob.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/LocalValueMap.java, core/src/main/java/io/questdb/griffin/engine/EmptyTableRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/columns/SymbolColumn.java, core/src/main/java/io/questdb/griffin/engine/groupby/MapSymbolColumn.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java, core/src/main/java/io/questdb/log/LogFactory.java, core/src/main/java/io/questdb/mp/RingQueue.java, core/src/main/java/io/questdb/mp/WorkerPool.java, core/src/main/java/io/questdb/std/AssociativeCache.java, core/src/main/java/io/questdb/std/Misc.java, core/src/main/java/io/questdb/std/ThreadLocal.java, core/src/main/java/io/questdb/std/WeakMutableObjectPool.java, core/src/test/java/io/questdb/griffin/AbstractGriffinTest.java, core/src/test/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
This PR makes Misc.free() and Misc.freeObjList() accept Closeable-derived argument only to improve type safety . 
If input type is not necessarily a Closeable then freeIfCloseable() or freeObjListIfCloseable() should be used . 
PR also contains fixes for several bad calls of aforementioned methods .
=> chore(core): improve cleanup method's reliability and fix several bad calls

core/src/main/java/io/questdb/cairo/vm/MemoryCMRImpl.java, core/src/test/java/io/questdb/griffin/O3FailureTest.java
Fixes this error from CI
```
2022-10-06T10:18:42.7683627Z 2022-10-06T10:18:42.719293Z I i.q.c.TableWriter ADDED column 'col428[SYMBOL], name txn 639 to /tmp/junit4122981112622880555/dbRoot/tbl_meta_test
2022-10-06T10:18:42.7684649Z 2022-10-06T10:18:42.720608Z E i.q.c.AbstractCairoTest 
2022-10-06T10:18:42.7685393Z io.questdb.cairo.CairoException: [0] File is too small, size=20480, required=20490
2022-10-06T10:18:42.7686143Z 	at io.questdb.cairo.CairoException.critical(CairoException.java:89)
2022-10-06T10:18:42.7686904Z 	at io.questdb.cairo.TableUtils.getCharSequence(TableUtils.java:1194)
2022-10-06T10:18:42.7687656Z 	at io.questdb.cairo.TableUtils.getColumnName(TableUtils.java:1177)
2022-10-06T10:18:42.7688394Z 	at io.questdb.cairo.TableUtils.validateMeta(TableUtils.java:1032) …
```
=> fix(sql): fix TableReader metadata open when columns are added frequently

core/src/main/java/io/questdb/cairo/ColumnPurgeJob.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpWriterJob.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
Reducing default `commitLag` to 1 second uncovered issue that if the commit itself takes longer than 1 second ILP degrades to row by row commit.
This fix accounts to the fact that commits are not instant in the calculations of the next commit time.
=> fix(ilp): fix degradation of row-by-row commit when commit operation takes longer than commit lag

core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java
fixes flapping test
```
2022-10-09T01:13:21.7641220Z 2022-10-09T01:13:21.712177Z I i.q.c.AbstractCairoTest Tearing down test PGJobContextTest#testFetchDisconnectReleasesReaderCrossJoin
2022-10-09T01:13:21.7682280Z 2022-10-09T01:13:21.723752Z E i.q.TestListener ***** Test Failed *****io.questdb.cutlass.pgwire.PGJobContextTest.testFetchDisconnectRe
leasesReaderCrossJoin : 
2022-10-09T01:13:21.7684460Z java.lang.AssertionError
2022-10-09T01:13:21.7685660Z    at org.junit.Assert.fail(Assert.java:87)
2022-10-09T01:13:21.7686940Z    at org.junit.Assert.fail(Assert.java:96)
2022-10-09T01:13:21.7688970Z    at io.questdb.cutlass.pgwire.PGJobContextTest.lambda$testFetchDisconnectReleasesReaderCrossJoin$17(PGJobContextTest.java:2145)
2022-10-09T01:13:21.7690610Z    at …
```
=> test(pgwire): fix flaky testFetchDisconnectReleasesReaderCrossJoin

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpUtils.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java, core/src/main/java/io/questdb/std/Chars.java, core/src/main/java/io/questdb/std/DirectByteCharSequenceIntHashMap.java, core/src/test/java/io/questdb/std/CharSequenceIntHashMapTest.java, core/src/test/java/io/questdb/std/DirectByteCharSequenceIntHashMapTest.java
Together with https://github.com/questdb/questdb/pull/2635 this PR stabilized performance of ILP ingestion by eliminating 
[megamorphic virtual calls](https://shipilev.net/jvm/anatomy-quarks/16-megamorphic-virtual-calls/). Specifically `charAt()` calls on `CharSequence` implementations.
On my desktop I get very stable TSBS performance of 1.2+M rows/s. Never below (notwithstanding short default lag, which could send TSBS into O3)
=> fix(ilp): fix variability in ILP performance

ci/dangerfile.js
```
feat(ui): hello world
chore(ui): hellow world
build: 6.6
```
new sub-type "ui", can be used with any type
```
build(sql): hello
build(core): hello
build(anything): hello
```
no brackets after "build" type.
=> chore(build): allow `build:` without `()` and `ui` subtype in PR titles

core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpCommitTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/load/TableData.java
The problem is that return was being called many times, so the first time did unlock the wait, and broke the test, in a non deterministic manner.
Closes https://github.com/questdb/questdb/issues/2340
=> chore(core): fix fuzzy test in line protocol (#2340)

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/main/java/io/questdb/cairo/pool/PoolListener.java, core/src/test/java/io/questdb/AbstractBootstrapTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AlterTableDropActivePartitionLineTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AlterTableLineTcpReceiverTest.java
closes https://github.com/questdb/questdb/issues/2529
truncate cannot be used when we are dropping the very last partition because that results in the removal of index files on the spot. This action must be delayed.
=> chore(core): allow dropping active partition concurrently with line ingress

core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/griffin/engine/analytic/AnalyticFunctionTest.java
current rank() implementation crashes tests on M1 CPU. It corrupts VM memory somehow. I didn't not have time to understand how.
We will do this after release
=> chore(sql): remove rank() function temporarily, it is unstable

core/src/test/java/io/questdb/cutlass/line/tcp/AlterTableLineTcpReceiverTest.java
fixes #2350
There is a race between returning an idle TableWriter into a pool and ALTER execution. If a TableWriter is returned before ALTER is executed then the ALTER succeeds and the test fails.
There is a tension between idleWriterTimeout and test duration: The smaller the timeout the greater likelihood of a test failure, but a long timeout increases test duration. So I'm increasing it from 250ms to 1000ms. It should help. If it does not then perhaps the test should be redesigned entirely.
=> test(ilp): fix flaky test

core/src/main/java/io/questdb/cairo/PartitionBy.java, core/src/main/java/io/questdb/griffin/engine/functions/date/MicrosOfSecondFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/groupby/MonthTimestampSampler.java, core/src/main/java/io/questdb/griffin/engine/groupby/YearTimestampSampler.java, core/src/main/java/io/questdb/std/Numbers.java, core/src/main/java/io/questdb/std/datetime/microtime/GenericTimestampFormat.java, core/src/main/java/io/questdb/std/datetime/microtime/TimestampFormatCompiler.java, core/src/main/java/io/questdb/std/datetime/microtime/TimestampFormatUtils.java, core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java, core/src/main/java/io/questdb/std/datetime/millitime/DateFormatCompiler.java, core/src/main/java/io/questdb/std/datetime/millitime/DateFormatUtils.java, core/src/main/java/io/questdb/std/datetime/millitime/GenericDateFormat.java, core/src/main/resources/text_loader.json, core/src/test/java/io/questdb/griffin/engine/functions/str/ToStrDateAndTimestampTest.java, core/src/test/java/io/questdb/std/datetime/microtime/TimestampFormatCompilerTest.java, core/src/test/java/io/questdb/std/datetime/microtime/TimestampsTest.java
fixes https://github.com/questdb/questdb/issues/2687
Also fixes ISO week parsing issue, introduced by https://github.com/questdb/questdb/pull/2632
=> feat(core): add support for `U+` - six-digit microsecond format component

core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java, core/src/test/java/io/questdb/cutlass/pgwire/PGSecurityTest.java, core/src/test/java/io/questdb/griffin/InsertNullGeoHashTest.java, core/src/test/java/io/questdb/griffin/InsertTest.java, core/src/test/java/io/questdb/griffin/LatestByTest.java, core/src/test/java/io/questdb/griffin/SimulatedDeleteTest.java, core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
Also fixes a number of issues around `INSERT INTO t VALUES()` and missing `Assert.fail()` in tests.
=> fix(sql): fix NullPointerException in join query over latest on sub-queries

core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/griffin/InsertTest.java
Closes #2719
The execution algorithm is the same as for `insert into table select ...`
=> feat(sql): support `insert into table with ...` syntax

core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerAPI.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java, core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/std/DirectLongListTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
The change is in `TableSequencerAPI`:
```
-            if (!entry.isDistressed()) {
+            if (!entry.isDistressed() && !entry.isClosed()) {
```
=> fix(core): fix race in WAL table transaction log

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/griffin/UnionTest.java
Fixes unnecessary recursion in sql optimiser taking minutes (and more) to process queries with many set operations, e.g. 
```sql
select 1 as a, select 2 as b
union all 
select 1 as a, select 2 as b
union all 
...
```
=> fix(sql): fix slow optimisation of queries with many set operations

core/src/main/java/io/questdb/cairo/sql/SymbolLookup.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java
If new symbol columns are added during heavy ILP ingestion it can happen that the new symbol field appears on more ILP lines before the column gets added to the table.
This means that while processing the second, third... lines `TableReader` could be _behind_, meaning it cannot see the new column yet for some time.
The same can happen to the metadata requested from the pool but that seems to reload faster, refresh is called on every get().
These are the different phases:
1. Pooled metadata and the reader are both behind, they are sync, no problem.
2. Pooled metadata has been refreshed but the reader is still behind, this is the window when we can see errors.
3. Pooled metadata and the reader are both refreshed, they are sync, no problem.
Solution is to treat the second phase the same way …
=> chore(ilp): symbol cache fix

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/cairo/wal/WalTableWriterTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/AbstractLineTcpReceiverFuzzTest.java, core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverUpdateFuzzTest.java, core/src/test/java/io/questdb/griffin/wal/WalPurgeJobTest.java
When UPDATE is compiled in the apply job it should use TableReader's metadata and not the latest from Sequencer.
Sequencer's metadata can be ahead of the current state of the table.
=> chore(wal): UPDATE compilation to use TableReader metadata in apply job

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/TxWriter.java, core/src/main/java/io/questdb/cairo/vm/api/MemoryCR.java, core/src/test/java/io/questdb/griffin/O3MaxLagTest.java
Fix bug introduced in #2759 when data is first written to future partition but not committed from the first commit because of calculated lag.
=> fix(core): fix potential corrupt data produced when writing from ILP on partition boundaries

core/src/main/java/io/questdb/Bootstrap.java, core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/GenericRecordMetadata.java, core/src/main/java/io/questdb/cairo/O3PartitionPurgeJob.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/wal/SymbolMapDiff.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableStructureAdapter.java, core/src/main/java/io/questdb/cutlass/text/CsvFileIndexer.java, core/src/main/java/io/questdb/griffin/DatabaseSnapshotAgent.java, core/src/main/java/io/questdb/griffin/SqlCompiler.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/engine/EmptyTableRandomRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/table/DataFrameRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java, core/src/main/java/io/questdb/griffin/model/InsertModel.java, core/src/main/java/io/questdb/jit/CompiledFilterIRSerializer.java, core/src/main/java/io/questdb/log/LogFactory.java, core/src/main/java/io/questdb/log/LogRecord.java, core/src/main/java/io/questdb/log/Logger.java, core/src/main/java/io/questdb/log/NullLogRecord.java, core/src/main/java/io/questdb/log/SyncLogger.java, core/src/test/java/io/questdb/cutlass/pgwire/PGSecurityTest.java, core/src/test/java/io/questdb/griffin/AlterTableDropActivePartitionTest.java, core/src/test/java/io/questdb/griffin/O3MaxLagTest.java, core/src/test/java/io/questdb/griffin/O3PartitionPurgeTest.java, core/src/test/java/io/questdb/griffin/wal/WalAlterTableSqlTest.java, core/src/test/java/io/questdb/log/LogAlertSocketTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
Now that QuestDB allows to drop last (active) partition the Async `O3PurgePartitionJob` need to be adjusted to the use case and remove the directory from disk.
Also here added more logging on what `O3PurgePartitionJob` tries to delete and return error when partition DROP or DETACH with WHERE clause do not find suitable partition to detach to have same feedback as dropping with LISTing partition syntax.
=> fix(core): fix partition directory left on disk when latest dropped

core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Fix for occasional CI failure.
IODispatcherTest produced the below error:
```
Exception in thread "Thread-327" java.lang.AssertionError: could not connect, errno=49
at org.junit.Assert.fail(Assert.java:89)
at io.questdb/io.questdb.test.tools.TestUtils.assertConnect(TestUtils.java:89)
java.lang.AssertionError: Not all requests successful, test failed, see previous failures
at org.junit.Assert.fail(Assert.java:89)
at io.questdb/io.questdb.cutlass.http.IODispatcherTest.lambda$testTwoThreadsSendTwoThreadsRead$56(IODispatcherTest.java:6873)
```
```
EADDRNOTAVAIL   49              /* Can't assign requested address */
```
The problem seems to be that sometimes the connection lingers around for some time after it is closed and trying to open a new connection results in EADDRNOTAVAIL (49).
Setting …
=> chore(core): fix flaky IODispatcher test

core/src/test/java/io/questdb/cairo/TxnScoreboardTest.java
Check in Scoreboard concurrency test the pattern used in production code to determine that there are no readers and it's safe to delete the partition version to prevent random test failures.
=> chore(build): fix `TxnScoreboardTest.testHammer` to check the pattern used in production code

core/src/main/java/io/questdb/cairo/sql/RecordCursorFactory.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceJob.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameReduceTask.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/log/LogFactory.java, core/src/main/java/io/questdb/mp/AbstractSSequence.java, core/src/main/java/io/questdb/mp/AbstractSequence.java, core/src/main/java/io/questdb/mp/FanOut.java, core/src/main/java/io/questdb/mp/MCSequence.java, core/src/main/java/io/questdb/mp/SCSequence.java, core/src/test/java/io/questdb/mp/ConcurrentTest.java
Fixes #2513
The problem was three-fold:
* `AsyncFilteredRecordCursor` wasn't calling `frameSequence.done()` in `topTo()`.
* Dynamic sequence addition/removal in `PubSub` could lead to out-of-sync barriers. See `testConcurrentFanOutAsyncOffloadPattern` for the reproducer.
* Our sequences (at least, the MP/MC ones) aren't sequentially consistent, so our `await()` code that was relying on the reducer counter value and the `cursor == -1` check led to unconsumed page frame tasks left in the queue.
The problem showed in this particular test since we cancel the frame sequence when the limit is reached. When we do that, reducer jobs don't run the filter, but immediately call `seq.done(cursor)`. I was able to reproduce the bug reliable with `taskset -c 0,2` to use two non-HT sibling cores. 500 …
=> fix(core): fix results returned in wrong order from parallel filter query

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java, core/src/main/java/io/questdb/cairo/sql/SqlExecutionCircuitBreakerConfiguration.java, core/src/main/java/io/questdb/griffin/DefaultSqlExecutionCircuitBreakerConfiguration.java, core/src/test/java/io/questdb/griffin/OrderByTimeoutTest.java
Attempt to reproduce https://github.com/questdb/questdb/issues/2829
No leaks detected
=> chore(sql): tests to make sure TableReader is not leaked in queries with ORDER by when time out happens

core/src/main/java/io/questdb/cairo/TableReader.java
fixes #2340
This was a frequently appearing issue in fuzz tests on CI. It was reproduced by adding `Os.sleep(10);` in reader reload code. The issue was to do with uncoordinated values in `columnCount` on `reader` and its `metadata`. Constructor would pick up old `columnCount` and then ask metadata to `reload` without updating `columnCount`.
=> fix(core): fix intermittent errors during table reads

core/src/main/java/io/questdb/cairo/TableReader.java, core/src/test/java/io/questdb/griffin/AlterTableDropPartitionTest.java
Fixes underlying reason for #2619 e.g. when reader is pooled and a partition is dropped TableReader does not correctly reload the partitions and produces `Partition 'XXX' does not exist in table 'test_table' directory`
=> fix(core): fix partition does not exist error after partition drop

core/src/main/java/io/questdb/cairo/sql/SqlExecutionCircuitBreaker.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/test/java/io/questdb/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/http/RetryIODispatcherTest.java, core/src/test/java/io/questdb/cutlass/http/SendAndReceiveRequestBuilder.java, core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
Fixes #2865
GET `/exp` endpoint wasn't resetting circuit breaker's timer.
=> fix(http): fix unexpected query timeout errors in /exp endpoint

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/griffin/InsertTest.java
Fix for indexing out of an array when `group by` is used with constant literals in `insert as select`.
Example for failing use case:
Trying to generate unique ids in insert statements by using the max() function.
```
create table currencies(ccy symbol, id long, ts timestamp) timestamp(ts);
insert into currencies values ('USD', 1, '2019-03-10T00:00:00.000000Z');
insert into currencies select 'EUR', max(id) + 1, '2019-03-10T01:00:00.000000Z' from currencies;
insert into currencies select 'GBP', max(id) + 1, '2019-03-10T02:00:00.000000Z' from currencies;
```
When running the above you get a failure on the 3rd line:
```
java.lang.AssertionError: index out of bounds, 1 >= 1
at io.questdb/io.questdb.std.ObjList.getQuick(ObjList.java:173)
at …
```
=> fix(sql): fix insert as select with group by expression and constant literals

core/src/main/java/io/questdb/Metrics.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DumpMemoryUsageFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/table/MemoryMetricsRecordCursorFactory.java, core/src/test/java/io/questdb/griffin/engine/table/MemoryMetricsRecordCursorFactoryTest.java
Adds Resident Set Size / Working Set Size to memory metrics list in : 
- /metrics endpoint 
- memory_metrics() & dump_memory_usage() functions 
It's not a 100% accurate metric but should be better than existing ones . 
There are differences between OSes though, for example Linux doesn't include MMAPed pages while Windows does (but only once they've been touched).
=> feat(core): add rss memory metric

ci/snapshot-pipeline.yml, ci/templates/hosted-cover-jobs.yml, ci/templates/self-hosted-jobs.yml
Fixes pipeline `snaphost-pipeline.yml` which is triggered on master commit to produce snapshot binaries.
Fixed run https://dev.azure.com/questdb/questdb/_build/results?buildId=13879&view=results
=> ci(build): fix snapshot pipeline

core/src/main/java/io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java, core/src/test/java/io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactoryTest.java
`WalTableListFunctionFactory` could be cached in QueryCache and reused.
Its state was not reset properly, adding a small fix.
=> chore(wal): make WalTableListFunctionFactory reusable

core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/cairo/wal/WalWriterEvents.java, core/src/test/java/io/questdb/griffin/wal/WalTableSqlTest.java
Truncate transaction in WAL-E to update the file size in the header.
Fixes #2925
=> chore(wal): fix truncate operation recording in WAL-E

core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpPartitionReadOnlyTest.java, core/src/test/java/io/questdb/cutlass/line/udp/LineUdpPartitionReadOnlyTest.java
```
2023-01-18T20:38:51.286550Z I i.q.c.TableReader open partition C:\Users\Vlad\AppData\Local\Temp\junit7611706806071924635\0e7e9312-4c08-4131-a7c2-2fd4667d336a\db\testTableIsReadOnlyTCP\2022-12-11 [rowCount=278, partitionNameTxn=-1, transientRowCount=278, partitionIndex=3, partitionCount=4]
2023-01-18T20:38:51.289596Z I i.q.c.l.t.PlainTcpLineChannel Send buffer size change from 65536 to 8192
2023-01-18T20:38:51.300230Z I tcp-line-server connected [ip=127.0.0.1, fd=2600]
2023-01-18T20:38:51.300879Z I i.q.c.p.AbstractMultiTenantPool closed 'testTableIsReadOnlyTCP' [at=0:0, reason=POOL_CLOSED]
2023-01-18T20:38:51.300978Z I i.q.c.p.AbstractMultiTenantPool open 'testTableIsReadOnlyTCP' [at=0:0]
2023-01-18T20:38:51.302760Z I i.q.g.SqlCompiler plan [q=`select-group-by min(ts) min, max(ts) max, …
```
=> chore(sql): fix broken test in line tcp/udp

core/src/main/java/io/questdb/cairo/pool/WalWriterPool.java, core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/cairo/wal/WalMetrics.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/resources/io/questdb/site/conf/log.conf
Also removes `wal_apply_rows_per_second` metric as it's trivial to configure Grafana to calculate it based on `wal_apply_written_rows`.
=> chore(core): add WAL writer metrics

core/src/main/java/io/questdb/Telemetry.java, core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/tasks/TelemetryTask.java, core/src/main/java/io/questdb/tasks/TelemetryWalTask.java, core/src/test/java/io/questdb/TelemetryTest.java, core/src/test/java/io/questdb/cairo/DefaultTestCairoConfiguration.java, core/src/test/java/io/questdb/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/cutlass/text/ParallelCsvFileImporterTest.java, core/src/test/java/io/questdb/griffin/CopyTest.java, core/src/test/java/io/questdb/griffin/wal/WalTelemetryTest.java
Fix bug introduced in #2930
Because of system table prefix is `sys.` the table name must be quoted. Without quotes `.` creates invalid syntax and server fails to start.
```
io.questdb.Bootstrap$BootstrapException: io.questdb.griffin.SqlException: [30] unexpected token: .
at io.questdb/io.questdb.ServerMain$1.configureSharedPool(ServerMain.java:149)
at io.questdb/io.questdb.WorkerPoolManager.<init>(WorkerPoolManager.java:48)
at io.questdb/io.questdb.ServerMain$1.<init>(ServerMain.java:93)
at io.questdb/io.questdb.ServerMain.<init>(ServerMain.java:93)
at io.questdb/io.questdb.ServerMain.<init>(ServerMain.java:69)
at io.questdb/io.questdb.ServerMain.<init>(ServerMain.java:65)
at io.questdb/io.questdb.ServerMain.main(ServerMain.java:214)
Caused by: io.questdb.griffin.SqlException: [30] …
```
=> fix(core): fix server start failure with sql syntax error in logs

core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/griffin/CompiledQuery.java, core/src/test/java/io/questdb/cutlass/http/HttpAlterTableTest.java
Add missing query executors for `table conversion` and `resume wal` in JsonQueryProcessor.
Fixes #2962
=> fix(wal): Table type conversion SQL was not processed via REST API

core/src/test/java/io/questdb/cutlass/line/tcp/LineTcpReceiverTest.java
If unlucky the ingestion could have finished earlier than the shutdown happened on the other thread.
Now the test ingests until shutdown happens eventually
=> chore(ilp): fix for race condition in ILP shutdown test

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
the optimized single-column happy path was overly optimistic about nested models. it was not assuming aliasing nor virtual tables.
fixes #2980
=> fix(sql): fix DISTINCT combined with a column alias

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
Similar to #2980  but fixes select distinct column with join .
Following queries : 
```sql
create table tab as (select x as id from long_sequence(3))
select distinct t1.id from  tab t1, tab t2;
select distinct t1.id 
from  tab t1 
join (select x as id from long_sequence(2)) t2 on (t1.id=t2.id);
```
trigger :
io.questdb.cairo.sql.InvalidColumnException
at io.questdb.cairo.sql.InvalidColumnException.<clinit>(InvalidColumnException.java:28)
at io.questdb.cairo.sql.RecordMetadata.getColumnIndex(RecordMetadata.java:60)
at io.questdb.griffin.SqlCodeGenerator.generateSelectDistinct(SqlCodeGenerator.java:3053)
at io.questdb.griffin.SqlCodeGenerator.generateSelect(SqlCodeGenerator.java:2684)
at io.questdb.griffin.SqlCodeGenerator.generateQuery0(SqlCodeGenerator.java:2287)
at …
=> fix(sql): fix error on select distinct with join

core/src/main/java/io/questdb/griffin/engine/join/LtJoinNoKeyRecordCursorFactory.java, core/src/test/java/io/questdb/griffin/AsOfJoinTest.java
The right side of a LT JOIN must have strictly smaller timestamps. Returning equal timestamps is a bug.
=> fix(sql): non-keyed LT JOIN could return equal timestamps

ci/templates/steps.yml
This is meant to deal with the "connection reset" problem when downloading artifacts from Maven Central.
Facts:
1. Builds are running in Azure Pipelines
2. Builds have the JDK HTTP pooling disabled via  -Dhttp.keepAlive=false
3. Builds are still frequently failing with "Connection Reset"
4. The errors happen right after running Core tests
Hypothesis:
1. Maven has its own connection pooling system as documented at https://issues.apache.org/jira/browse/WAGON-545 So even when JDK pooling is disabled there is still a pool on a higher level.
2. Azure infra kills idle TCP connections while tests are running
3. When Core tests are finished Maven starts building the Benchmark module. The Benchmark module uses a different Maven Clean plugin version -> Maven wants to download this version by using …
=> chore(build): Decrease Maven Wagon Connection Pool TTL

benchmarks/pom.xml, ci/templates/steps.yml, examples/pom.xml, utils/pom.xml
this PR attempts to fix constant connection reset errors. The battle plan:
- maven supposed to have 3 retries, we need to enable debug mode to see if it actually does retry we might need to increase retry count
- sync "clean" plugin versions between `benchmark` and `core`
- i logged an issue with maven central to see if they have genuine and hopefully temporary problems https://issues.sonatype.org/browse/MVNCENTRAL-7864
=> ci(core): fix connection reset

core/src/main/java/io/questdb/griffin/engine/table/LatestByAllFilteredRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValuesFilteredRecordCursor.java, core/src/test/java/io/questdb/griffin/LatestByTest.java
Fixes #3026  
Fixes symbol filter initialization order in query mentioned in isssue and : 
```sql
create table a ( i int, s symbol, ts timestamp ) timestamp(ts);
select s, i, ts 
from a 
where s in (select distinct s from a) 
and s = 'ABC' <-- fixed filter 
latest on ts partition by s;
```
=> fix(sql): fix symbol column initialization in latest by cursors

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/PropServerConfigurationTest.java, core/src/test/java/io/questdb/cutlass/text/CairoConfigurationWrapper.java, core/src/test/resources/server.conf
Ability to set size of the window, which is used by O3 automatic lag algo to maintain correct lag size. Before this lag window was hardcoded to have 4 entries, which may be insufficient for some ingestion data patterns.
The new option can be set via:
```
cairo.o3.lag.calculation.windows.size=128
```
=> feat(core): add external configuration for lag calculation window size

core/src/main/bin/questdb.sh
The current 2.5 seconds threshold is too small: many times I observed the database being `kill -9`'ed after, say, a TSBS run or a freshly executed CREATE TABLE AS SELECT.
=> chore(core): increase kill -9 threshold to 30 seconds in questdb.sh script

core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
Remove unnecessary critical error message from logs about `unsolicited table lock` when `ApplyWal2TableJob` races with engine releasing inactive writers.
=> fix(wal): remove unnecessary critical error about unsolicited table lock

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/engine/join/SpliceJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/model/JoinContext.java, core/src/test/java/io/questdb/griffin/ExplainPlanTest.java
Fixes #3010 
Even if order by is defined in outer query, order by in nested query should not be ignored if it's marked with explicit timestamp.
Timestamp(ts) is often used to make query pass validation of time-based joins (AsOf, Lt and Splice) so nested order by clause can't be removed. 
Example : 
```sql
CREATE TABLE gas_prices (timestamp TIMESTAMP, galon_price DOUBLE ) timestamp (timestamp);
with gp as 
(
select * from (
select * from gas_prices order by timestamp asc, galon_price desc
) timestamp(timestamp)
)
select * from gp gp1 
asof join gp gp2 
order by gp1.timestamp;
```
produces following plan in branch : 
```
SelectedRecord
AsOf Join
SelectedRecord
Sort light
keys: [timestamp, galon_price desc]
DataFrame
Row forward scan
Frame forward scan on: gas_prices
SelectedRecord
Sort …
```
=> fix(sql): fix order by removal in subquery with explicit timestamp

ci/test-fuzz.yml, core/src/test/java/io/questdb/griffin/wal/WalWriterFuzzTest.java
Run fuzz tests every 10 minutes in CI to increase coverage by running often with different random seeds.
https://dev.azure.com/questdb/questdb/_build?definitionId=25
=> ci(build): add continuous fuzz test run on master

core/src/main/java/io/questdb/cutlass/pgwire/CircuitBreakerRegistry.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
Move CircuitBreaker creation/destruction from registry back to PGConnectionContext to fix startup issue.
Worker pool allocates 4 contexts per thread on startup and that number could easily exceed connection limit if the number of workers is large .
=> chore(pgwire): fix circuit breaker registry

core/src/main/java/io/questdb/std/LongLongHashSet.java, core/src/test/java/io/questdb/test/std/LongLongHashSetTest.java
`size` wasn't incremented in `addAt()` method leading to an infinite loop when `probe()` is called. As a result, `count_distinct()` on UUID column could lead to a never-ending query.
=> fix(sql): fix infinite loop in count_distinct on UUID column

core/src/main/java/io/questdb/cutlass/text/types/TypeManager.java, core/src/test/java/io/questdb/test/cutlass/text/types/TypeManagerTest.java
I stumbled upon this certainly unintended fall-through behavior in a switch, introduced with #2769
=> fix(http): geo types should not fall-through to the UUID adapter

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/cairo/wal/WalTableWriterFuzzTest.java, core/src/test/java/io/questdb/test/griffin/AbstractO3Test.java, core/src/test/java/io/questdb/test/griffin/O3MaxLagFuzzTest.java, core/src/test/java/io/questdb/test/griffin/O3MaxLagTest.java, core/src/test/java/io/questdb/test/griffin/TruncateTest.java, core/src/test/java/io/questdb/test/std/AtomicIntListFuzzTest.java, core/src/test/java/io/questdb/test/wal/WalTxnDetailsFuzzTest.java
Fix the error when a non-partitioned table has a column deleted and then truncated.
```
java.lang.UnsupportedOperationException: null
at io.questdb.cairo.vm.api.NullMemory.getFd(NullMemory.java:82)
at io.questdb.cairo.vm.api.MemoryM.isOpen(MemoryM.java:57)
at io.questdb.cairo.TableWriter.truncate(TableWriter.java:2165)
at io.questdb.test.griffin.wal.fuzz.TruncateTableOperation.apply(TruncateTableOperation.java:33)
at io.questdb.test.griffin.O3MaxLagTest.replayTransactions(O3MaxLagTest.java:436)
at io.questdb.test.griffin.O3MaxLagTest.testFuzz00(O3MaxLagTest.java:514)
at io.questdb.test.griffin.O3MaxLagTest.testFuzz0(O3MaxLagTest.java:807)
```
Also, move fuzz (random number generated) test cases into classes with `Fuzz` in their name to be picked up for Fuzz test CI runs.
=> fix(core): fix non-partitioned table truncate error

core/src/main/java/io/questdb/cairo/AbstractIntervalDataFrameCursor.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java, core/src/test/java/io/questdb/test/griffin/LimitTest.java, core/src/test/java/io/questdb/test/griffin/OrderByWithAsyncFilterTest.java, core/src/test/java/io/questdb/test/griffin/OrderByWithIntervalFilterTest.java
Fixes #3163 
Also fixes:  
- bad result ( 0 )  for queries like : 
```sql
select count(*) from ( 
select sensor_time, temperature_out 
from weather_data 
where sensor_time <= dateadd( 's', rnd_int(0,1,0), to_timestamp('2022-08-01:00:00:00', 'yyyy-MM-dd:HH:mm:ss')) 
limit -5 )
```
- bad result or exceptions thrown during interval calculation
=> fix(sql): fix interval scan boundary calculation

core/src/main/java/io/questdb/Bootstrap.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java
The purpose of this change is to avoid critical level logs for non-critical `CairoException`s.
=> chore(http): unify error logging in JSON and text processors

core/Dockerfile
Hi!
The Dockerfile placed at "core/Dockerfile" contains the best practice violation [DL3015](https://github.com/hadolint/hadolint/wiki/DL3015) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3015 occurs when the apt tool is used to install packages without the "--no-install-recommends" flag. This flag is recommended to be used to avoid installing additional packages not explicitly requested.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, the "--no-install-recommends" flag is added to the apt-get install command.
This change is only aimed at fixing that specific smell. If the fix is not valid or useful, please …
=> chore(core): marginally reduce time it takes to build Docker imeage (DL3015)

core/src/test/java/io/questdb/test/griffin/wal/fuzz/FuzzTransactionGenerator.java
Prevent fuzz tests from generating rows with thousands of add/cancel row actions. 
Cancelling row can be an expensive operation and lead to test run timeout https://dev.azure.com/questdb/questdb/_build/results?buildId=19655&view=logs&j=85bc06a8-a627-555e-552b-b210a8c8389c&t=f747e3bf-47e7-5fc1-f444-dbfd34317c83
=> test(core): reduce the chances of fuzz test timing out

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/griffin/O3FailureTest.java
Initial atomic counter value set in the test was too high leading to occasional failures.
=> test(sql): fix flaky O3FailureTest.testOutOfFileHandles

core/src/main/java/io/questdb/griffin/BasePlanSink.java, core/src/main/java/io/questdb/griffin/PlanSink.java, core/src/main/java/io/questdb/griffin/model/RuntimeIntervalModel.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/KeyedAggregationTest.java, core/src/test/java/io/questdb/test/griffin/LatestByTest.java, core/src/test/java/io/questdb/test/griffin/LimitTest.java, core/src/test/java/io/questdb/test/griffin/OrderByWithFilterTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByFunctionCaseTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
Changes : 
- fix display for interval scans with dynamic intervals 
- show iso-formatted timestamps instead of raw long values
=> feat(sql): fix display of interval scans in EXPLAIN's output

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/vm/MemoryCMARWImpl.java, core/src/test/java/io/questdb/test/cairo/vm/ContinuousMemoryMTest.java, core/src/test/java/io/questdb/test/griffin/O3FailureTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
Fix rare SIGBUS which can happen after a transaction rollback on Linux.
When file is truncated it can be pad with 0 to the page size but if the file is already truncated via another file descriptor SIGBUS crash can happen on Linux.
To avoid, close active partition on rollbacks and also check file size before padding with 0 on truncate.
=> fix(core): fix rollback failure

core/src/test/java/io/questdb/test/tools/TestUtils.java, core/src/test/java/io/questdb/test/tools/TestUtilsTest.java
Prevents WAL writer fuzz tests from timing out due to O(n^2) comparison of rows with duplicate timestamps.
=> test(core): get rid of O(n^2) check in WAL writer fuzz tests

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/griffin/RecordToRowCopierUtils.java, core/src/main/java/io/questdb/griffin/SqlUtil.java, core/src/main/java/io/questdb/griffin/engine/functions/constants/Long256Constant.java, core/src/main/java/io/questdb/griffin/engine/functions/constants/Long256NullConstant.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/FunctionParserErrorTest.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerTest.java, core/src/test/java/io/questdb/test/griffin/SqlUtilTest.java
This is to allow the following:
```sql
create table long256 (long256 long256);
insert into long256 values
('0x6bbf0c833a5448baa23a0366d85079afc390e9837e67ac3f653076982d02dd3a'),
('0X6bbf0c833a5448baa23a0366d85079afc390e9837e67ac3f653076982d02dd3b'),
('6bbf0c833a5448baa23a0366d85079afc390e9837e67ac3f653076982d02dd3c');
```
from clients through for instance pgwire.
=> chore(core): allow implicit cast from str to long256

core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Improve PGJobContextTest.testCancelRunningQuery()  teststability by making update sql much more work-intensive .
=> test(pgwire): fix flaky pg test

core/src/test/java/io/questdb/test/griffin/O3FailureTest.java
Fix intermittent errors happening when OS reuses FD of closed file.
=> fix(build): fix O3FailureTest.testAllocateFailsAtO3OpenColumn

core/src/main/java/io/questdb/Bootstrap.java, core/src/main/java/io/questdb/BootstrapConfiguration.java, core/src/main/java/io/questdb/DefaultBootstrapConfiguration.java, core/src/main/java/io/questdb/DefaultFactoryProvider.java, core/src/main/java/io/questdb/FactoryProvider.java, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cutlass/auth/StaticPublicKeyRepoFactory.java, core/src/main/java/io/questdb/cutlass/line/tcp/DefaultLineTcpReceiverConfiguration.java, core/src/test/java/io/questdb/test/AbstractTest.java, core/src/test/java/io/questdb/test/TestServerConfiguration.java, core/src/test/java/io/questdb/test/cutlass/http/SendAndReceiveRequestBuilder.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/AbstractLineTcpReceiverTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/BaseLineTcpContextTest.java
It is now possible to use partial response matching in HTTP tests, which deals with cases where some error responses contain variable file names
=> test(core): send-receive test did not account for multi-byte characters, which causes flapping tests

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
Fixes 
_at least one aggregation function must be present in 'select' clause_
error triggered by bad rewrite of _limit -N_ clause . 
Example (using demo):
```sql
select  timestamp, count(*) as total 
from trades 
sample by 1s 
limit -10
```
=> fix(sql): fix bad rewrite of limit -N

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
partially reverting the change from https://github.com/questdb/questdb/pull/3080 
#3080 changed the reported version as a side-effect, but the new version was used in PropServerConfiguration only, DefaultPGWireConfiguration stays on 11.3 The result was that most tests reported the version 11.3 to clients while production QuestDB builds reported 15.2. Some Postgres clients adjust behaviour depending on the reported server version and using different version in tests and in production builds means we could not trust tests.
=> fix(pgwire): revert reported pg server version back to 11.3

core/src/main/java/io/questdb/cairo/BitmapIndexWriter.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/griffin/O3MaxLagTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java, utils/src/test/java/io/questdb/cliutil/TestUtils.java
After adding index testing to fuzz tests few issues were found and fixed
- WAL tables can miss a range of rows in the index. When rows were applied from lag, indexes were not incrementally built.
- Non-WAL tables can have duplicated index entries when a row cancel happens on the edge of a partition.
=> fix(core): fix index miss values or contain duplicates in certain commit patterns

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/resources/server.conf
This change is required to avoid having server restarts due to failed k8s liveness probes on machines with a few CPU cores. Having a dedicated thread to handle `GET /status` should guarantee the absence of false negative liveness probes.
=> chore(http): use dedicated thread for healthchecks and metrics by default

core/src/main/java/io/questdb/cairo/BitmapIndexWriter.java, core/src/main/java/io/questdb/cairo/O3CopyJob.java, core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
With some commit patterns found in tests, the symbol index could contain a duplicate reference to a row. This affects WAL and non-WAL tables.
=> fix(core): fix symbol index containing duplicates references

core/src/main/java/io/questdb/griffin/engine/join/HashOuterJoinFilteredLightRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/engine/join/HashJoinTest.java
Fixes #3289 
Fix unsafe TreeCursor.next() call without a prior TreeCursor.hasNext() that can lead to EXCEPTION_ACCESS_VIOLATION .
=> fix(sql): fix crash in hash outer join with filter factory

core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinLightRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/AsOfJoinTest.java
=> fix(sql): unhandled ArrayIndexOutOfBoundsException in ASOF and LT JOIN on empty table

core/src/main/java/io/questdb/cairo/MapWriter.java, core/src/main/java/io/questdb/cairo/SymbolMapWriter.java, core/src/main/java/io/questdb/cairo/vm/NullMapWriter.java, core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java, core/src/main/java/io/questdb/cutlass/text/types/TypeAdapter.java
Refs #3269
COPY was using default symbol table capacity for temporary tables. This led to sub-optimal ingestion performance due to slow symbol lookups. With this patch, temporary tables use the same symbol capacities as the end table.
Create a 100M test CSV file with this Golang program:
```go
package main
import (
"bufio"
"os"
"strconv"
"time"
)
func main() {
f, err := os.Create("/tmp/input.csv")
if err != nil {
panic(err)
}
defer f.Close()
_, err = f.WriteString("sym,ts\n")
if err != nil {
panic(err)
}
f.Sync()
w := bufio.NewWriter(f)
for i := 1; i <= 100_000_000; i++ {
t := time.UnixMicro(int64(i) * 1_000_000)
_, err := w.WriteString(strconv.Itoa(i%234870) + "," + t.Format("2006-01-02T15:04:05.000000Z") + "\n")
if err != nil {
panic(err)
}
}
w.Flush()
f.Sync()
}
```
Pre-create the …
=> fix(sql): fix COPY performance for pre-created tables with non-default symbol capacity

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cutlass/Services.java, core/src/main/java/io/questdb/cutlass/http/DefaultHttpContextConfiguration.java, core/src/main/java/io/questdb/cutlass/http/DefaultHttpServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpContextConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpMinServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/processors/HealthCheckProcessor.java, core/src/main/java/io/questdb/griffin/engine/functions/StrArrayFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/CurrentSchemasFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/StringToStringArrayFunction.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/cutlass/http/HealthCheckTest.java, core/src/test/java/io/questdb/test/cutlass/http/HttpHealthCheckTestBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/HttpServerConfigurationBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/StrArrayFunctionTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/CurrentSchemasFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/StringToStringArrayFunctionTest.java, core/src/test/resources/server.conf, pkg/ami/marketplace/assets/server.conf
Fixes #3288
Introduces `http.pessimistic.health.check.enabled` property (`false` by default) to configure health check endpoint pessimism. When enabled, the health check will return HTTP 500 if there were any unhandled errors since server start. This is a potentially breaking change as previously the behavior was always the same as with `http.pessimistic.health.check.enabled=true`.
Also, fixes `select current_schemas(true) from long_sequence(1)` query handling, so that it no longer leads to `UnsupportedOperationException`.
=> feat(http): introduce configuration for health check pessimism

core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessorState.java, core/src/test/java/io/questdb/test/cutlass/http/ImportIODispatcherTest.java
Fixes #2703
The format field wasn't properly initialized when the TCP connection was reused between subsequent POST `/imp` requests. As a result, the next request could receive a response in the wrong format.
=> fix(http): format query parameter ignored by /imp endpoint

core/src/main/java/io/questdb/cairo/wal/WalWriter.java
During a WAL segment roll-over we:
1. Start writing to a new segment.
2. Clean up the old segment.
In that order.
This PR is to ensure that we maintain the lock to the old segment until we're done cleaning it up.
This is necessary because cleaning up requires truncating files which makes modifications to the filesystem and thus still requires a lock.
=> fix(core): consistent segment rollover in WalWriter

core/pom.xml
This PR sets version of `@questdb/web-console` dependency to 0.2.0
It includes:
* New CSV Import view by @insmac https://github.com/questdb/ui/pull/130
* Update autocomplete in editor with:
* add keywords `snapshot`, `prepare`, `complete`, `squash`, `partitions`, `explain`
* add function `rnd_uuid4`
* add data type `uuid`
* fix typo `tables_columns` -> `table_columns`
=> feat(ui): bump web-console version to 0.2.0

core/src/main/java/io/questdb/mp/SOCountDownLatch.java, core/src/main/java/io/questdb/mp/SOUnboundedCountDownLatch.java, core/src/main/java/io/questdb/mp/SimpleWaitingLock.java, core/src/main/java/io/questdb/std/Os.java, core/src/test/java/io/questdb/test/mp/SOLatchTest.java, core/src/test/java/io/questdb/test/mp/SOUnboundedCountDownLatchTest.java
Fix the bug found in fuzz tests when threads suck in sorting data for many minutes and the test timeouts.
```
2023-05-13T00:32:01.6539765Z 'questdb-testing-154': WAITING
2023-05-13T00:32:01.6541095Z 		at java.base@11.0.19/jdk.internal.misc.Unsafe.park(Native Method)
2023-05-13T00:32:01.6542097Z 		at java.base@11.0.19/java.util.concurrent.locks.LockSupport.park(LockSupport.java:323)
2023-05-13T00:32:01.6545692Z 		at app//io.questdb.mp.SOUnboundedCountDownLatch.await(SOUnboundedCountDownLatch.java:47)
2023-05-13T00:32:01.6548125Z 		at app//io.questdb.cairo.TableWriter.dispatchO3CallbackQueue(TableWriter.java:3218)
2023-05-13T00:32:01.6549450Z 		at app//io.questdb.cairo.TableWriter.o3Sort(TableWriter.java:5047)
2023-05-13T00:32:01.6552080Z 		at …
```
=> fix(core): fix stuck ingestion

README.md
There was a mistake in the name of the column `timestamp` in the database query sample (Try QuestDB section). The name of this column was mistakenly written as `time`, which causes the query to fail with an error in the [demo database](https://demo.questdb.io/) website.
=> chore(docs): fix column name `timestamp` for `trades` table

core/src/main/java/io/questdb/cairo/BitmapIndexWriter.java, core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileIndexedFrameColumn.java, core/src/main/java/io/questdb/std/Files.java, core/src/main/java/io/questdb/std/LongList.java, core/src/test/java/io/questdb/test/cairo/BitmapIndexTest.java, core/src/test/java/io/questdb/test/griffin/O3FailureTest.java
Fixes error found in fuzz test. The problem occurs when an indexed column could have garbage left in the key file after the key file is re-created (truncated).
```
2023-05-15T13:02:07.9451609Z java.lang.AssertionError
2023-05-15T13:02:07.9451965Z 	at io.questdb.cairo.BitmapIndexWriter.add(BitmapIndexWriter.java:126)
2023-05-15T13:02:07.9452411Z 	at io.questdb.cairo.frm.file.ContiguousFileIndexedFrameColumn.append(ContiguousFileIndexedFrameColumn.java:59)
2023-05-15T13:02:07.9452854Z 	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:63)
2023-05-15T13:02:07.9453229Z 	at io.questdb.cairo.frm.FrameAlgebra.append(FrameAlgebra.java:37)
2023-05-15T13:02:07.9453628Z 	at io.questdb.cairo.TableWriter.squashSplitPartitions(TableWriter.java:6851)
2023-05-15T13:02:07.9454053Z 	at …
```
=> chore(core): fix error in partition squashing on indexed columns

core/pom.xml
Setting `@questdb/web-console` dependency to 0.2.1
Changes include:
- New feature in CSV Import: Allow editing schema on existing tables (column type, designated timestamp and its pattern, geohash precision) https://github.com/questdb/ui/pull/140
- Small visual updates for the schema editor UI in CSV Import, along with code refactoring for simplicity.
=> feat(ui): bump web-console version to 0.2.1

core/src/main/java/io/questdb/cairo/O3CopyJob.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/BaseLineTcpContextTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/BaseLineTcpInsertGeoHashTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/EllipticCurveAuthConnectionContextTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpConnectionContextBrokenUTF8Test.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpConnectionContextInvalidSymbolTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpConnectionContextTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpInsertOtherTypesTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpTypeConversionTest.java, core/src/test/java/io/questdb/test/griffin/AbstractO3Test.java, core/src/test/java/io/questdb/test/griffin/O3FailureTest.java
ILP jobs were in greedy mode never releasing thread unless socket is empty. This could lead to bad user experience on smaller instances where ILP jobs run from shared pool.
The fix is to re-queue socket after every measurement. There is no notable impact on performance.
In Summary:
- fix O3 test failure when `sync` is enabled
- fix O3 `commit()` hanging when `sync` fails
- fix graceful shutdown under heavy ingest load
- fix graceful shutdown after catastrophic disk failure
=> fix(core): allow server to perform graceful shutdown under heavy ILP load

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
UDP receiver might be a friction component on systems without multicast support. There it will prevent server from starting up with a cryptic message.
This is not a well used component.
=> feat(ilp): disable UDP receiver by default

core/src/main/java/io/questdb/cairo/TableWriter.java
The PR fixes the column version not set when the column is renamed. Specific to non-partitioned tables only.
Found by fuzz test runs.
```
io.questdb.griffin.SqlException: [0] [2]: could not open read-only [file=/tmp/junit1029390315418332203/dbRoot/y~/default/new_col_17.d.14]
at io.questdb.griffin.SqlException.position(SqlException.java:107)
at io.questdb.griffin.SqlOptimiser.openReaderAndEnumerateColumns(SqlOptimiser.java:2496)
at io.questdb.griffin.SqlOptimiser.enumerateTableColumns(SqlOptimiser.java:1770)
at io.questdb.griffin.SqlOptimiser.enumerateTableColumns(SqlOptimiser.java:1775)
at io.questdb.griffin.SqlOptimiser.optimise(SqlOptimiser.java:4646)
at io.questdb.griffin.SqlCompiler.compileExecutionModel0(SqlCompiler.java:1172)
at …
```
=> fix(core): fix column not found error after column rename

core/src/main/java/io/questdb/cairo/wal/WalWriter.java
Based on the report collected with https://github.com/RedHatPerf/type-pollution-agent:
```
--------------------------
Type Pollution:
--------------------------
1:	io.questdb.cairo.vm.MemoryPMARImpl
Count:	60851191
Types:
io.questdb.cairo.vm.api.MemoryA
io.questdb.cairo.vm.api.MemoryMA
Traces:
io.questdb.cairo.wal.WalWriter$RowImpl.getPrimaryColumn(WalWriter.java:1864)
class: io.questdb.cairo.vm.api.MemoryA
count: 30427173
io.questdb.cairo.wal.WalWriter.getPrimaryColumn(WalWriter.java:1023)
class: io.questdb.cairo.vm.api.MemoryMA
count: 30413843
io.questdb.cairo.TableWriter.getPrimaryColumn(TableWriter.java:3540)
class: io.questdb.cairo.vm.api.MemoryMA
count: 3990
io.questdb.cairo.TableWriter.closeAppendMemoryTruncate(TableWriter.java:2841)
class: io.questdb.cairo.vm.api.MemoryMA
count: …
```
=> chore(core): avoid type pollution in WalWriter

core/src/main/java/io/questdb/cairo/CairoEngine.java
To address test failure and to generally remove table reserved error which only makes sense on concurrent table create but does not make sense on reading or writing to the table.
```
2023-05-25T23:35:09.758329Z E i.q.t.c.l.t.LineTcpReceiverFuzzTest 
io.questdb.cairo.CairoException: [-1] table name is reserved [table=weather0]
at io.questdb.cairo.CairoException.critical(CairoException.java:62)
at io.questdb.cairo.CairoException.nonCritical(CairoException.java:114)
at io.questdb.cairo.CairoEngine.verifyTableName(CairoEngine.java:802)
at io.questdb.cairo.CairoEngine.getReader(CairoEngine.java:416)
at io.questdb.test.AbstractCairoTest.getReader(AbstractCairoTest.java:449)
at io.questdb.test.cutlass.line.tcp.AbstractLineTcpReceiverFuzzTest.checkTable(AbstractLineTcpReceiverFuzzTest.java:326) …
```
=> chore(core): replace table name reserved error with table does not exist in some cases

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
If the ILP message buffer size is smaller than the max measurement size, instead of throwing an exception the message buffer size should be adjusted to have enough space at least for a single measurement.
=> chore(ilp): adjust ILP msg buffer size to max measurement size if needed

core/src/main/java/io/questdb/griffin/FunctionFactory.java, core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/GroupByTest.java
=> fix(sql): fix NullPointerException in GROUP BY query with ORDER BY expression

core/src/main/bin/questdb.sh
To fix the bug mentiend in the issue [#3405](https://github.com/questdb/questdb/issues/3405#issue-1727198171). QuestDB would reach the max number of open files when requesting a bunch of tables simultaneously. However, modify the system level configuration does not work. I add some code in questdb.sh so that #max-open-files can be configured on MacOS.
=> fix(core): increase max open files limit on MacOS

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/JoinTest.java
Fixes #3383 
Fixes propagation of join columns into join models when join columns aren't used  in outer query.
=> fix(sql): fix join column propagation

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerTest.java
Fixes #3386
PR makes compiler reject non-boolean join filters, e.g. 
```sql
create table a ( ts timestamp, i int) timestamp(ts);
create table b ( ts timestamp, i int) timestamp(ts);
select * from a left join b on a.i - b.i;
select * from a join b on a.ts = b.ts and a.i - b.i;
```
Queries above now return `boolean expression expected` during compilation instead of `UnsupportedOperationException` during query execution.
=> fix(sql): improve error reporting on non-boolean join conditions

core/src/main/java/io/questdb/cairo/MapWriter.java, core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/vm/MemoryCMRImpl.java, core/src/main/java/io/questdb/cairo/vm/Vm.java, core/src/test/java/io/questdb/test/griffin/O3FailureTest.java
Fix WAL table writing bug which can lead to incorrect partition data truncation. This then manifests in the reading error similar to
```
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
```
The issue was that Table Writer did not advance column files truncate positions under certain circumstances before switching to the next partition while applying WAL. This results in the incorrect trimming of the partition and if the trimming difference is bigger than File page size it leads to read errors like the one listed above.
=> fix(core): fix incorrect truncation of WAL table partition leading to read errors

core/src/main/java/io/questdb/griffin/engine/functions/eq/EqStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/lt/LtCharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/lt/LtStrFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/lt/LtStrFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
Fixes #3454
Adds support for string comparison operator, so the following queries are now possible:
```sql
SELECT 'abc' < 'def'
FROM my_table
WHERE str_col_1 >= str_col_2;
```
=> feat(sql): add string comparison operator

core/src/main/java/io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java, core/src/test/java/io/questdb/test/cutlass/pgwire/BasePGTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
=> fix(pgwire): gracefully handle a client disconnecting during authentication

core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/test/java/io/questdb/test/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
Fixes #3489
Missing exception handling could lead to thread (and reader) leak due to an infinite loop in `PageFrameSequence#await()` (`dispatchStartFrameIndex` was assigned to `frameCount` in `dispatch()` and never got updated to the proper value).
=> fix(sql): fix thread and reader leak on invalid filter in WHERE clause

core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerAPI.java
The iterator of the map holds onto the last returned node, unless remove() is called.
=> fix(core): memory leak fix

core/src/main/java/io/questdb/griffin/engine/table/AbstractDeferredValueRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AbstractLatestByValueRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueDeferredIndexedFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueFilteredRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueIndexedFilteredRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/LatestByValueRecordCursor.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Fixes a number of latest by factories that cached and used the first bind variable value set.
Example:
```sql
CREATE TABLE IF NOT EXISTS tab (
ts timestamp, 
sym symbol, 
isym symbol,
h string,
type char,
stat char
), index(isym) timestamp(ts) partition by MONTH;
insert into tab values 
(0, 'S1', 'S1', 'h1', 'X', 'Y' ), 
(1, 'S2', 'S2', 'h2', 'X', 'Y' ), 
(3, null, null, 'h3', 'X', 'Y' );
select h, isym from 
(select h, stat, isym from tab 
where sym = ? and type = 'X' latest on ts partition by sym 
) where stat='Y';
```
Running the last query with "S1" and then "S2" bind variable value or null returns the following in master branch :
```sql
h   isym
h1    S1
```
=> fix(sql): fix latest by factories not reacting to bind variable value change

core/src/main/java/io/questdb/cairo/TableToken.java, core/src/main/java/io/questdb/std/str/DirectUtf8Sequence.java, core/src/main/java/io/questdb/std/str/GcUtf8String.java, core/src/main/java/io/questdb/std/str/Utf8s.java, core/src/test/java/io/questdb/test/std/str/GcUtf8StringTest.java, core/src/test/java/io/questdb/test/std/str/Utf8sTest.java
Aligned naming of Utf8 types with the naming scheme we use in the rest of the code base.
=> refactor(core): rename Utf8Native to DirectUtf8Sequence

core/src/main/java/io/questdb/log/LogAlertSocketWriter.java, core/src/test/java/io/questdb/test/log/LogAlertSocketWriterTest.java
Fixes #3518 
Fixes LogAlertSocketWriter trying to extract data from mutable StringSink that is used as both message template  and a buffer 
and thus producing an endless stream of exceptions.
=> fix(sql): fix constant StringIndexOutOfBoundsException in alert socket writer

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/DenyAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/main/java/io/questdb/cairo/sql/async/PageFrameSequence.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredNegativeLimitRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java, core/src/test/java/io/questdb/test/griffin/AsyncOffloadTest.java
Introduces separate permission checks for ILP in `SecurityContext`: create table, add column, insert.
Also includes the following:
* Fix incomplete exception and timeout handling in `AsyncFilteredNegativeLimitRecordCursor`.
* Use error level for errors logged by `AsyncFilteredRecordCursor` and `AsyncFilteredNegativeLimitRecordCursor`. That's to prevent false positive critical level logging in the case of `ImplicitCastException` and similar non-critical ones.
=> chore(core): introduce separate set of permissions for ILP

core/src/main/java/io/questdb/griffin/engine/functions/uuid/LongsToUuidFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/UuidTest.java
This PR introduces a new SQL function: `to_uuid(long, long)`. The function creates a UUID value out of 2 long values. 
Each long value has 64 bits. UUID values have 128 bits. The function combines bits from both longs to construct a UUID. The first long is interpreted as the lower 64 bits and the 2nd long is used as higher 64 bits of the resulting UUID value. 
Trivial example:
```sql
select to_uuid(2, 1) as uuid from long_sequence(1);
```
Expected result:
```
uuid
00000000-0000-0001-0000-000000000002
```
Less trivial example:
```sql
create table x (lo long, hi long);
insert into x values (2, 1);
select to_uuid(lo, hi) as uuid from x;
```
Expected result:
```
uuid
00000000-0000-0001-0000-000000000002
```
Expected use-case: Construct a unique ID out of 2 IDs received from different sources.
=> feat(sql): implement function to convert two longs to UUID

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/AlterWalTableLineTcpReceiverTest.java
Fuzz test that drops column concurrently with ILP ingestion found a problem. It is a race condition in ILP, which can lead to data loss. More specifically, column name is double-cached in ILP, once for UTF8 and second time UTF16. These maps can diverge and column index begins to return negative column types that ILP doesn't know what to do with.
To help the review, i replaced "if" clause inside loop that is trying to determine if column has be added, with "switch" statement. It was not clear that there are three branches. I feel "switch" makes it easier to understand what's going on. I also renamed `columnIndex` to `columnWriterIndex` which is what this variable is.
Log is below:
```
2023-07-13T08:34:28.5574001Z 2023-07-13T08:34:26.075837Z E i.q.c.l.t.LineTcpMeasurementScheduler could not …
```
=> fix(ilp): fix data loss causes by concurrent column drop transactions

core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cutlass/auth/EllipticCurveAuthenticatorFactory.java, core/src/test/java/io/questdb/test/AbstractBootstrapTest.java, core/src/test/java/io/questdb/test/ConcurrentTcpSenderBootstrapTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/AbstractLineTcpReceiverTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/BaseLineTcpContextTest.java
Previously, there could be multiple threads sharing the same buffer inside StaticChallengeResponseMatcher. This could lead to signature being mangled and thus valid user could be refused to connect. This bug could not be abused to get access without having a valid key.
This fix will create a StaticChallengeResponseMatcher instance for each EllipticCurveAuthenticator instance.
=> fix(ilp): fix race condition in ILP authentication

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerTest.java
Fixes #3595 
Fixes 'Invalid column' error occurring for columns in non-equality join condition when join order is different from that in query .
=> fix(sql): fix Invalid Column error with multiple JOIN

core/src/main/java/io/questdb/griffin/FunctionParser.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerTest.java
Fixes #3576 
e.g. 
```sql
select 'ab'>'a'
```
Also fixes function matching for expressions that use bind variables or non-constant arguments, e.g. 
```sql
select ? > 'a'
select rnd_str('be', 'cd') < 'd'
```
that used to expect both char arguments and fail for strings longer than 1 character .
=> fix(sql): fix string and char comparison

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
Fix write error when dedup is enabled and commit results in moving all rows to lag.
Improve dedup fuzz tests to have more Timestamp collisions.
=> chore(core): fix write error with dedup enabled

README.md, i18n/README.ar-dz.md, i18n/README.es-es.md, i18n/README.it-it.md, i18n/README.ja-ja.md, i18n/README.pt.md, i18n/README.ua-ua.md, i18n/README.zh-cn.md, i18n/README.zh-hk.md
All but one of the current translated READMEs used a fully-qualified URL to a PNG image that no longer exists. This fixes the image srcs to point to the equivalent image.
Curiously, some translations describe their TSDB image in the way that corresponds to the English README, but many others refer to a different benchmark using a `Ryzen 3970X`. I have for the time being amended any translation that uses that exact phrase to use the latter benchmark image, although I'm unsure where it came from.
=> fix(ui): Fix broken image link in translated READMEs

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/WalTableListFunctionFactory.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/test/AbstractCairoTest.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/cairo/CairoTestConfiguration.java, core/src/test/java/io/questdb/test/cairo/ConfigurationOverrides.java, core/src/test/java/io/questdb/test/cairo/Overrides.java, core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java, core/src/test/java/io/questdb/test/cutlass/text/CairoConfigurationWrapper.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/WalTableListFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java, core/src/test/resources/server.conf, pkg/ami/marketplace/assets/server.conf
Previously, it could happen that the O3 lag, i.e. the invisible part of a WAL table, was growing almost unbounded. This patch ensures that we force a full commit each `cairo.wal.max.lag.txn.count` transactions (by default, set to 20). This makes sure that the data periodically becomes visible to table readers.
Also, adds `writerLagTxnCount` column to `wal_tables()` pseudo-table to allow monitoring transaction count in the table's lag.
An example of the described scenario may be seen in the below screenshot.
=> fix(core): avoid unbounded growth of transactions in O3 lag of WAL tables

core/src/main/java/io/questdb/griffin/model/IntervalUtils.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java, core/src/test/java/io/questdb/test/griffin/model/IntervalUtilsTest.java
Attempt to make QuestDB compatible with Grafana alerting. 
related to https://github.com/grafana/grafana/issues/51611
=> fix(sql): truncate nanos in textual timestamps

core/src/main/java/io/questdb/mp/SimpleWaitingLock.java
The problem with the old code. Imagine this scenario:
1. The lock is available
2. Thread1 and Thread2 are competing to acquire it
3. Thread1 set itself as a waiter
4. Thread2 overwrites it and set itself as a waiter!
5. Both threads see the `lock.get()` as `false`
6. Thread2 wins the `getAndSet()` race and returns
7. Thread1 will park
8. Threads2 releases the lock and unpark ... itself
9. Thread1 will be stuck until the `Os.park();` timeouts!
This change also simplifies reasoning:
1. It reduces concurrent state updates to just a single reference.
2. `lock()` is just `tryLock()` with a very long timeout
=> chore(core): SimpleWaitingLock liveness improvements and simplification

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/wal/MetadataService.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/java/io/questdb/cairo/wal/seq/MetadataServiceStub.java, core/src/main/java/io/questdb/client/Sender.java, core/src/main/java/io/questdb/cutlass/http/processors/TextImportProcessor.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java, core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java, core/src/main/java/io/questdb/cutlass/text/TextLoader.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java, core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
Fixes #3480
By default, the POST `/imp` REST API endpoint doesn't issue intermediate commits. This PR makes sure that we initialize `maxUncommittedRows` and `o3MaxLag` parameters of the `CairoTextWriter` with the table's defaults, so that `writer.ic()` calls are made during the import. As a result, the O3 memory won't be unboundedly growing when importing O3 data and chances to run OOM become much smaller.
Also improves timestamp unit description in `Sender`'s Javadoc
=> fix(http): avoid running out of memory when importing partitioned table over REST API

core/src/main/java/io/questdb/griffin/engine/functions/cast/CastIPv4ToStrFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/IPv4Test.java
Fixes issue from  https://github.com/questdb/questdb/pull/3523 in which explicitly casting an IPv4 constant to a string returned an incorrect value (the `int` representation of IPv4).
Previous behaviour: 
```sql
select '235.11.98.4'::ipv4::string -> -351575548
``` 
Current behaviour:
```sql
select '235.11.98.4'::ipv4::string -> 235.11.98.4
```
=> fix(sql): fix explicit const ipv4 to string cast bug

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastIPv4ToStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TypeOfFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/CaseCommon.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/CoalesceFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/TypeOfFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CoalesceFunctionFactoryTest.java
Fixes #3622 
Also fixes : 
- `select typeOf(ipv4_expression)`
- implicit cast between string and ipv4 types
=> fix(sql): fix implicit type casting in coalesce() function

core/src/main/java/io/questdb/cairo/DedupColumnCommitAddresses.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/main/java/io/questdb/griffin/SqlKeywords.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TableListFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/CreateTableDedupTest.java, core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
Both syntax variants are made valid
```
ALTER table abc DEDUP ENABLE UPSERT KEYS(a, b);
ALTER table abc DEDUP UPSERT KEYS(a, b);
```
Also fixed a bug where table was not shows as dedup enabled in `tables()` query when the timestamp index is 0.
=> fix(sql): fix alter table dedup enable syntax

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/DynamicTableReaderMetadata.java, core/src/main/java/io/questdb/cairo/TableReaderMetadata.java, core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/cairo/pool/MetadataPool.java, core/src/main/java/io/questdb/cairo/sql/TableMetadata.java, core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java, core/src/test/java/io/questdb/test/cairo/TableMetadataTest.java, core/src/test/java/io/questdb/test/cutlass/http/HttpAlterTableTest.java, core/src/test/java/io/questdb/test/cutlass/http/ImportIODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java, core/src/test/java/io/questdb/test/griffin/O3MaxLagTest.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
REST `imp` endpoint was not updated to write to WAL tables using WAL infrastructure. This PR makes the writing to behave as expected. Also fixes #3632
=> fix(http): make HTTP text import for WAL tables to write via WAL

core/src/main/java/io/questdb/griffin/engine/functions/eq/EqIPv4FunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/lt/LtIPv4FunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/IPv4Test.java
Adds these operators missing from https://github.com/questdb/questdb/pull/3523:
- `<` **Less than**
- Return value: `boolean`
- Takes two IPv4 arguments
- Use case: testing to see if one IP address is less than another
- Example
``` sql
select ipv4 '33.1.8.43' < ipv4 '200.6.38.9' -> T
``` 
- `>` **Greater than**
- Return value: `boolean`
- Takes two IPv4 arguments
- Use case: testing to see if one IP address is greater than another
- Example
``` sql
select ipv4 '33.1.8.43' > ipv4 '200.6.38.9' -> F
``` 
- `<=` **Less than or equal**
- Return value: `boolean`
- Takes two IPv4 arguments
- Use case: testing to see if one IP address is less than or equal to another
- Example
``` sql
select ipv4 '33.1.8.43' <= ipv4 '33.1.8.43' -> T
``` 
- `>=` **Greater than or equal**
- Return value: `boolean` …
=> feat(core): add more operators ipv4 operators + alter eq ipv4

utils/src/main/java/io/questdb/misc/SqlGrammarUtil.java
Simply run the main method from within the IDE and, for each category (functions, keywords, types), find the relevant appropriatedly named ts file, and wack the entries, to be then replaced with the ones produced by the tool
=> chore(sql): add simple tool to produce content for repo sql-grammar ts files

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/engine/union/ExceptAllCastRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/union/ExceptAllRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/union/ExceptAllRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/union/ExceptCastRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/union/ExceptRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/union/IntersectAllCastRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/union/IntersectAllRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/union/IntersectAllRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/union/IntersectCastRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/union/IntersectRecordCursor.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGQuerySuspendabilityTest.java, core/src/test/java/io/questdb/test/griffin/ExceptTest.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/IPv4Test.java, core/src/test/java/io/questdb/test/griffin/IntersectTest.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
Fixes #3580
This is a breaking change: the behavior of the old INTERSECT/EXCEPT was the same as the newly added INTERSECT ALL/EXCEPT ALL, i.e. they were not removing duplicate rows. Now they do.
So, if previously
```sql
(SELECT 1 UNION ALL SELECT 1) EXCEPT (SELECT 0);
```
would return `[(1,),(1,)]`, now it returns `[(1,)]`.
=> feat(sql): add support for INTERSECT ALL/EXCEPT ALL statements

core/src/main/java/io/questdb/cairo/wal/DefaultWalListener.java, core/src/main/java/io/questdb/cairo/wal/WalListener.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerAPI.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java, core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLog.java, core/src/test/java/io/questdb/test/cairo/wal/WalListenerTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
- Introduce `tableCreated` notification.
- Persist table creation timestamp in the transaction log header (backward-compatible modification).
- Align segmentClose signature with others, incorporating txn and ~~timestamp~~ arguments.
=> chore(wal): unify WalListener API

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
fixes #3661
The ORDER BY advice cannot be pushed down through SAMPLE BY, because SAMPLE BY requires designated timestamps to be sorted by their natural (ascending) order.
=> fix(sql): fix SAMPLE BY queries with ORDER BY timestamp DESC

core/src/main/java/io/questdb/cutlass/text/TextDelimiterScanner.java
Depending on data shape of inboud TEXT files the heuristic for detecting column delimiter could malfunction and pick wrong delimiter. This was caused by abnormally high double tolerance value when comparing stddev of each delimiter candites.
=> fix(http): improve detection of flat file delimiter

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/groupby/VirtualFunctionSkewedSymbolRecordCursor.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
Fixes #3750 
Fixes: 
- bug in group by cursor size re-caculation where cursor.size() method relied on element that wasn't cleared on close() method call 
- bug in handling of group by with empty aggregate list that caused it to skip processing data, e.g. `select id from users group by id`
-
=> fix(sql): fix empty result on second run of query with group by and limit

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/LineTcpBootstrapTest.java
The disconnectOnError flag was not respected for WAL tables.
=> fix(ilp): ILP disconnects on error with WAL tables

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/wal/seq/SeqTxnTracker.java, core/src/test/java/io/questdb/test/cairo/wal/seq/SeqTxnTrackerTest.java
The simplest way to reproduce this bug was to ingest to the same table concurrently from multiple ILP connections.
=> fix(core): fix race leading to occasionally frozen WAL transaction processing on some tables

.all-contributorsrc, ci/validate-pr-title/validate.js
Remove trailing slash to ensure valid JSON syntax.
This file is used as the payload for our internal API, which is later used to build questdb.io website.
`.all-contributorsrc` is expected to be a JSON file, however, a single trailing comma broke it.
Due to this, the result of the internal API was `server error` and thus some data in questdb.io website was not populated.
Namely, the contributors count on questdb.io/about-us does not show a number.
This PR fixes the issue.
=> docs(core): Fix syntax in all-contributorsrc file

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java, core/src/main/java/io/questdb/cutlass/line/tcp/TableUpdateDetails.java, core/src/main/java/io/questdb/cutlass/text/CairoTextWriter.java, core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/InsertOperationImpl.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGSecurityTest.java, core/src/test/java/io/questdb/test/griffin/SecurityTest.java
- move INSERT permission to table level
- use INSERT permission instead of COPY
- remove ILP specific permissions and use their counterparts (INSERT, CREATE TABLE, ADD COLUMN) instead
required by https://github.com/questdb/questdb-enterprise/pull/172
=> chore(core): table level insert permission

benchmarks/src/main/java/org/questdb/PongMain.java, core/src/main/java/io/questdb/Metrics.java, core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryMetrics.java, core/src/main/java/io/questdb/cutlass/line/LineMetrics.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGWireMetrics.java, core/src/main/java/io/questdb/network/IOContext.java, core/src/test/java/io/questdb/test/cutlass/IODispatcherHeartbeatTest.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Refs: #2794
Adds the following gauges for Prometheus metrics:
```
questdb_http_connections
questdb_pg_wire_connections
questdb_line_tcp_connections
```
=> feat(core): add connection count gauge metrics for all network interfaces

core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java, core/src/test/java/io/questdb/test/griffin/WhereClauseParserTest.java
Fixes parsing of NOT IN expression where first argument is not a column but an expression. 
Example : 
```sql
CREATE TABLE tab ( timestamp TIMESTAMP, col STRING, id SYMBOL INDEX) TIMESTAMP(timestamp);
INSERT INTO tab VALUES (1, 'foo', 'A'), (2, 'bah', 'B'), (3, 'dee', 'C')");
SELECT * FROM tab
WHERE substring(col, 1, 3) NOT IN ('foo', 'bah')
```
Query fails with 'column expected' in current master.
=> fix(sql): fix NOT IN expression parsing with function arguments

ci/qlog.conf, core/src/main/java/io/questdb/log/GuaranteedLogger.java, core/src/main/java/io/questdb/log/LogFactory.java
PR enables switching guaranteed logging for all messages issued by selected classes, via entry in log.conf . 
For the time being it's used to fix issues with acl query logging tests . 
Required by https://github.com/questdb/questdb-enterprise/pull/177 .
=> chore(core): add configurable per-class guaranteed logging

core/src/main/java/io/questdb/cutlass/line/tcp/auth/EllipticCurveAuthenticator.java
do not give up a thread after fully reading keyId
reasoning: we just finished reading `keyId` and we are scheduled on a thread. there is no need to give up on the thread and wait to be scheduled again. we can opportunistically try to send the challenge immediately. given the challenge is only 513 bytes there is a good chance it will fit into a socket in one go. this should improve authentication responsiveness in very busy systems - where it can take a while for an IOContext to be scheduled again.
=> fix(ilp): faster ILP authentication

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/UpdateTest.java
SQL UPDATE treats table names as case sensitive.
This bug originates from validateUpdateColumns throwing TableReferenceOutOfDateException whenver the UPDATE name case does not strictly match the table name. Changing the evaluation function from Chars.equals to Chars.equalsIgnoreCase fixed the problem.
Also added new test to ensure UPDATE is table-name case insensitive.
This closes #3656
=> fix(sql): fix table name case sensitivity in SQL UPDATE

benchmarks/src/main/java/org/questdb/LineTCPSenderMain.java, core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/test/java/io/questdb/test/griffin/AlterTableRenameColumnTest.java
Fix TableReader reload error after a series column renames found by fuzz tests.
The symptom is the error:
```
Caused by: io.questdb.griffin.SqlException: [0] [2]: could not open read-only [file=/var/folders/kj/wpw2cl295rbdksb3ysqsj1yw0000gn/T/junit12416700228706723530/dbRoot/db/testFuzzWithSnapshot_2~7/new_col_0.k]
at io.questdb@7.3.3-SNAPSHOT/io.questdb.griffin.SqlException.position(SqlException.java:103)
at io.questdb@7.3.3-SNAPSHOT/io.questdb.griffin.SqlOptimiser.openReaderAndEnumerateColumns(SqlOptimiser.java:2523)
at io.questdb@7.3.3-SNAPSHOT/io.questdb.griffin.SqlOptimiser.enumerateTableColumns(SqlOptimiser.java:1772)
at io.questdb@7.3.3-SNAPSHOT/io.questdb.griffin.SqlOptimiser.enumerateTableColumns(SqlOptimiser.java:1777)
at …
```
=> fix(core): fix transient select error after symbol column rename sequence

core/docker-entrypoint.sh
This closes [#3814 ]
With this fix, the ParallelGC would be added as a part of the JVM args if no args passed via configuration file.
=> fix(core): use the same GC algorithm in Docker image as with other QuestDB distros

core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
Fixes #3771 
PR improves cleanup of  WhereClauseParser's internal state on change of key column.
=> fix(sql): fix parsing of indexed symbol predicates in where clause

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/griffin/engine/table/VirtualRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
Fixes #3783 
PR Improves  order by advice propagation mismatch with limit lo advice, sometimes causing nested subquery to apply bad scan order and limit and return bad result . 
Example :
```sql
CREATE TABLE device_data 
( 
timestamp TIMESTAMP, 
val DOUBLE, 
id SYMBOL 
) TIMESTAMP(timestamp);
EXPLAIN 
SELECT timestamp AS date, val, val + 1 
FROM device_data 
WHERE device_data.id = '12345678' 
ORDER BY timestamp DESC 
LIMIT 1;
```
In master it produces the following plan : 
```
Sort light lo: 1
keys: [date desc]
VirtualRecord
functions: [date,val,val+1]
SelectedRecord
Async JIT Filter workers: 1 
limit: 1   
filter: id='12345678'
DataFrame
Row forward scan
Frame forward scan on: device_data
```
while correct plan is : 
```
Limit lo: 1
VirtualRecord
functions: [date,val,val+1] …
```
=> fix(sql): improve order by clause propagation

core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java, core/src/main/java/io/questdb/cutlass/line/tcp/PlainTcpLineChannel.java, core/src/main/java/io/questdb/log/LogAlertSocket.java, core/src/main/java/io/questdb/network/AbstractIODispatcher.java, core/src/main/java/io/questdb/network/Net.java, core/src/main/java/io/questdb/network/NetworkFacade.java, core/src/main/java/io/questdb/network/NetworkFacadeImpl.java
MacOS TCP/IP stack sometimes stops listening on a server socket when we set KeepAlive. To avoid that we configure KeepAlive on server sockets only after `accept()`, never on `serverFd`.
=> fix(core): fix connection error to HTTP TCP port on MacOS

core/src/main/java/io/questdb/cutlass/http/processors/PrometheusMetricsProcessor.java, core/src/test/java/io/questdb/test/cutlass/http/HttpMinTestBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/HttpServerConfigurationBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/MetricsIODispatcherTest.java
The PrometheusMetricsProcessor wasn't handling resumes after `PeerIsSlowToReadException`.
There is still a theoretical problem when metrics do not fit into the application http buffer, but given the buffer size is 2MB by default the metrics fit in practice.
=> fix(http): prometheus exporter occasionally fails to send all metrics

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContext.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java
rework PG-specific user enabled check.
instead of returning a boolean and throw exception, just throw the exception inside the check.
this makes it possible to reuse some code, and also to add the right entity name to the error message when user assumes a service account and the user gets disabled.
required by https://github.com/questdb/questdb-enterprise/pull/183
=> chore(core): PG-specific user enabled check

core/src/main/java/io/questdb/griffin/JsonPlanSink.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/JsonPlanSinkTest.java
Fixes https://github.com/questdb/questdb/issues/3721
Fixes https://github.com/questdb/questdb/issues/3720: Apparently, #3804 was processed faster than this PR, so this has been fixed
When ending a JSON explain tag, previously, both a `"` and `,` were inserted.
`,` should never be necessary in this context, because the whole JSON is being finished up.
`"` is only necessary if the type is a string (counterexample: int)
Also fixes a more general and widespread bug where a numerical value would be encased in `"`, if a string-type value has been inserted before that in the JSON document (excluding the node type)
=> fix(sql): ensure EXPLAIN (FORMAT JSON) returns valid JSON 

core/src/main/java/io/questdb/griffin/engine/functions/bool/InLongFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java, core/src/test/java/io/questdb/test/log/LogAlertSocketTest.java
Fixes `UnsupportedOperationException` when running 
```SQL
CREATE table abc (a int, b short) 
insert into abc values(1, 2)
select * from abc where a in (1, 2)
```
=> fix(sql): fix sql error [col in (1,2)] when col is type short

core/src/test/java/io/questdb/test/log/MockAlertTarget.java
This tests is failing often, I noticed all failed runs run almost exactly 5 seconds, which happens to be the old timeout.
This is from one of the failure log:
```
2023-10-26T08:22:59.7428640Z 2023-10-26T08:22:59.727683Z I i.q.t.TestListener >>>> io.questdb.test.log.LogAlertSocketTest.testFailOverSingleHost
2023-10-26T08:23:04.8725310Z 2023-10-26T08:23:04.735514Z E i.q.t.l.MockAlertTarget
2023-10-26T08:23:04.8786480Z java.net.SocketTimeoutException: Accept timed out
2023-10-26T08:23:04.9378960Z 	at java.net.PlainSocketImpl.socketAccept(Native Method)
2023-10-26T08:23:04.9395110Z 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
2023-10-26T08:23:04.9398350Z 	at java.net.ServerSocket.implAccept(ServerSocket.java:565)
2023-10-26T08:23:04.9400790Z 	at …
```
=> test(http): increase Socket timeout in MockAlertTarget

core/src/main/java/io/questdb/mp/SOCountDownLatch.java, core/src/test/java/io/questdb/test/mp/SOCountDownLatchTest.java
I cannot think of a user-friendly title, it's a basic infra.
=> chore(core): countDownLatch respects timeout in the presence of spurious wakeups

core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencer.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerAPI.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java
If the sequencer file can be updated externally, Apply WAL job can have errors 
```
could not apply structure change from WAL to table. WAL metadata change does not exist [structureVersion=1], errno=0
```
The fix is for Apply WAL job to always open fresh cursor from files without trying to optimise comparing the searched meta version with the sequencer meta version.
=> chore(core): fix reload race WAL Apply when sequencer files are updated externally

core/src/main/java/io/questdb/griffin/engine/functions/lt/LtStrFunctionFactory.java, core/src/main/java/io/questdb/jit/CompiledFilterIRSerializer.java, core/src/test/java/io/questdb/test/griffin/CompiledFilterTest.java, core/src/test/java/io/questdb/test/jit/CompiledFilterIRSerializerTest.java
Fixes #3828 
PR rejects <, <=, >, >= operator serialization with symbol arguments because they require string value comparison and JIT doesn't handle string types yet.
=> fix(sql): fix symbol value comparison with <, <=, >, >= operators

core/src/main/java/io/questdb/griffin/engine/functions/math/RemIntFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/math/RemIntFunctionFactoryTest.java
Fixes #3849 
PR fixes modulo ( remainder )  operator to return null when one argument is null or divisor is 0 . 
Examples:
```sql
select null % 1;
select 1 % null;
select null % null;
select 1 % 0 ;
```
All of the above return now `null`.
=> fix(sql): fix modulo int operator result with nulls

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
Fixes #3733 
PR fixes propagation of non-equality join condition columns .
Example:
```sql
create table test (event int, created timestamp);
SELECT count(*)
FROM test as T1
JOIN ( SELECT * FROM test ) as T2 ON T1.event < T2.event
JOIN test as T3 ON T2.created = T3.created;
```
returns `invalid column T2.event` error because T2.event is pushed to top-most T2 only model.
=> fix(sql): fix 'Invalid column' column error for columns used in non-equality join conditions

core/src/main/java/io/questdb/griffin/engine/functions/math/AddIntFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
Fixes #3840 
PR improves performance integer addition expression involving many non-constant elements, e.g.
```sql
select x + x + ... + x 
from tab;
```
or 
```sql
select rnd_int() + rnd_int() + ...
```
Issue was caused by AddIntFunctionFactory's recursively checking whether arguments are constant and not caching partial result .
=> fix(sql): fix server hang on evaluating large integer addition expression

core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/griffin/engine/functions/metadata/AbstrtactEnvVariableValueFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/metadata/InstanceNameFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/metadata/InstanceRGBFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/AbstractCairoTest.java, core/src/test/java/io/questdb/test/cairo/CairoTestConfiguration.java, core/src/test/java/io/questdb/test/cairo/ConfigurationOverrides.java, core/src/test/java/io/questdb/test/cairo/Overrides.java, core/src/test/java/io/questdb/test/griffin/MetadataFunctionTest.java
added two functions:
```sql
select instance_name
```
This function returns value of the env variable `QDB_INSTANCE_NAME`
```sql
select instance_rgb
```
This function returns instance "color", it should be one of the 3 letters, `R`, `G` or `B`. Value is read from env variable `QDB_INSTANCE_RGB`
Web console should have 3 different color schemes for each of the "colors". All colors should be shows "inverted", e.g. white text on red background
=> feat(sql): sql functions to support traffic light widget in the Web Console

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/window/WindowRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionTest.java
PR adds missing metadata to window sub-query/factory to fix e.g.  
```sql
select * from 
(
select *, avg(t1.price) over(partition by t1.symbol rows between 50 preceding and current row) mavg 
from trades t1
)
lt join trades  t2
```
returning 'left side of time series join has no timestamp' error .
=> fix(sql): maintain timestamp metadata in window factories

core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/test/java/io/questdb/test/cairo/CreateTableTest.java
Fixes #3961 
The dedup flags were not being copied to the CreateTable model.
=> fix(sql): fix create table like with dedup

core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIPv4GroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIntGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctLongGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctStringGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java, core/src/main/java/io/questdb/std/AbstractIntHashSet.java, core/src/main/java/io/questdb/std/AbstractLongHashSet.java, core/src/main/java/io/questdb/std/CompactCharSequenceHashSet.java, core/src/main/java/io/questdb/std/CompactIntHashSet.java, core/src/main/java/io/questdb/std/CompactLongHashSet.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctIntGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctLongGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/std/CompactCharSequenceHashSetTest.java
Considering that biased locking was removed from OpenJDK, `StringBuffer` became noticeably more expensive than before. On my machine, this change cut down the `regexp_replace` query in ClickBench by ~20 seconds.
Also includes the following changes:
* Fixes no entry values in integer `Compact*HashSet` used in `count_distinct()` functions. The default value was -1 which led to incorrect results
* `CompactCharSequenceHashSet` no longer inherits from `AbstractCharSequenceHashSet`. That's to be able to use `String[]` array to store the keys and use `String#hashCode()` (which is cached) when comparing keys
=> perf(sql): use StringBuilder instead of StringBuffer when possible in regexp_replace

core/src/main/bin/questdb.sh
fixes #3996
Reasoning: QuestDB no-jre fails to start on MacOS. Because it's trying to create /usr/local/var/questdb which it cannot do without sudo. When installed via brew the DBRoot is created during the installation process and set explicitly.
I assume there is the same problem with the no-jre version on FreeBSD.
=> fix(build): create dbroot directory inside user home on MacOS

core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
fixes #3180
reasoning: if the query is completed before the cancelling thread is scheduled for execution then the test fails. this can happen on under-powered boxes (e.g. Windows CI) where a scheduler has to shuffle a lot of tasks. this changeset makes the queries slower thus the cancelling thread has a higher chance to cancel the query.
=> test(pgwire): fix a flaky pgwire cancellation test

core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/cutlass/http/SendAndReceiveRequestBuilder.java
`testShowParameters()` to print missing/extra properties only.
When the entire diff is printed, it is almost impossible to identify the missing/extra rows just by looking at the diff.
Also fixes https://github.com/questdb/questdb/issues/3825 by increasing default timeout in `SendAndReceiveRequestBuilder`.
=> chore(core): testShowParameters() to print missing/extra properties only

core/src/main/java/io/questdb/griffin/SqlKeywords.java
I did some code optimization in the `SqlKeywords` class.
I know, this kind of optimization could be seen controversial, and I'm keen to get your feedback.
I did two things, which slightly sacrifice the readability - I hope it's still OK.
* refactor using short-circuit evaluation in SqlKeywords only
* refactor using a constant as array-index instead of a variable 
Both approaches together lead to a 12.4% smaller (compiled) .class file size. And also, the local variable is removed.
Looking at the compiled .class file, I believe the JIT will more often inline these functions (because smaller and technically simpler code) and the resulting assembly code will be somewhat smaller. 
That said, I also think the overall performance gain is very small, as local variables easily are buffered by the …
=> perf(sql): micro optimizations SqlKeywords implementation (short-circuit evaluation, inline variable)

core/src/main/java/io/questdb/griffin/engine/functions/groupby/AbstractCovarGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/AbstractRegressionGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/AbstractStdDevGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CorrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CorrGroupByFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CovarPopGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CovarPopGroupByFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CovarSampleGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CovarSampleGroupByFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CorrGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CovarPopGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CovarSampleGroupByFunctionFactoryTest.java
Closes #3826
Resolves https://github.com/questdb/roadmap/issues/55
Model after Postgres: ```covar_samp()```, ```covar_pop()```, ```corr()```
=> feat(sql): add covariance and corr built-in functions

core/src/main/java/io/questdb/cairo/sql/TableMetadata.java, core/src/test/java/io/questdb/test/fuzz/FuzzTransactionGenerator.java, core/src/test/java/io/questdb/test/griffin/O3MaxLagFuzzTest.java, core/src/test/java/io/questdb/test/griffin/wal/AbstractFuzzTest.java, core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java, core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java
Follow-up for #4014
With this change, col tops columns are included in the fuzzed transactions. Previously it wasn't the case as those columns weren't in the end table when the fuzzer was generating transactions.
=> test(core): improve FuzzRunner

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizePartiallySortedLightRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/OrderByWithFilterTest.java
Fixes #4022 
If base cursor (subquery) is already sorted on designated timestamp then 
```sql 
ORDER BY  designated_timestamp, col1, ..., colN 
LIMIT N
```
can stop traversing base cursor when enough different timestamps have been found, e.g. 
N records with timestamp T0 and 1 record with T1 . 
Hot runs of:
```sql
SELECT SearchPhrase FROM hits WHERE SearchPhrase IS NOT NULL ORDER BY EventTime, SearchPhrase LIMIT 10;
```
take (on my desktop):  
master) 450 ms  
this pr) 22 ms
=> perf(sql): optimize order by designated timestamp and other columns with limit

core/src/main/java/io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CaseFunctionFactoryTest.java
This could happen when a single letter string literal was recognized as a CharConstant and the switch function would call `getSymbol()` on it.
I see no good reason for differentiation between getString() and getSymbol() in the switch factory. As both work with CharSequence anyway.
=> fix(sql): fix edge case internal error in case-switch expression

core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java, core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
Fixes fuzz test failure happened in CI when table drop step is performed. This locks the table to drop but Fuzz test infrastructure does not handle the locked exception well.
```
2023-11-29T20:07:39.793525Z E i.q.t.TestListener ***** Test Failed *****io.questdb.test.griffin.wal.WalWriterFuzzTest.testWalWriteFullRandom[NO_MIXED_IO] duration_ms=2378 : 
java.lang.RuntimeException: io.questdb.cairo.pool.ex.EntryLockedException: [-1] table busy [reason=unknown]
at io.questdb.test.griffin.wal.FuzzRunner.applyManyWalParallel(FuzzRunner.java:180)
at io.questdb.test.griffin.wal.FuzzRunner.applyWalParallel(FuzzRunner.java:434)
at io.questdb.test.griffin.wal.FuzzRunner.runFuzz(FuzzRunner.java:787)
...
Caused by: io.questdb.cairo.pool.ex.EntryLockedException: [-1] table busy [reason=unknown]
at …
```
=> test(core): fix fuzz tests to handle table dropping

core/src/main/bin/questdb.sh
Fixes #3981 
In this PR, I've modified questdb.sh file to set JVM flags using environment variables.  Please let me know if anything has to be changed in code.
Appreciate if you can review.
Thanks!
=> feat(core): add support for configurable JVM flags using environment variables

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/map/FastMap.java, core/src/main/java/io/questdb/std/MemoryTag.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/resources/server.conf, pkg/ami/marketplace/assets/server.conf
Before:
```
Benchmark                          Mode  Cnt  Score   Error  Units
FastMapWriteBenchmark.testFastMap  avgt    3  0.367 ± 0.017  us/op
```
After:
```
Benchmark                          Mode  Cnt  Score   Error  Units
FastMapWriteBenchmark.testFastMap  avgt    3  0.347 ± 0.004  us/op
```
=> perf(sql): get rid of offset packing in FastMap

core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
=> fix(sql): fix column propagation for queries with set operations and distinct

core/src/main/java/io/questdb/griffin/engine/functions/catalogue/Constants.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/CurrentSettingFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/InformationSchemaTablesFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/PgExtensionFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/PrefixedPgExtensionFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/QuoteIdentFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/FirstValueDoubleWindowFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/CurrentSettingFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/InformationSchemaTablesFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/PgExtensionFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/QuoteIdentFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionTest.java
PR improves compatibility with metadata sql issued by grafana's query builder and code editor by adding : 
- quote_ident() function 
- information_schema.tables 
- pg_extension stub 
- current_setting() function stub 
PR also fixes a bug in first_value() function not working with non-caching Window Factory and `over (partition by x)` clause variant. 
Related grafana PR -> https://github.com/grafana/grafana/pull/79066
=> fix(sql): improve compatibility with grafana

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java
Fixes bad parsing of single characters used as window frame boundaries, e.g. 
```sql
create table tab ( key int, value double, ts timestamp) timestamp(ts);
explain select avg(value) over (PARTITION BY key ORDER BY ts RANGE BETWEEN '1' MINUTES PRECEDING AND CURRENT ROW) from tab;
--in master 
Window
functions: [avg(value) over (partition by [key] range between 2940000000 preceding and current row)]
DataFrame
Row forward scan
Frame forward scan on: tab
--this branch
Window
functions: [avg(value) over (partition by [key] range between 60000000 preceding and current row)]
DataFrame
Row forward scan
Frame forward scan on: tab
```
The issue was that single character was converted to long as ascii code - 49.
=> fix(sql): fix parsing of single character window frame bounds

core/src/main/java/io/questdb/griffin/engine/functions/math/SignByteFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/SignDoubleFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/SignFloatFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/SignIntFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/SignLongFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/math/SignShortFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/engine/functions/math/SignFunctionFactoryTest.java
PR adds sign() function for argument of byte, short, int, long, float and double data type.
Example:
```sql
create table tab ( d double );
insert into tab values (0.0), (-0.0), 
(2.2250738585072014E-308), (1.0), (1.7976931348623157E308), ('Infinity'::double), 
(-2.2250738585072014E-308), (-1.0), (-1.7976931348623157E308), ('-Infinity'::double),
(null);
select d, sign(d) from tab;
--returns 
sign | d
-- | --
0 | 0
0 | 0
1 | 0.22250738585072E-307
1 | 1
1 | 1.7976931348623157E+308
1 | Infinity
-1 | -0.22250738585072E-307
-1 | -1
-1 | -1.7976931348623157E+308
-1 | -Infinity
null | null
```
=> feat(sql): add sign() functions

core/src/main/java/io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/SwitchFunctionFactoryTest.java
PR makes it possible to use 'simple' case  expression with a list of float or double values, e.g .
```sql
select case value when 1.0f  then 'blue' else 'red' end 
from 
( 
select 1f value from long_sequence(1)
)
select case value when 1.0d  then 'blue' else 'red' end 
from 
( 
select 1d value from long_sequence(1)
)
```
In current master the above queries return 
`type FLOAT is not supported in 'switch' type of 'case' statement` and 
`type DOUBLE is not supported in 'switch' type of 'case' statement`
errors .
=> fix(sql): implement 'case expression when value' for float and double data types

core/src/main/java/io/questdb/cairo/SecurityContext.java, core/src/main/java/io/questdb/cairo/security/AllowAllSecurityContextFactory.java, core/src/main/java/io/questdb/cairo/security/ReadOnlySecurityContextFactory.java, core/src/main/java/io/questdb/cairo/security/SecurityContextFactory.java, core/src/main/java/io/questdb/cutlass/auth/Authenticator.java, core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/ReadOnlyUsersAwareSecurityContextFactory.java
Separate the handling of endpoint permission and user enabled checks from authentication, and run the checks for every request.
required by https://github.com/questdb/questdb-enterprise/pull/307
=> chore(core): user enabled and endpoint permission checks on every query

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yml
Request identity when bug or feature are reported as well as more precise details about QuestDB configuration.
Inspired by https://github.com/duckdb/duckdb/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml
=> docs(build): change github issue templates

core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java, core/src/main/java/io/questdb/cutlass/http/processors/LineHttpProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/LineHttpProcessorState.java, core/src/test/java/io/questdb/test/cutlass/http/HttpSecurityTest.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/http/TestHttpClient.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpFailureTests.java
- small fixes for ILP over HTTP, such as using the right security context, returning the right HTTP response code
- HttpClient to support token auth, and proper handling of 204 response code
=> fix(ilp): ilp@http small fixes

core/src/main/c/share/util.h, core/src/main/java/io/questdb/cairo/BinarySearch.java, core/src/main/java/io/questdb/griffin/model/IntervalUtils.java, core/src/main/java/io/questdb/std/DoubleList.java, core/src/main/java/io/questdb/std/IntList.java, core/src/main/java/io/questdb/std/LongList.java
```
mid = (low + high) / 2;
^^^^^^^^^^^^
|
potential integer overflow
```
Fix :
```
diff = high - low;
mid = low + diff / 2;
```
fixes #4087
=> fix(core): fix potential and unlikely numeric overlflow that could lead to incorrect query results

core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/main/java/io/questdb/griffin/engine/RegisteredRecordCursorFactory.java
Required by https://github.com/questdb/questdb-enterprise/pull/320
PR pushes RegisteredRecordCursorFactory creation into overloaded method so that outermost factory is the one checking permissions .
=> chore(sql): fix query registry with acl issues

core/src/main/java/io/questdb/cairo/map/FastMap.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/ParallelGroupByTest.java
Also fixes broken check in `FastMap#setKeyCapacity()` (this change wasn't released yet).
=> fix(sql): fix potential races when regexp_replace function is used in where or group by clause

ci/ami-market-pipeline.yml, pkg/ami/marketplace/Makefile
Previous CI error: 
My guess is that underlying container image has a updated packer version that does not bundle the plugins on install
=> chore(build): add aws packer plugin for AMI deployment

core/src/main/java/io/questdb/griffin/engine/RegisteredRecordCursorFactory.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Fixes issue with queries that fail on cursor initialization leaving entry in query registry.
Fixes #4112
=> fix(sql): unregister query on cursor initialization failure

core/src/main/java/io/questdb/cairo/ColumnVersionWriter.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java, core/src/test/java/io/questdb/test/griffin/TruncateTest.java
=> fix(core): fix non-partition table truncate not working correctly alter table add column

core/src/main/java/io/questdb/cairo/ColumnPurgeJob.java, core/src/main/java/io/questdb/cairo/ColumnPurgeOperator.java, core/src/main/java/io/questdb/tasks/ColumnPurgeTask.java, core/src/test/java/io/questdb/test/griffin/ColumnPurgeJobTest.java
Some fuzz tests in CI were stuck because logging exceptions did not return the logging sequence.
=> fix(core): fix database stuck on startup after some table drops

core/src/main/java/io/questdb/cairo/wal/WalTxnDetails.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java
Related to #4154
TODO will be fixed as part of #4160
Removes unstable WAL cancellation test, #4151 will not be needed
=> fix(core): fix wal resume exception after table suspended because of an error

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/resources/io/questdb/site/conf/server.conf, pkg/ami/marketplace/assets/server.conf
tandem https://github.com/questdb/questdb-enterprise/pull/353
=> feat(conf): add new configuration settings to server.conf (including Enterprise settings)

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/DefaultHttpContextConfiguration.java, core/src/main/java/io/questdb/cutlass/http/DefaultHttpServerConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/HttpContextConfiguration.java, core/src/main/java/io/questdb/cutlass/http/HttpResponseSink.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorConfiguration.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/std/StationaryNanosClock.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/TestServerConfiguration.java, core/src/test/java/io/questdb/test/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/HttpServerConfigurationBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Changes in this PR:
- measure latency caused by authentication, it is displayed in Web Console
- add 302 (Temporarily Moved) to the list of allowed HTTP status codes, used for redirects
required by https://github.com/questdb/questdb-enterprise/pull/365
=> chore(core): add authentication to timings

.github/workflows/rebuild_native_libs.yml
the `macos-14` runner uses MacOS@ARM and is free of charge for OSS projects as explained at https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> chore(build): use a free runner to build MacOS ARM binaries

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
Changed lineTcpWriterWorkerCount to default to 0 instead of 1. This field is used to dedicate threads for ILP ingestion for non-WAL tables. This will increase default eligibility for AsyncGroupBy optimisation for 4 vCPUs.
Increase minimum shared.worker.count to 4, up from 2. This increases eligibility for AsyncGroupBy optimisation for small instances <4 vCPUs.
Updated testAllDefaults() to account for new default value.
Added test for shared workers to guarantee a minimum of 4.
Changed cpuSpare to allocate one core from 16-31 cores (previously 8-15 cores) and 2 cores from 32+ cores.
Note:
This is a modification to prior default behaviour. By default, one core will no longer be dedicated to ILP for non-partitioned tables.
Without modifications to the config, this means that …
=> fix(sql): enable parallel group-by on servers with fewer than 4 cores

core/src/main/java/io/questdb/cairo/SymbolMapUtil.java, core/src/main/java/io/questdb/std/Files.java, core/src/test/java/io/questdb/test/griffin/wal/SnapshotFuzzTest.java
Some volatile files like `_meta.swp` caused coping directories to abort the copy files to snapshots in the test because of an error. The fix is for the test to ignore such errors on copying files.
The PR is also fixing a bug in `Files.rmdir()` implementation.
=> test(core): fix snapshot fuzz test

core/src/main/java/io/questdb/griffin/engine/table/DeferredSymbolIndexRowCursorFactory.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Symbol key was not correctly initialized in `DeferredSymbolIndexRowCursorFactory` in case of non-existing symbols.
```sql
CREATE TABLE 'one_min' (
ticker SYMBOL capacity 256 CACHE index capacity 256,
open INT,
high INT,
low INT,
close INT,
time TIMESTAMP
) TIMESTAMP (time) PARTITION BY YEAR WAL;
INSERT INTO one_min VALUES ('x', 1, 1, 1, 1, now());
```
Then `SELECT * FROM one_min WHERE ticker = ?;` query can be run for `x` and `foobar` (non-exiting) symbol values. The second execution would wrongly return results for the `x` symbol.
=> fix(sql): fix non-existing symbol bind variable initialization in indexed filter queries

core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByNotKeyedRecordCursor.java, core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
Queries like the following one had a chance of returning incorrect results in the case when some of the worker threads (or machine's cores) are loaded:
```sql
SELECT sum(long_col) FROM tab;
```
In that case, some of the worker threads may not participate in the aggregation leading to the
```java
if (destValue.isNew()) {
destValue.copy(srcValue);
}
```
branch in `AsyncGroupByNotKeyedRecordCursor`. The branch wasn't updating the new flag of `destValue`, hence some of the partial results may get ignored.
=> fix(sql): potential incorrect results in non-keyed parallel GROUP BY query

core/src/main/java/io/questdb/cairo/DatabaseSnapshotAgentImpl.java
Found by fuzz test. 
```
2024-02-18T05:28:05.862406Z I i.q.c.DatabaseSnapshotAgentImpl recovered _txn file [src=/tmp/junit10201576134088118831/dbRoot/snapshot/db/testSnapshotFullFuzz~2/_txn, dst=/tmp/junit10201576134088118831/dbRoot/testSnapshotFullFuzz~2/_txn]
2024-02-18T05:28:05.862441Z I i.q.c.DatabaseSnapshotAgentImpl recovered _cv file [src=/tmp/junit10201576134088118831/dbRoot/snapshot/db/testSnapshotFullFuzz~2/_cv, dst=/tmp/junit10201576134088118831/dbRoot/testSnapshotFullFuzz~2/_cv]
2024-02-18T05:28:05.862558Z I i.q.c.DatabaseSnapshotAgentImpl rebuilding symbol files [table=/tmp/junit10201576134088118831/dbRoot/testSnapshotFullFuzz~2, column=c2, count=0]
2024-02-18T05:28:05.863398Z I i.q.c.DatabaseSnapshotAgentImpl rebuilding symbol files …
```
=> test(core): fix edge case of snapshot restore failure when data copied under heavy ddl load

core/src/main/java/io/questdb/cairo/map/Map.java, core/src/main/java/io/questdb/cairo/map/MapFactory.java, core/src/main/java/io/questdb/cairo/map/OrderedMap.java, core/src/main/java/io/questdb/cairo/map/Unordered16Map.java, core/src/main/java/io/questdb/cairo/map/Unordered2Map.java, core/src/main/java/io/questdb/cairo/map/Unordered4Map.java, core/src/main/java/io/questdb/cairo/map/Unordered8Map.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/main/java/io/questdb/std/Hash.java, core/src/main/java/io/questdb/std/Vect.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/test/griffin/GroupByTest.java, pkg/ami/marketplace/assets/server.conf
`MapFactory#createUnorderedMap()` wasn't considering the size of the value correctly when deciding which map to create. This may have led to increased memory usage when running GROUP BY queries.
Other than that, fixes a few typos in comments and improves naming.
=> fix(sql): fix incorrect unordered map creation check

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/griffin/CreateTableDedupTest.java
Fixes a bug so that adding/removing an index on a symbol column removes the column from deduplication keys list.
=> fix(sql): fix altering table to add index can remove dedup key

core/src/main/java/io/questdb/cairo/DatabaseSnapshotAgentImpl.java, core/src/main/java/io/questdb/client/Sender.java, core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java, core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java, core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/MockHttpProcessor.java
This patch introduces a new configuration option for the ILP@HTTP client: minimal request throughput. 
It enables the configuration of the HTTP request timeout to scale with request size. The feature calculates a dynamic timeout based on request size and adds this to the base timeout. This functionality is useful for occasionally sending large batches over slow links, where adding a large static timeout would be impractical.
This ensures the Java client remains in sync with other clients that also support this functionality.
=> chore(ilp): implement min request throughput in Java ILP Sender

core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLogV2.java, core/src/main/java/io/questdb/std/str/Path.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
fixes #4283
Problem is reproducible by running `testDetachPartitionsColumnTops` in a loop on MacOS
=> test(core): fix SIGABRT in mac CI runs

core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Quick fix which does not impact OSS, only enterprise, hence it is a chore.
1. `CairoConfigurationWrapper.getSampleByDefaultAlignmentCalendar()` has a hard-coded `return true`, changed it to call the delegate. Also changed `PropServerConfigurationTest` to exercise the wrapper too, so these type of bugs will be caught in the future.
2. SqlParserTest has a table with field name `service` , which is good for OSS, but in enterprise that is a keyword (`service account`), and needs quotes around it.
=> chore(core): sample by config fix

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/ServerMainTest.java, pkg/ami/marketplace/assets/server.conf
ILP/TCP has 256 as the default max conn limit. For ILP/HTTP it's set to 64 by default which may be too low considering that REST API connections also count for the limit.
=> chore(http): increase HTTP max connections limit to 256

pkg/ami/marketplace/assets/systemd.service
Fix order of options. Until now, all the -XX options were ignored, because they were passed as parameters to the main class.
The example at https://questdb.io/docs/deployment/systemd/#example-questdbservice need the same fix.
=> fix(core): fix ignored JVM arguments in AMI

core/src/main/java/io/questdb/client/impl/ConfStringParser.java, core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java, core/src/test/java/io/questdb/test/client/impl/ConfStringParserTest.java
this makes it consistent with other clients
=> chore(ilp): configuration string schema is case sensitive

core/src/main/java/io/questdb/cairo/RecordSinkFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/ILikeVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/LikeVarcharFunctionFactory.java, core/src/main/java/io/questdb/std/Chars.java, core/src/main/java/io/questdb/std/str/Utf8s.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/cairo/RecordSinkFactoryTest.java, core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CaseFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/regex/ILikeFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/regex/LikeFunctionFactoryTest.java, core/src/test/java/io/questdb/test/std/str/CharsTest.java, core/src/test/java/io/questdb/test/std/str/Utf8sTest.java
Also, includes the following:
* Fix varchar calls generated by RecordSinkFactory
* Add LIKE/ILIKE support for varchar
Local clickbench runs:
```sql
-- varchar column
-- 2.11s
SELECT COUNT(*) FROM hits WHERE URL LIKE '%google%';
-- string column
-- 5.36s
SELECT COUNT(*) FROM hits WHERE URL2 LIKE '%google%';
```
=> fix(sql): fix ILIKE for upper case non-ASCII patterns

core/src/main/java/io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ConcatFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/LowerVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/QuoteIdentFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/SizePrettyFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/SubStringFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/SubStringVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ToLowercaseFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ToLowercaseVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ToUppercaseFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ToUppercaseVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/UpperVarcharFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/LowerVarcharFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/SubStringVarcharFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/UpperVarcharFunctionFactoryTest.java
Queries with filters like `UPPER(str_col) LIKE '%FOOBAR%'` returned incorrect results when present in parallel filter or GROUP BY.
The list of affected SQL functions:
* upper/to_uppercase
* lower/to_lowercase
* substring
* base64
* quote_ident
* size_pretty
* concat
=> fix(sql): fix incorrect results returned when executing lower/upper/substring functions in parallel

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Fixes https://github.com/questdb/questdb/issues/4350
=> fix(sql): SAMPLE BY not to mix multiplication asterisk with wildcard column

core/src/test/java/io/questdb/test/log/LogFactoryTest.java
After running our test suite, I'd usually get a dangling empty file `core/io`. I tracked it down to the test that created it, but sometimes failed to delete it. Instead of the `io` file, we now use the same temp file that other tests use.
=> chore(core): use the managed temp file in LogFactoryTest

core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLogV2.java, core/src/test/java/io/questdb/test/wal/TableTransactionLogFuzzTest.java
Having a cleanup thread static code in `TableTransactionLogV2` can lead to dead lock in logging threads on a failed startup.
This PR removes thread static cleanup code.
=> chore(core): reduce thread static cleanup

core/src/main/java/io/questdb/cairo/BinaryTypeDriver.java, core/src/main/java/io/questdb/cairo/ColumnTypeDriver.java, core/src/main/java/io/questdb/cairo/O3OpenColumnJob.java, core/src/main/java/io/questdb/cairo/StringTypeDriver.java, core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java, core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/test/java/io/questdb/test/cairo/VarcharTypeDriverTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java
```
#
#
#
#
#
#
---------------  S U M M A R Y ------------
Command Line: -ea -Dfile.encoding=UTF-8 /home/vsts/work/1/s/core/target/surefire/surefirebooter6109048573964084745.jar /home/vsts/work/1/s/core/target/surefire/surefire11576409589169175072tmp /home/vsts/work/1/s/core/target/surefire/surefire_07837652167085883151tmp
Host: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz, 2 cores, 6G, Ubuntu 22.04.4 LTS
Time: Mon Apr  1 01:58:41 2024 UTC elapsed time: 374.041564 seconds (0d 0h 6m 14s)
---------------  T H R E A D  ---------------
Current thread (0x00007f09d83d2800):  JavaThread "Thread-705" daemon [_thread_in_native, id=3258, stack(0x00007f09c8bfd000,0x00007f09c8cfd000)]
Stack: [0x00007f09c8bfd000,0x00007f09c8cfd000],  sp=0x00007f09c8cfaed8,  free space=1015k
Native frames: (J=compiled …
```
=> chore(core): fix WAL append crash for varchar column

core/src/main/java/io/questdb/cairo/pool/AbstractMultiTenantPool.java, core/src/main/java/io/questdb/cairo/pool/ReaderPool.java, core/src/test/java/io/questdb/test/cairo/pool/ReaderPoolTest.java
```
024-04-04T20:37:39.1253070Z 2024-04-04T20:37:38.901214Z I i.q.t.AbstractTest Starting test ReaderPoolTest#testGetAndCloseRace^M
2024-04-04T20:37:39.1253900Z 2024-04-04T20:37:38.902602Z I i.q.c.TableNameRegistryStore reloading tables file [path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/junit8640915225145085674/dbRoot/tables.d.0, threadId=1318]^M
2024-04-04T20:37:39.1254730Z io.questdb.cairo.CairoException: [0] double close [table=xyz~, index=0]^M
2024-04-04T20:37:39.1255180Z <->at io.questdb.cairo.CairoException.instance(CairoException.java:310)^M
2024-04-04T20:37:39.1255640Z <->at io.questdb.cairo.CairoException.critical(CairoException.java:69)^M
2024-04-04T20:37:39.1256120Z <->at io.questdb.cairo.pool.AbstractMultiTenantPool.returnToPool(AbstractMultiTenantPool.java:387)^M …
```
=> chore(core): fix flapping test

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
Just started reading `QuestDB` code (purely for fun) and find out that manual implementation of SQL parser looks pretty fragile. Turned out that following query parsed with syntax error:
```
$> SELECT -5 BETWEEN -10 AND -1
too few arguments for 'between' [found=2,expected=3]
```
This PR fixes parser for this case (the fix is simple: one branch type were missed for unary `-` and `~` signs).
Also have off-topic question: why to implement sql parser manually and not to use some parser generators which can derive AST parser from grammar definition?
=> fix(sql): bug for negative upper bound (second argument) in BETWEEN operator

core/src/main/java/io/questdb/client/Sender.java, core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java, core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderMockServerTest.java
Without this change it is only possible to disable both interval and row-based flushes via auto_flush=off. It's also possible to set auto_flush_interval or auto_flush_rows to a 'very large value' but that's not very elegant.
This PR allows
- `auto_flush_interval=off` - disables interval-based auto-flushing, but keeps row-based flushed enabled. 
- `auto_flush_rows=off` - disables row-based flushes, but keeps interval-based flushes intact
The idea is copied from the Python client
=> feat(ilp): Sender config string can disable individual flush types separately

benchmarks/src/main/java/org/questdb/CsvLexerBenchmark.java, benchmarks/src/main/java/org/questdb/CsvTextLexerBenchmark.java, benchmarks/src/main/java/org/questdb/CutlassLexerTest.java, benchmarks/src/main/java/org/questdb/LineTcpParserBenchmark.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpParser.java, core/src/main/java/io/questdb/cutlass/text/AbstractTextLexer.java, core/src/main/java/io/questdb/cutlass/text/CopyTask.java, core/src/main/java/io/questdb/cutlass/text/CsvFileIndexer.java, core/src/main/java/io/questdb/cutlass/text/GenericTextLexer.java, core/src/main/java/io/questdb/cutlass/text/ParallelCsvFileImporter.java, core/src/main/java/io/questdb/std/SwarUtils.java, core/src/test/java/io/questdb/test/cutlass/text/ParallelCsvFileImporterTest.java, core/src/test/java/io/questdb/test/std/SwarUtilsTest.java
Results for SQL COPY in clickbench (optimized schema with varchar), c6a.metal:
Before:
```
2024-04-05T17:00:05.272708Z I i.q.c.t.ParallelCsvFileImporter import complete [importId=085572760f310fd8, file=`/home/ubuntu/ClickBench/questdb/hits.csv`', time=153s]
```
After:
```
2024-04-05T19:33:29.855367Z I i.q.c.t.ParallelCsvFileImporter import complete [importId=6678835cfb20a947, file=`/home/ubuntu/ClickBench/questdb/hits.csv`', time=127s]
```
Before:
```
2024-04-05T16:57:31.915697Z I i.q.c.t.ParallelCsvFileImporter finished [importId=085572760f310fd8, phase=analyze_file_structure, file=`/home/ubuntu/ClickBench/questdb/hits.csv`, duration=0s, errors=0]
2024-04-05T16:57:35.823696Z I i.q.c.t.ParallelCsvFileImporter finished [importId=085572760f310fd8, phase=boundary_check, …
```
=> perf(sql): speed up SQL COPY and REST API CSV import

core/src/main/java/io/questdb/griffin/engine/functions/date/TimestampAddFunctionFactory.java, core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java, core/src/test/java/io/questdb/test/griffin/engine/functions/date/TimestampAddFunctionFactoryTest.java
Added 'T' and 'u' as possible values to dateadd, so we can add millis and microseconds to a timestamp
=> feat(sql): add milliseconds and microseconds support to dateadd

core/src/main/java/io/questdb/network/JavaTlsClientSocket.java
Bug description:
1. HTTP server sends a response immediately followed by TLS close_notification
2. Client unwrap the response and does another receive/unwrap iteration.
3. This unwraps the close notification and recv() return -1. Even there were some plaintext data to be processed
This change make recv() to return received plaintext if there is any.
I discovered this while testing against QuestDB Cloud. I suspect there is an HTTP proxy which behaves differently than QuestDB builtin HTTP server.
=> fix(http): client to process data received before TLS close_notification

.github/workflows/danger.yml
The latest Danger version requires nodejs 18+
see: https://github.com/danger/danger-js/releases/tag/12.0.1
=> chore(build): upgrade nodejs version used by Danger

core/src/main/java/io/questdb/cairo/ColumnType.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/griffin/RecordToRowCopierUtils.java, core/src/main/java/io/questdb/griffin/SqlUtil.java, core/src/test/java/io/questdb/test/griffin/VarcharConversionTest.java
The second `insert` below is currently failing due to the lack of support for converting VARCHAR to LONG256. A similar problem exists for GEOHASH and IPv4. Equivalent expressions with STRING work.
```sql
create table x (c_varchar varchar);
create table y (c_long256 long256);
insert into x values('0x1');
insert into y select * from x;
```
The PR adds simple support for these by relying on the fact that the strings involved are pure ASCII, so it just uses `Utf8Sequence.asAsciiSequence()`.
=> chore(core): add support for varchar-typed arguments to functions

core/src/main/java/io/questdb/griffin/engine/functions/BinaryFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/UnaryFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/bind/BinBindVariable.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/AllNotEqStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/AllNotEqVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolCursorFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InTimestampStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/columns/Long256Column.java, core/src/main/java/io/questdb/griffin/engine/functions/eq/EqSymStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/AbstractLikeVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/SizePrettyFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/groupby/vect/AvgDoubleVectorAggregateFunction.java, core/src/test/java/io/questdb/test/griffin/ParallelGroupByFuzzTest.java
For queries like `SELECT key, count(*) FROM tab WHERE key like '%foobar%' ORDER BY key;` filter functions were not cloned. This led to incorrect results returned by the query.
Also, cleans up `isReadThreadSafe` overrides to make them consistent.
=> fix(sql): fix incorrect results for parallel group by with symbol like filter

core/src/main/java/io/questdb/griffin/engine/groupby/GroupByMergeShardJob.java, core/src/main/java/io/questdb/griffin/engine/groupby/vect/VectorAggregateEntry.java
Fixes #4418
`PerWorkerLocks#acquireSlot()` may throw while the code wasn't properly counting down the latch in that case.
=> fix(sql): fix stuck parallel group by query due to incorrect query timeout handling

core/src/main/java/io/questdb/cairo/VarcharTypeDriver.java
When the varchar is 9 bytes or less, we store it fully within the auxiliary vector. Currently we just write the data bytes, and don't zero out the padding up to 9 bytes. This adds code that zeroes them out, as needed for JIT operations.
=> chore(core): zero out unused inlined varchar bytes

core/pom.xml
Run testsuite with '-Xcheck:jni' to ensure we catch bugs in JNI code which could later cause issues like crashes
Add -Xcheck:jni
Testsuite will be able to catch more JNI bugs
This PR was inspired by a Netty PR:
https://github.com/netty/netty/pull/13642
https://docs.oracle.com/en/java/javase/11/tools/java.html
=> chore(build): add Xcheck:jni flag

core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
Fixes bug introduced in https://github.com/questdb/questdb/pull/4392
`managedCursor.toTop()` resets the state of the cursor. However, this change is not propagated to the inner records until `managedRecord.hasNext()` is called. `.hasNext()` applies the state change to the records, and is not just a predicate.
An assertion was raised against `managedRecord.hasNext()` which would be called correctly in debug builds, but would be elided in release builds, causing breakage to FILL(LINEAR), as the record's position would not be reset to top.
=> fix(sql): FILL(LINEAR) regression in 7.4.1

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InSymbolCursorFunctionFactory.java, core/src/main/java/io/questdb/std/AbstractCharSequenceHashSet.java, core/src/main/java/io/questdb/std/AbstractUtf8SequenceHashSet.java, core/src/main/java/io/questdb/std/CharSequenceBoolHashMap.java, core/src/main/java/io/questdb/std/CharSequenceHashSet.java, core/src/main/java/io/questdb/std/CharSequenceIntHashMap.java, core/src/main/java/io/questdb/std/CharSequenceLongHashMap.java, core/src/main/java/io/questdb/std/CharSequenceObjHashMap.java, core/src/main/java/io/questdb/std/Utf8SequenceHashSet.java, core/src/main/java/io/questdb/std/Utf8SequenceIntHashMap.java, core/src/main/java/io/questdb/std/Utf8SequenceObjHashMap.java, core/src/main/java/io/questdb/std/Utf8StringIntHashMap.java, core/src/main/java/io/questdb/std/Utf8StringObjHashMap.java, core/src/main/java/io/questdb/std/str/Utf8s.java
`Utf8StringIntHashMap` and `Utf8StringObjHashMap` are used in symbol cache and ILP hot path. The lookups are mostly done for `DirectUtf8Sequence`, so introducing `equals(DirectUtf8Sequence, Utf8String)` overload in parallel to the existing `equals(Utf8Sequence, Utf8Sequence)` gets rid of megamorphism in the hash table calls.
=> chore(core): avoid megamorphism in hash tables used on hot path

core/src/main/java/io/questdb/griffin/engine/functions/str/LengthVarcharFunctionFactory.java, core/src/main/java/io/questdb/std/str/Utf8s.java
Uses a SWAR technique to count the UTF-8 continuation bytes and subtract that from the total size of the VARCHAR.
Benchmark results:
```plain
STRING:
select * from (
select title t1, title2 t2 from hits
) where length(t1) > 10;
VARCHAR:
select * from (
select title t1, title2 t2 from hits
) where length(t2) > 10;
master:
STRING
10.8 s
VARCHAR
12 s
branch:
STRING
10.8 s
VARCHAR
9.5 s
```
=> perf(sql): improve performance of length(VARCHAR)

core/src/test/java/io/questdb/test/griffin/engine/groupby/hyperloglog/HyperLogLogTestUtils.java
closes https://github.com/questdb/questdb/issues/4426. 
This approach may seem a bit crude, but I believe it's the quickest way to address the issue. My suggestion is to give it a try, and if you continue to observe incorrect failures of HyperLogLogTest.testFuzz, please let me know. I'll try to figure out a more reliable method for testing this functionality.
=> chore(test): Extend expected cardinality range for HyperLogLog

.idea/ant.xml, core/src/main/assembly/no-jre.xml
Build on master incorrectly packages `libjemalloc.so` into no-jre distribution. This PR removes `libjemalloc.so` from no-jre.
=> chore(core): remove jemalloc from no-jre build

core/src/main/java/io/questdb/griffin/engine/functions/bool/InStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InVarcharFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/bool/InStrFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/bool/InVarcharFunctionFactoryTest.java
Closes https://github.com/questdb/questdb/issues/4496
The `NullConstant` args were being added to the deferred symbol list. This isn't initialised until `init()`.
However, the result was requested early by `functionToConstant0` meaning it wasn't being picked up.
Fix is to stop `NullConstant` being deferred.
=> fix(sql): IN with NULLs and STRINGs sometimes may return the wrong result

core/src/main/java/io/questdb/griffin/SqlOptimiser.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
fixes #4501
This used to work
```SQL
select symbol, sum(amount), timestamp_floor('1d', timestamp), last(timestamp) last_timestamp
from trades w where timestamp > dateadd('d', -1, now());
```
and return few hundred rows on [https://demo.questdb.io](demo). 
But if an alias added to the `timestamp_floor` column
```SQL
select symbol, sum(amount), timestamp_floor('1d', timestamp) "timestamp", last(timestamp) last_timestamp
from trades w where timestamp > dateadd('d', -1, now());
```
the query suddenly returns 700k rows.
=> fix(sql): fix SAMPLE BY and GROUP BY not grouping when used with column aliases

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java, core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/cairo/wal/CheckWalTransactionsJob.java, core/src/main/java/io/questdb/cairo/wal/seq/SeqTxnTracker.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerAPI.java, core/src/main/java/io/questdb/griffin/ConvertOperatorImpl.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/AbstractLineHttpFuzzTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpFailureTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableFailureTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java
fixes #4013
Also periodically re-evaluates all unsuspended WAL tables to mitigate potential race condition of a table not being notified to `ApplyWal2TableJob`. This should eliminate issue found by fuzz test where a table is left unnotified without any errors:
```
java.lang.AssertionError: [-1] txn timed out [expectedTxn=21, writerTxn=-1
at org.junit.Assert.fail(Assert.java:89)
at io.questdb.test.cutlass.http.line.AbstractLineHttpFuzzTest.lambda$runTest$0(AbstractLineHttpFuzzTest.java:242)
at io.questdb.test.tools.TestUtils.assertMemoryLeak(TestUtils.java:644)
at io.questdb.test.cutlass.http.line.AbstractLineHttpFuzzTest.runTest(AbstractLineHttpFuzzTest.java:212)
at io.questdb.test.cutlass.http.line.LineHttpReceiverFuzzTest.runTest(LineHttpReceiverFuzzTest.java:32)
at …
```
=> feat(core): resume all suspended WAL tables on start up

core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/test/java/io/questdb/test/fuzz/FuzzChangeColumnTypeOperation.java, core/src/test/java/io/questdb/test/griffin/AlterTableChangeColumnTypeTest.java
On Windows column conversion for WAL tables can fail if the column is converted from var length to fix length and then dropped and another var column is renamed to that tname. In this case `.i` file remains in WAL segment folder on the first step and the renaming to the existing file name is not supported on Windows, so the last step fails. The fix is to remove `.i` file in WAL segment when column conversion is done.
Second change is to prevent "Not enough space" error at fuzz tests when a column is converted to an indexed symbol. For that the conversion adds indexes only when the source type os Boolean or Byte.
=> chore(core): fix column conversions

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/O3PartitionPurgeJob.java, core/src/main/java/io/questdb/mp/WorkerPoolUtils.java, core/src/test/java/io/questdb/test/griffin/AlterTableAttachPartitionFromSoftLinkTest.java, core/src/test/java/io/questdb/test/griffin/AlterTableDetachPartitionTest.java, core/src/test/java/io/questdb/test/griffin/AlterTableDropActivePartitionTest.java, core/src/test/java/io/questdb/test/griffin/O3PartitionPurgeTest.java, core/src/test/java/io/questdb/test/griffin/VacuumTablePartitionTest.java, core/src/test/java/io/questdb/test/griffin/wal/FuzzRunner.java
The problem found by fuzz tests. 
When a non-WAL table is re-created with the same name (dropped and created with the same name) the partition purge job can drop a partition of the new table. This is relevant log:
```
2024-05-20T21:52:11.600808Z I i.q.t.f.FuzzDropCreateTableOperation dropping table testWalAddRemoveCommitDropFuzz_nonwal~
2024-05-20T21:52:11.619260Z I i.q.c.p.WriterPool created [table=`testWalAddRemoveCommitDropFuzz_nonwal~`, thread=31]
2024-05-20T21:52:11.619370Z I i.q.c.TableWriter open 'testWalAddRemoveCommitDropFuzz_nonwal'
2024-05-20T21:52:11.622014Z I i.q.c.CairoEngine unlocked [table=`testWalAddRemoveCommitDropFuzz_nonwal`]
2024-05-20T21:52:11.622049Z I i.q.c.p.WriterPool >> [table=`testWalAddRemoveCommitDropFuzz_nonwal~`, thread=31]
2024-05-20T21:52:11.625181Z I …
```
=> fix(core): fix potential data loss when non-WAL table dropped and created with same name

core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByIntHashSetFuzzTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/GroupByLongHashSetFuzzTest.java
Also: add Fuzz to classname so it's picked up by the CI fuzzer
=> test(core): GroupBy{Int,Long}HashSet(Fuzz)Test - deal with a random generator yielding duplicates

core/src/main/java/io/questdb/griffin/engine/QueryProgress.java
SQL query logging should be done in sync mode, so it can be traced back always what queries were run.
required by https://github.com/questdb/questdb-enterprise/pull/433
=> chore(core): fix SQL query logging

core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexUtils.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactory.java, core/src/main/java/io/questdb/std/str/DirectUtf16Sink.java, core/src/test/java/io/questdb/test/griffin/engine/functions/regex/RegexpReplaceVarcharFunctionFactoryTest.java
The trick is to avoid litter generated by `matcher.appendReplacement()` and get rid of megamorphism in the input and returned types.
```sql
-- master 22.5s
-- patch 11.5s
SELECT * FROM (SELECT REGEXP_REPLACE(Referer, '^https?://(?:www\.)?([^/]+)/.*$', '$1') AS k, AVG(length(Referer)) AS l, COUNT(*) AS c, MIN(Referer) FROM hits WHERE Referer IS NOT NULL GROUP BY k) WHERE c > 100000 ORDER BY l DESC LIMIT 25;
```
=> chore(sql): speed up regexp_replace(varchar) with single group

core/src/main/java/io/questdb/cairo/TableWriter.java
The issue was found by fuzz tests.
Column top partition is not correctly set if Change Column Type SQL is run on the empty table directly after the truncate table operation. The result is that some partitions can return null values for the converted columns.
=> fix(core): fix column type change after table truncate can lead to invalid data in the column

core/src/main/java/io/questdb/griffin/engine/functions/bool/InCharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InDoubleFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InLongFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InStrFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InTimestampTimestampFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InUuidFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/bool/InVarcharFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/finance/LevelTwoPriceFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ConcatFunctionFactory.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/TimestampQueryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/InDoubleTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/InLongTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/InStrTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/InTimestampTimestampTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/InUUIDTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/InVarcharTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/bool/InStrFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/finance/LevelTwoPriceFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/ConcatFunctionFactoryTest.java
Fixes various SQL failures caused by holding onto transient object and int lists, where the lists contain function objects and SQL positions.
When these lists are mutated, the SQL execution fails.
The fix is to create copies of these lists, and keep the reference to the copies instead of the original lists.
=> fix(sql): fix SQL error when bind variables used within the IN() function

core/src/main/java/io/questdb/cairo/sql/Function.java, core/src/main/java/io/questdb/client/impl/ConfStringParser.java, core/src/main/java/io/questdb/griffin/FunctionFactory.java, core/src/test/java/io/questdb/test/client/LineSenderBuilderTest.java, core/src/test/java/io/questdb/test/client/impl/ConfStringParserTest.java
This change updates the Java client to handle client configuration
strings without requiring a trailing semicolon, aligning it
with the behavior of other clients.
Originally, the trailing semicolon was mandated to help detect
accidentally truncated configuration strings. However, this has
led to user frustration, as semicolons are commonly perceived
as option delimiters rather than terminators, leading to a tendency
to omit the final semicolon.
This update removes the requirement, reducing potential
user errors and improving consistency across different clients.
=> fix(ilp): make trailing semicolon in client configuration optional

core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Add `nm=true` as a query parameter to exclude headers in CSV exports. This is useful for scripting data-based monitoring tasks.
Example, return ingestion lag in milliseconds:
```
$ curl -G "http://localhost:9000/exp" --data-urlencode "query=SELECT (now () - max(timestamp)) / 1000 from trades;" --data-urlencode "nm=true"
210
```
This returns only the query result, omitting any metadata, which allows monitoring without requiring additional post-processing.
Additionally, the `nm` parameter was already supported in the JSON (/exec) endpoint, and this PR improves the consistency of the QuestDB REST interface.
Fixes #4629
=> feat(http): add support for `nm=true` query parameter in text export (/exp) to exclude metadata

core/src/main/java/io/questdb/cairo/ColumnTypeConverter.java, core/src/main/java/io/questdb/cairo/O3PartitionJob.java, core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/cairo/frm/file/ContiguousFileVarFrameColumn.java
The bug was found by fuzz testing.
If a STRING column with a column top goes through partition squashing it corrupts the storage and cannot be read back.
=> fix(core): fix potentially corrupt storage of STRING column after data inserting

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGOids.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Handle `BINARY_TYPE_VARCHAR` in `PgConnectionContext`.
We were missing the case when the binary flag was raised for VARCHAR.
It resulted in an empty response and broke the client.
=> fix(pgwire): Fix for querying VARCHAR columns via sqlx::postgres in Rust

core/src/main/java/io/questdb/cutlass/pgwire/CleartextPasswordPgWireAuthenticator.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Changes:
- PGConnectionContext to properly handle bind variable type for vararg functions
- Fix dumping of PGWire traffic
=> fix(pgwire): fix for using vararg functions with bind variables in Go

core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Before this change, if a request timed out after execution had started, the REST interface would return HTTP 408 (Request Timeout) as expected. However, if the request timed out before execution began, it would incorrectly return HTTP 400.
This PR corrects this behavior to consistently return HTTP 408 in both scenarios.
Additionally, this PR fixes a flaky test: `testJsonQueryErrorOnDataUnavailableEventNeverFired()`. This test was occasionally failing on the slower Windows CI environments. Specifically, the test expected an HTTP 400 error, but would receive an HTTP 408 when the query timed out before starting.
=> fix(http): Ensure REST interface consistently returns HTTP 408 on timeouts

core/src/main/java/io/questdb/griffin/engine/functions/finance/LevelTwoPriceFunctionFactory.java
Gets rid of `ObjList#qetQuick()` calls in unrolled versions of `l2price` SQL function.
```sql
-- master L2PriceFunction1: 246ms
-- master L2PriceFunctionN: 260ms
-- patch L2PriceFunction1:  181ms
select max(l2price(0.0015, UserID, ParamPrice)) from hits;
```
(the choice of columns is arbitrary, just for measurement purposes)
=> perf(sql): optimize l2price with up to 5 argument pairs

core/src/main/java/io/questdb/Bootstrap.java, core/src/main/java/io/questdb/std/Files.java
NFS is known to cause issues. It is better to fail at startup rather than pretending everything is fine, only to inevitably encounter problems later. Although NFS has never been supported, this is the first time we are enforcing this, which could be a breaking change for some users.
When NFS is detected QuestDB startup fails with this error:
```
Error: Unsupported Filesystem Detected.
QuestDB cannot start because the '/tmp/dbroot-fixes' is located on an NFS filesystem, which is not supported. Please relocate your 'db root' to a supported filesystem to continue.
For a list of supported filesystems and further guidance, please visit: https://questdb.io/docs/deployment/capacity-planning/#supported-filesystems [path=/tmp/dbroot-fixes/db, kind=db, fs=NFS]
```
We don't enforce this for `sql …
=> fix(core): 💥 breaking change - enforce fail-fast on NFS

core/src/test/java/io/questdb/test/fuzz/FuzzInsertOperation.java
Fuzz tests now treat `strLen` parameters as the maximum possible size for Binary, String, and Varchar columns. Previously, for Varchar columns, it would always generate UTF-8 strings with `strLen` codepoints, resulting in multi-gigabyte O3 transactions causing out-of-memory errors.
This change makes Varchar values consistent with String and Binary: strLen is the maximum size, but each value can be anything between 0 and strLen in length.
An additional benefit of this change is that fuzz tests now exercise fully inlined Varchar values as well.
=> test(sql): fuzz tests use strLen as maximum varchar length

ci/docker-release-pipeline.yml, core/Dockerfile, core/LICENSE.txt
Adds docker builds based on the [redhat ubi](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) to become compliant with [preflight checks](https://github.com/redhat-openshift-ecosystem/openshift-preflight) for RedHat certification.
One of the requirements is adding a license file to `/licenses` inside the image. Since I didn't want to expand our Docker build context (for build speed optimization), and we can't add files to an image from outside the context (not even symlinked), I copied the license file to the build context root (`./core`).
=> ci(build): add redhat ubi docker build

examples/src/main/java/com/example/sender/AuthExample.java, examples/src/main/java/com/example/sender/AuthTlsExample.java, examples/src/main/java/com/example/sender/BasicExample.java, examples/src/main/java/com/example/sender/HttpAdvancedExample.java, examples/src/main/java/com/example/sender/HttpExample.java, examples/src/main/java/com/example/sender/HttpsAuthExample.java
Changed examples to use trades data, rather than sensors. These examples are pulled directly to the docs
=> docs(ilp): changed examples to use trades table

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java, core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/O3PartitionPurgeJob.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/vm/MemoryCMORImpl.java, core/src/main/java/io/questdb/cairo/vm/api/MemoryCR.java, core/src/main/java/io/questdb/cairo/wal/CheckWalTransactionsJob.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/java/io/questdb/log/AbstractLogRecord.java, core/src/main/java/io/questdb/log/LogFactory.java, core/src/main/java/io/questdb/log/LogRecord.java, core/src/main/java/io/questdb/log/NullLogRecord.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/cairo/vm/ContiguousOffsetMappedMemoryTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalTableWriterFuzzTest.java, core/src/test/java/io/questdb/test/griffin/TimestampQueryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/bind/RegexpReplaceStrBindVariableTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalTableSqlTest.java, core/src/test/java/io/questdb/test/griffin/wal/WalWriterFuzzTest.java, core/src/test/java/io/questdb/test/log/LogAlertSocketTest.java
Every transaction written to WAL table has a fixed time needed to apply to the table columns. For small 1 line transactions this fixed overhead can make a big impact on overall throughput.
This PR reduces the time spent to apply a transaction and moves overall throughput from 3k transactions per second to 5k transactions per second in a simulated benchmark.
The changes are:
- avoid mmap/munmp WAL column files when data is copied using FDs (no mixed IO)
- optimise batching of rows in the last partition LAG area to reduce small, frequent full commits
Also, this PR reduces the logging by not logging full QuestDB paths to the files but only relative paths to the DB root directory.
=> perf(core): speedup small transaction writing 50-100%

ci/docker-release-pipeline.yml, core/Dockerfile
Missed a flag (and an architecture) in my previous command because I was using podman locally. Tested the exact command using docker and it works.
Also overrides 2 additional image tags that were written in the base image by redhat
I tested the docker build (without the `--push` flag) on an x86 ec2 instance 
fixes https://github.com/questdb/questdb/pull/4783
=> ci(build): fix rhel Docker image build

core/src/main/java/io/questdb/griffin/engine/window/CachedWindowRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionTest.java
This is reproducible when using a negative limit and querying a table without a designated timestamp. then `buildRecordChain()` is called twice: once in `calculateSize()` and then is `hasNext()`
Fixes https://github.com/questdb/questdb/issues/4748
TODO:
=> fix(sql): some window functions might double count rows

core/src/main/java/io/questdb/std/str/DirectString.java, core/src/test/java/io/questdb/test/std/str/DirectStringTest.java
Modified the `_subSequence` to correct the calculation of the `lo`, `hi`, and `len`.
=> chore(core): `DirectString#_subSequence` method

core/src/main/java/io/questdb/griffin/engine/groupby/SampleByFillValueNotKeyedRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/groupby/TimestampSamplerFactory.java, core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
This worked:
```sql
select pickup_datetime, first(fare_amount) as first_price from trips
sample by 1w 
limit 5
```
This didn't:
```sql
select pickup_datetime, first(fare_amount) as first_price from trips
sample by 1w fill(null)
limit 5
```
with error:
> unsupported interval qualifier
Now it works.
Also contains a fix for a separate issue with the new FROM-TO syntax, where the a sequential SAMPLE BY with FROM-TO and FILL would sometimes contain an extra row versus the parallel version. Both should be half-open and not include the final timestamp, especially since the bucket may not have the data you'd expect in it (or any at all) due to filtering.
=> fix(sql): add support for filling weeks ('w') in SAMPLE BY queries

core/rust/qdbr/src/parquet_write/jni.rs, core/src/main/java/io/questdb/griffin/engine/groupby/FillRangeRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java
Closes https://github.com/questdb/questdb/issues/4847
Support for parallel sample by with a fill clause was added in https://github.com/questdb/questdb/pull/4733
However, an edge case was missed. If no `FROM-TO` clause is provided, and all records are filtered out by the `WHERE` clause, then the `FillRangeRecordCursorFactory` was improperly initialised.
This change ensures that errors are not thrown when looking up what buckets to fill, by enforcing bucket index >= 0.
=> fix(sql): fix edge case when using parallel sample by with fill

core/src/main/java/io/questdb/Bootstrap.java
https://github.com/questdb/questdb/pull/4810 added the `-Dcontainerized` system property, which points the Bootstrap to the [stdout-enabled log.conf](https://github.com/questdb/questdb/blob/master/core/src/main/resources/io/questdb/site/conf/log.conf) when set to `true`.
This needs to be set in the docker entrypoint, otherwise we log to disk using the [non-containerized log.conf](https://github.com/questdb/questdb/blob/master/core/src/main/resources/io/questdb/site/conf/non_containerized_log.conf).
Evidence:
Locally, on my branch, I build a docker image with my updated `docker-entrypoint.sh`:
```
docker buildx build --build-arg tag_name=steve/fix-docker-entrypoint --platform linux/amd64 -t sklarsa/questdb:test .
```
And when I run it, I get all the logs
```
➜  core …
```
=> chore(log): set containerized system property to default true

core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java
BACKUP statement's SQL context was used for reading tables. This led to a permission error in case the user has no permission to read some tables, e.g. system ones.
=> chore(sql): fix backup read table permissions

ci/templates/install-llvm.yml, ci/templates/steps.yml, ci/test-pipeline.yml, core/rust/qdbr/src/lib.rs, core/src/main/java/io/questdb/std/histogram/org/HdrHistogram/package-info.java
Use rustup to install them, this avoids the inevitable version mismatch the previous method would result in.
=> ci(build): improve method of installing LLVM coverage tools

core/pom.xml
Maven Surefire plugin uses a very peculiar syntax for `%regex[...]` -- when the "regex" ends in ".class", it's taken literally and the dot does not mean "any character", but a literal `.`.
So the backslash that I added in an earlier PR should not be there.
=> fix(build): revert changed test class regex

core/src/main/java/io/questdb/cairo/SymbolMapWriter.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/cutlass/http/DispatcherWriterQueueTest.java
In `SymbolMapWriter`, there is a condition to determine whether the symbol is or isn't cached:
https://github.com/questdb/questdb/blob/753485fb4427b9317a98921c59031d300d4cc2da/core/src/main/java/io/questdb/cairo/SymbolMapWriter.java#L200-L202
This checks whether or not there are values in-memory in a cache.
In `TableWriter`, there is a `changeCacheFlag` method:
https://github.com/questdb/questdb/blob/753485fb4427b9317a98921c59031d300d4cc2da/core/src/main/java/io/questdb/cairo/TableWriter.java#L817-L829
This is used to toggle the flag on or off.
Starting with `CACHE` enabled, the `SymbolMapWriter` is loaded and cache initialised.
When setting it to `NOCACHE`, `SymbolMapWriter` will run `updateCacheFlag`:
https://github.com/questdb/questdb/blob/753485fb4427b9317a98921c59031d300d4cc2da/core/s …
=> fix(sql): symbol cannot be set to CACHE immediately after setting it to NOCACHE

core/src/test/java/io/questdb/test/ServerMainForeignTableTest.java
The original code was flooding the system with (parallel?) SAMPLE BY queries until it returned the expected results.
There are 2 issues with this approach:
1. minor one: if the query occasionally returns wrong results then the test won't catch it
2. bigger one: it looks like the WAL Apply Job was starved due almost 5k SAMPLE BY queries running in the span of 5s. See the log: https://gist.githubusercontent.com/jerrinot/2efdc5d35f3d1cfbdad2fda78375db2a/raw/d51368ae264f262f1e64a6ad1cdce244d0ac3900/gistfile1.txt There are 5k queries, none of them returns the expected result. Only after the failure there is a log message about WAL being ejected.
We know the test populate the table atomically (INSERT ATOMIC INTO ...) thus we can await for the tx to be applied and then simply assert the expected …
=> test(sql): fix flaky testServerMainCreateWalTableInVolume()

core/src/test/java/io/questdb/test/griffin/CheckpointTest.java
This PR https://github.com/questdb/questdb/pull/4869 introduced the `StationaryMicrosClock` in `CheckpointTest.setUpStatic()`, which was necessary since `testCheckpointStatus()` relied on frozen clocks.
However, other tests, such as `testSuspendResumeWalPurgeJob()`, depend on the ability to manipulate time freely and fail with the `StationaryMicrosClock`.
This issue was mostly obscured because `CheckpointTest` resets the clock to the default (non-StationaryMicrosClock) after each test case. Therefore, `testSuspendResumeWalPurgeJob()` only fails when it runs as the first test case in `CheckpointTest`.
When another test runs first, it resets the clock back to normal after completion, and subsequent executions of `testSuspendResumeWalPurgeJob()` pass normally.
Fixes #4922
This fix removes …
=> test(core): fix flaky CheckpointTest.testSuspendResumeWalPurgeJob()

core/src/test/java/io/questdb/test/cutlass/http/line/HttpSenderMemoryPressureFuzzTest.java
it's now running 7s on my local vs around a minute before.
It's still triggering the parallelism limiter on OOM.
=> test(core): speed-up HttpSenderMemoryPressureFuzzTest.testMemoryPressureSingleSender()

ci/templates/steps.yml, core/pom.xml, core/rust/qdbr/src/lib.rs
Removes the cumbersome way in which an environment variable was being set, moves that to pom.xml
=> ci(build): simplify Rust code coverage

core/src/main/java/io/questdb/client/Sender.java, core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java, core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java, core/src/main/java/io/questdb/cutlass/line/LineUdpSender.java, core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java
This is useful when you start a row and then realize the row is invalid and cannot be sent to the QuestDB server.
This can occur when you cannot validate data upfront, for example, when you receive them in a streaming fashion.
This API is implemented only for the HTTP transport, as the TCP transport can flush at any time. The HTTP transport flushes only after finishing a row.
Some other clients - for example C# - already support this feature.
=> feat(ilp): ILP client allows to cancel the current row

core/src/main/java/io/questdb/griffin/engine/functions/finance/FinanceUtils.java, core/src/main/java/io/questdb/griffin/engine/functions/finance/MidPriceFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/finance/SpreadBpsFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/griffin/engine/functions/finance/SpreadBpsFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/finance/SpreadFunctionFactoryTest.java
Adds a spread_bps function. This is the quoted spread in basis points i.e `spread / mid * 10k`
Part of https://github.com/questdb/questdb/issues/4620
=> feat(sql): add spread_bps function for finance

core/src/main/java/io/questdb/cutlass/pgwire/AbstractTypeContainer.java, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/main/java/io/questdb/cutlass/pgwire/PGPipelineEntry.java, core/src/main/java/io/questdb/cutlass/pgwire/TypesAndSelect.java
There are still `testInsertTableDoesNotExistSimple[NO_WAL]` and `testSchemasCall[NO_WAL]` failing. 
That wasn't the case before, it's now failing even in `vi_pg_pipeline` - I'll explore it too. 
edit: `testInsertTableDoesNotExistSimple[NO_WAL]` and `testSchemasCall[NO_WAL]` are failing due to JDBC driver being upgraded here: https://github.com/jerrinot/questdb/blame/96e0f5c1e77977487c56462a154a505498e9de93/core/pom.xml#L707
=> pgwire 2.0: Fix Rust hex tests

core/src/main/java/io/questdb/ServerMain.java, core/src/main/java/io/questdb/cairo/DedupColumnCommitAddresses.java, core/src/main/java/io/questdb/cairo/O3PartitionJob.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
Fixes crash found by fuzz test. The problem is that an incorrect size was used when unmapping the deduplication data.
=> fix(core): fix potential crash when writing with dedup key on on varchar, string column key

compat/src/test/java/io/questdb/compat/InfluxDBClientTest.java, compat/src/test/java/io/questdb/compat/InfluxDBUtils.java, core/src/main/java/io/questdb/cutlass/http/processors/LineHttpProcessorState.java
When ILP line does not fit receive HTTP buffer there is nothing logged in the server logs, this is fixed in this PR.
Also after test refactoring this PR fixes a failure when the last line is nothing but `\n`character, this was considered to be a parse error but now will be tolerated and the message will be valid.
E.g. this is now a valid ILP request containing 1 line (\n chars written explicitly in this example):
```
table_a,sym=123 val=999i\n
\n
```
=> fix(ilp): add error message in server log about the line that caused receive buffer overflow

core/src/main/java/io/questdb/griffin/engine/groupby/FillRangeRecordCursorFactory.java
The `bucketIndex()` function was being called even when `maxTimestamp` could not change. This has been amended.
=> chore(sql): remove unnecessary round function calls in FillRangeRecordCursor

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/griffin/ReaderReloadFuzzTest.java, core/src/test/java/io/questdb/test/griffin/ReaderReloadTest.java
Reduce performance hit by re-opening table partitions
- generously bump table reader max open partitions to 10,000 from 128. This will keep up to 10k partitions open in the Table Readers instead of current 128
- optmise partition reload logic to not reload all the partitions every time a new partition is added/change in the table
This will speed up query execution for the tables with many partitions, like hourly partitions
=> perf(sql): reduce unnecessary TableReader partition reloads

core/src/main/java/io/questdb/griffin/SqlUtil.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastIntToIPv4FunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastStrToIPv4FunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastStrToUuidFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/cast/CastVarcharToIPv4FunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/CaseCommon.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/CoalesceFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/IPv4Test.java, core/src/test/java/io/questdb/test/griffin/OrderByRadixSortTest.java, core/src/test/java/io/questdb/test/griffin/SqlUtilTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CaseFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CoalesceFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/SwitchFunctionFactoryTest.java
Fixes missing UUID and IPv4 literal in `coalesce` function and `switch` statement. With this path, it's enough to write `coalesce(x, '00000000-0000-0000-0000-000000000000')` instead of `coalesce(x, cast('00000000-0000-0000-0000-000000000000' as uuid))`.
=> fix(sql): missing UUID and IPv4 literal support in coalesce function and switch statement

core/src/main/java/io/questdb/griffin/engine/groupby/GroupByIntHashSet.java, core/src/main/java/io/questdb/griffin/engine/groupby/GroupByLong128HashSet.java, core/src/main/java/io/questdb/griffin/engine/groupby/GroupByLong256HashSet.java, core/src/main/java/io/questdb/griffin/engine/groupby/GroupByLongHashSet.java, core/src/main/java/io/questdb/griffin/engine/groupby/GroupByMergeShardJob.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilterAtom.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncFilteredRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByAtom.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByNotKeyedAtom.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByNotKeyedRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByRecordCursor.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncGroupByRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AsyncJitFilteredRecordCursorFactory.java, core/src/test/java/io/questdb/test/ServerMainQuerySmokeTest.java
When a parallel group by sharding takes place, it may happen that a work-stealing thread steals another thread's task and starts executing it as if it's the task's owner.
The fix makes the per-worker synchronization mandatory in such cases by checking the task's atom and comparing it with the thread's one.
=> fix(sql): race in parallel group by with many groups

core/src/test/java/io/questdb/test/griffin/engine/groupby/SampleByTest.java
The implementation using `Date` could fail at certain times of day due to differences in UTC and local time on the local machine. This implementation should fix this flakiness.
=> chore(sql): fix non-timezone aware test

core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/processors/LineHttpProcessor.java, core/src/main/java/io/questdb/cutlass/line/LineMetrics.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpConnectionContext.java
This is in reference to #4751 - adding two new CountGauge to keep track of HTTP and TCP bytes in LineMetrics.
=> feat(ilp): add ILP traffic volume metrics - TCP, HTTP

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
=> fix(core): fix db random crash after inserting into a table with varchar dedup key

ci/test-pipeline.yml
Azure CI is quite expensive to run nowadays and it's often clogged with the draft PRs nowhere near the end.
This change disables triggering CI builds on draft PRs
=> ci(build): disable ci auto triggers on draft PRs

core/src/test/java/io/questdb/test/cutlass/text/TextLoaderTest.java
Fixes https://github.com/questdb/questdb/issues/4823
It looks like a JVM bug! It’s quite interesting:
The test converts a Java string with valid CSV content into a UTF-8 byte array, then copies the array
content into a native buffer.
During copying, it corrupts three specific bytes. These bytes happen to be part of the CSV header.
It literally overrides the three bytes with an invalid UTF-8 sequence: A0 A0 A0.
From that point on, the test exclusively uses the native buffer with the corrupted field name.
When TextMetadataDetector encounters an invalid UTF-8 sequence in the field name, it creates
a synthetic field/column name: f_<index>.
The test asserts that this synthetic field is present. Yet, in failing runs, there is
no synthetic column at all! Magically, the field name is correct—as …
=> test(http): flaky TextLoaderTest.testBrokenUtf8Header()

core/docker-entrypoint.sh
We have the `-ea` flag in many places like `questdb.sh`, but not in the Docker image.
=> chore(core): enable assertions in Docker image

core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/test/java/io/questdb/test/griffin/AggregateTest.java, core/src/test/java/io/questdb/test/griffin/ExplainPlanTest.java, core/src/test/java/io/questdb/test/griffin/ExpressionParserTest.java, core/src/test/java/io/questdb/test/griffin/FunctionParserTest.java, core/src/test/java/io/questdb/test/griffin/GroupByTest.java, core/src/test/java/io/questdb/test/griffin/IPv4Test.java, core/src/test/java/io/questdb/test/griffin/SqlCodeGeneratorTest.java, core/src/test/java/io/questdb/test/griffin/SqlOptimiserTest.java, core/src/test/java/io/questdb/test/griffin/UuidTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/ApproxCountDistinctIntGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctIntGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctLong256GroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctLongGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctSymbolGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctUuidGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountStringGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/StringAggGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/StringDistinctAggGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/StringDistinctAggSymbolGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/StringDistinctAggVarcharGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/json/JsonExtractVarcharFunctionFactoryTest.java
This change means that instead of using `count_distinct(foo)`, it is now possible to write `count(distinct foo)`. Similarly, instead of `string_distinct_agg(foo)`, you can now use `string_agg(distinct foo)`.
The motivation for this change is to improve compatibility with PostgreSQL.
Internally, the `count()` and `string_agg()` functions are rewritten to their distinct versions when the `distinct` keyword is present.
~`count(distinct)` is still treated as a non-unique count of a column named distinct. Since `distinct` is a keyword, we could (or should?) enforce that it be enclosed in double quotes when used as a column name. This would cause `count(distinct)` to fail. However, this PR is more lenient and does not enforce this, prioritizing backward compatibility.~
~If reviewers feel that …
=> feat(sql):  breaking change 💥 - support for count(distinct col) and string_agg(distinct col)

core/src/main/java/io/questdb/griffin/engine/functions/groupby/RegressionSlopeFunctionFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory
`regr_slope` was listed under a finance-related functions issue, but is actually a more generic statistical function, and should be colocated with the others (variance, stddev etc.).
=> chore(sql): relocate `regr_slope()`

core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
when a client sends multiple UPDATE statements then - depending on the protocol mode - only the last statement is closed on the server side.
the current pgwire implementation does not support pipelined execution very well, but a memory leak justifies the fix.
**Note for reviewers**
GitHub web diff does not cope well with the test change. The new test is taken from the `vi_pg_pipeline` where the new pgwire implementation is being cooked. It's the same test, except it runs in in all pgwire modes: simple, extended, text, binary, different thresholds for prepared statements, etc.
=> fix(pgwire): memory leak with pipelined UPDATEs

core/src/test/java/io/questdb/test/griffin/wal/DedupInsertFuzzTest.java
fix 
```
java.lang.ArithmeticException: / by zero
at io.questdb.std.Rnd.nextLong(Rnd.java:162)
at io.questdb.test.griffin.wal.DedupInsertFuzzTest.testDedupWithRandomShiftAndStepAndColumnTops(DedupInsertFuzzTest.java:836)
at io.questdb.test.griffin.wal.DedupInsertFuzzTest.lambda$testDedupWithRandomShiftAndStepAndVarcharKeyAndColumnTops$4(DedupInsertFuzzTest.java:168)
```
=> test(core): fix fuzz test setup / by zero exception

.github/workflows/pgwire_latest.yml, .github/workflows/pgwire_stable.yml, .gitignore, compat/src/test/python/runner_asyncpg.py, compat/src/test/python/runner_psycopg2.py, compat/src/test/python/runner_psycopg3.py, compat/src/test/rust/scenarios/src/main.rs, compat/src/test/scenarios_latest.sh, compat/src/test/scenarios_stable.sh, core/src/main/java/io/questdb/cutlass/pgwire/PGConnectionContext.java, core/src/test/java/io/questdb/test/cutlass/pgwire/BasePGTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
This PR fixes a bug in PGWire query caching.
**Problem:**
1. Simple Protocol Clients: These clients caused cache poisoning by failing to poll the cache during query execution, but still populated it afterward, leading to stale entries.
2. Schema Change: A schema change invalidated all cached plans, which is expected.
3. Extended Protocol Clients: After the schema change, extended protocol clients consulted the cache, found stale query plans, and triggered retries. Each retry failed as the cache continued returning stale plans.
**Fix:**
Simple protocol clients now do not populate the query cache.
Also - added a facility for simple local execution of non-Java tests and Rust runner respects iteration config
=> fix(pgwire): fix a spurios errors after table schema change

core/src/main/java/io/questdb/griffin/engine/functions/groupby/StringAggGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/StringAggGroupByFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/StringAggGroupByFunctionFactoryTest.java
`string_agg()` can knockout server if not careful. This PR forces the memory cap per function instance that defaults to 1MiB
Error message to the user in case cap is breached:
The value is configures via `cairo.sql.string.function.buffer.max.size` and is dynamically reloadable by this function.
=> fix(sql): cap `string_agg()` memory use to the "strFunctionMaxBufferLength" value

ci/github-release-pipeline.yml
Fix 
https://dev.azure.com/questdb/questdb/_build/results?buildId=114472&view=logs&j=8a903c0a-beec-5c5f-3f8d-9756db27ce86&t=e27b12f5-dddf-508b-19d6-b729a9cbdfc9
Previously `grep` resulted into too many lines, this fixes it to take only the line that contains the draft release url
=> ci(build): fix ci release pipeline draft url parsing

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/WorkerPoolManager.java, core/src/main/java/io/questdb/mp/WorkerPool.java, core/src/main/java/io/questdb/mp/WorkerPoolConfiguration.java, core/src/main/java/io/questdb/network/AbstractIODispatcher.java, core/src/test/java/io/questdb/test/ServerMainTest.java
This change makes QuestDB more responsive to the health check endpoint, which is usually used by Kubernetes. What used to happen is that on high CPU load `http-min-server` does not cope with processing disconnects and exceeds connection limit. That closes the listening socket and the server becomes unresponsive. Kubernates then restart the QuestDB pod.
Changes
- Make HTTP server connection limit log message of Advisory level so it's clear that the limit is exceeded.
- Increase default HTTP min server connection limit from 4 to 64.
- Set higher HTTP MIn server worker pool threads priority
=> feat(http): make healthcheck endpoint responsive on high CPU load

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java
Replace spaghetti-like two-method tandem, which was assembling artefacts for group-by and sample-by queries. This was necessitated by an awkward dependency of code generator on the token position, which is ordinarily display-only value. This makes tricky SQL rewrites that do not have organic position.
There is a single method now, with simpler logic that does the same thing. Hence tests pass (hopefully)
=> chore(sql): simplify group-by SQL assembly

benchmarks/src/main/java/org/questdb/UnorderedVarcharMapBenchmark.java, core/src/main/java/io/questdb/cairo/IndexBuilder.java, core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/vm/MemoryPMARImpl.java, core/src/main/java/io/questdb/cairo/vm/Vm.java, core/src/main/java/io/questdb/cairo/wal/WalEventWriter.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/java/io/questdb/cairo/wal/seq/SequencerMetadata.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerAPI.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java, core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLog.java, core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLogFile.java, core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLogV1.java, core/src/main/java/io/questdb/cairo/wal/seq/TableTransactionLogV2.java, core/src/main/java/io/questdb/cutlass/text/CsvFileIndexer.java, core/src/main/java/io/questdb/std/SimpleReadWriteLock.java, core/src/test/java/io/questdb/test/cairo/CairoMemoryTest.java, core/src/test/java/io/questdb/test/cairo/MemRemappedFileTest.java, core/src/test/java/io/questdb/test/cairo/TableReaderMetadataCorruptionTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java, core/src/test/java/io/questdb/test/wal/TableTransactionLogFuzzTest.java
- remove hard "msync" from critical path (e.g. commit). "msync" is conditional on database being in SYNC mode
- remove read-lock when WAL writer is activated. When metadata version doesn't change WAL activation follows fast path
- refactor out caching of `cairo.commit.mode` value, so it can be reloaded without server restart
PG Wire 2.0 bench before and after. 10 second run of inserts, two fields, commit every row (batch size = 1).
Before:
```
2,196 inserts    14,042 selects
4,496 inserts    43,795 selects
6,760 inserts    75,253 selects
9,022 inserts   107,121 selects
11,044 inserts   137,401 selects
13,246 inserts   170,169 selects
15,388 inserts   201,575 selects
17,636 inserts   234,439 selects
19,868 inserts   266,073 selects
22,090 inserts   295,647 selects
12 JDBC inserters, 1 …
```
=> perf(core): replace unconditional txn sync with a conditional one. 10x improvement of ingress perf for small transactions

core/src/main/java/io/questdb/std/str/StringSink.java
Avoid redundant buffer allocations in StringSink when the existing buffer matches the required size. Previously, repeated insertions of same-sized strings would unnecessarily create new buffers, even when the existing one was adequate.
Spotted this in allocation profiler while working with PGWire data. I was pumping in tons of INSERT rows, and QueryRegistry (which uses StringSink internally) kept recreating buffers for no good reason even after it hit the right size.
=> perf(core): optimize StringSink buffer reuse - garbage elimination

core/src/main/java/io/questdb/cutlass/line/AbstractLineSender.java, core/src/main/java/io/questdb/cutlass/line/LineTcpSender.java, core/src/main/java/io/questdb/cutlass/line/LineUdpSender.java, core/src/main/java/io/questdb/cutlass/line/http/LineHttpSender.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineProtocolException.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineWalAppender.java, core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderTest.java, core/src/test/java/io/questdb/test/std/datetime/microtime/TimestampsTest.java
Client no longer works with nanoseconds internally. Previously, even non-designated timestamps were converted to nanos only to be converted back to microseconds. The highest timestamp which can be represented in nanos in a 64-bit signed integer is 2262-04-11 23:47:16.854. Anything above this would overflow. This change converts timestamps directly to microseconds, preventing the overflow.
It also changes behavior for designated timestamps: they are now sent as microseconds instead of nanos, since the server would store them in microseconds anyway. This means even the designated timestamps now support a higher range.
The max timestamp that works reliably is 9999-12-31 23:59:59.999999 since our timestamp format compiler assumes at most 4-digit years. If we remove this limitation, we could …
=> fix(ilp): Java ILP client supports timestamps up to 9999-12-31 23:59:59.999999

core/src/main/java/io/questdb/griffin/engine/functions/window/AvgDoubleWindowFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/FirstValueDoubleWindowFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/RankFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/window/RowNumberFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/window/WindowFunctionUnitTest.java
For some reason `OrderedMap` was used in `WindowFunction`s while they don't seem to use the iteration order property of the hash table.
=> perf(sql): use faster hash table in window functions

ci/templates/steps.yml, core/src/test/java/io/questdb/test/FilesTest.java
The `Files.testIsDirOrSoftLinkDir` test requires either Admin or Developer Mode privilidges on Windows.
After this PR, the test will always test the `isDir` logic, but will only execute the symlink checks on CI where the extra privilidges are present.
This change does not affect Linux and MacOS runners.
=> test(core): partially disabled `Files.testIsDirOrSoftLinkDir` test on Windows

core/src/test/java/io/questdb/test/fuzz/FuzzDropCreateTableOperation.java, core/src/test/java/io/questdb/test/fuzz/FuzzDropPartitionOperation.java
Fixes https://dev.azure.com/questdb/questdb/_build/results?buildId=118054&view=results
```
2024-11-12T13:06:46.9734992Z 2024-11-12T13:06:46.972336Z I i.q.t.f.FuzzDropCreateTableOperation dropping table testWalWriteFullRandom_wal_parallel~2
2024-11-12T13:06:46.9801186Z 2024-11-12T13:06:46.979883Z I i.q.c.p.WriterPool open [table=`testWalWriteFullRandom_wal_parallel~2`, thread=2955]
2024-11-12T13:06:46.9805414Z 2024-11-12T13:06:46.979955Z I i.q.c.TableWriter open 'testWalWriteFullRandom_wal_parallel'
2024-11-12T13:06:46.9822395Z 2024-11-12T13:06:46.982037Z I i.q.c.TableWriter switched partition [path=/testWalWriteFullRandom_wal_parallel~2/2022-03-06]
2024-11-12T13:06:46.9832094Z 2024-11-12T13:06:46.982942Z I i.q.c.p.WriterPool >> [table=`testWalWriteFullRandom_wal_parallel~2`, thread=2955] …
```
=> test(core): fix fuzz drop partition test to not fail when running with drop/recreate fuzz step in parallel

core/src/main/java/io/questdb/griffin/engine/join/CrossJoinRecordCursorFactory.java, core/src/test/java/io/questdb/test/griffin/SecurityTest.java, core/src/test/java/io/questdb/test/griffin/model/IntrinsicModelTest.java
`CrossJoinRecordCursorFactory` was missing a circuit breaker check. We now check it after each iteration through the secondary table.
=> fix(sql): cross join queries not cancelling when circuit breaker is invoked

core/pom.xml
Changed:
- use a new information_schema.questdb_columns() instead of information_schema.columns()
=> chore(core): pickup web console 0.6.5

core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGTlsCompatTest.java
This PR fixes incorrect handling of the `PeerIsSlowToReadException` during the TLS initiation stage.
=> fix(pgwire): fix error message resend loop during failed TLS connection initiation

core/rust/qdbr/src/parquet_write/varchar.rs, core/src/test/java/io/questdb/test/TestServerConfiguration.java
Required to fix ent's `HttpCallbackTest`
Refs https://github.com/questdb/questdb-enterprise/pull/529
Also makes Clippy (Rust linter) happy again
=> test(core): add missing override to TestServerConfiguration

benchmarks/pom.xml, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoException.java, core/src/main/java/io/questdb/cairo/RecordChain.java, core/src/main/java/io/questdb/cairo/sql/NetworkSqlExecutionCircuitBreaker.java, core/src/main/java/io/questdb/cairo/vm/api/MemoryCR.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/TextQueryProcessor.java, core/src/main/java/io/questdb/griffin/engine/ops/UpdateOperation.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/griffin/CheckpointTest.java
We are going from this:
to this:
- added an assertion to `RecordChain.of()` so that record chain cannot take illegal offset
- replaced `query.timeout.sec` with `query.timeout`. The value can be set as `query.timeout=5s` or `query.timeout=1m` etc. Old property is still supported but deprecated
=> fix(http): fix bad error message to Web Console when SQL times out

core/src/main/java/io/questdb/DynamicPropServerConfiguration.java, core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/ShowParametersCursorFactory.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/cairo/Overrides.java
SHOW PARAMETERS SQL now correctly displays all reloadable properties:
```sql
(SHOW PARAMETERS) WHERE reloadable = true;
```
The `dynamic` column here was renamed to `reloadable` to keep naming consistent.
https://questdb.com/docs/configuration/#reloadable-settings
Ent PR: https://github.com/questdb/questdb-enterprise/pull/543
=> feat(sql): mark reloadable properties in show parameters SQL

core/src/main/java/io/questdb/cairo/TableReader.java
Found by fuzz test
When a mapping exception is thrown on TableReader resizing the columns on a column add it can lead to a leak of file descriptors and memory.
=> fix(core): fix resource leak on query errors

core/src/test/java/io/questdb/test/griffin/engine/functions/activity/QueryActivityFunctionFactoryTest.java
the test is racy: it starts a new thread and then both the main test thread and the newly started thread uses the main test string sink concurrently.
the problem can be easily reproduced by injecting a bit of sleeping to `printSql()`.
```java
public static void printSql(
SqlCompiler compiler,
SqlExecutionContext sqlExecutionContext,
CharSequence sql,
MutableUtf16Sink sink
) throws SqlException {
try (RecordCursorFactory factory = compiler.compile(sql, sqlExecutionContext).getRecordCursorFactory()) {
try (RecordCursor cursor = factory.getCursor(sqlExecutionContext)) {
RecordMetadata metadata = factory.getMetadata();
Os.sleep(1); // <--- NEW LINE
sink.clear();
CursorPrinter.println(metadata, sink);
Os.sleep(1);  // <--- NEW LINE
final Record record = cursor.getRecord();
while …
```
=> test(sql): fix flaky testNonAdminCanNotSeeOtherUsersCommands()

core/src/test/java/io/questdb/test/cairo/fuzz/ParallelGroupByFuzzTest.java
Instead of running all parameter combinations, now we run only single combination per CI run. Another change is using 2x fewer rows in `testParallelStringAndVarcharKeyGroupBy()` to speed up all tests based on this method.
=> test(sql): speed up ParallelGroupByFuzzTest

core/src/main/java/io/questdb/cairo/ColumnTypeConverter.java, core/src/main/java/io/questdb/cairo/TableReader.java, core/src/main/java/io/questdb/griffin/ConvertOperatorImpl.java
Found by fuzz test. 
Error at the end can be an FD leak or error of double file close.
=> fix(core): fix column conversion error leading to file descriptor leaks

core/src/main/java/io/questdb/griffin/engine/functions/groupby/AbstractCountGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctIPv4GroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstDateGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstGeoHashGroupByFunctionShort.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstStrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/FirstVarcharGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/MaxDateGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/MaxStrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/MinStrGroupByFunction.java, core/src/main/java/io/questdb/griffin/engine/functions/groupby/VwapDoubleGroupByFunction.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctIPv4GroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/CountDistinctVarcharGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/MaxStrGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/MinStrGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/groupby/VwapDoubleGroupByFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/CountTest.java
Follow-up to PR #5324
This PR addresses two issues related to function linear interpolation support:
1. Added explicit interpolation support declarations for aggregate functions:
- `count()`
- `count_distinct()`
- `vwap()`
These functions already supported interpolation, but this wasn't properly declared. Added tests to verify this behavior.
2. Removed incorrect interpolation support declarations from string and geohash functions:
- Some string functions interpolation was erroneously marked as supported, though it's not applicable
- This appears to have been an accidental addition during test development, where tests were checking for specific error messages
- The recent validation changes caused these tests to fail earlier with different error messages
- Removed the invalid support …
=> chore(sql): sample-by clean ups and fixes

core/src/main/java/io/questdb/tasks/TelemetryTask.java, core/src/main/java/io/questdb/tasks/TelemetryWalTask.java, core/src/test/java/io/questdb/test/TelemetryTest.java
I also confirmed manually that the telemetry tables created by 8.2.0 get recreated with the `master` version, and have TTL set.
=> chore(core): add tests that check the behaviour of upgrading Telemetry tables with TTL

core/src/main/java/io/questdb/cairo/FullBwdPartitionFrameCursorFactory.java, core/src/main/java/io/questdb/cairo/FullFwdPartitionFrameCursorFactory.java, core/src/main/java/io/questdb/cairo/IntervalFwdPartitionFrameCursorFactory.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java, core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/functions/test/TestReferenceOutOfDateFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/test/TestTableReferenceOutOfDateFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/table/AbstractPageFrameRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnSubQueryRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/FilterOnValuesRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/SortedSymbolIndexRecordCursorFactory.java, core/src/main/java/module-info.java, core/src/main/resources/META-INF/services/io.questdb.griffin.FunctionFactory, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
Also adds cursor release calls to some record cursor factories and improves error handling in `SqlCodeGenerator`
=> fix(http): memory leak when querying tables with changing metadata

core/pom.xml
0.7.3 -> 0.7.4:
- support for OAuth2 state parameter [#390](https://github.com/questdb/ui/pull/390)
=> chore(ui): update web console to 0.7.4

core/src/main/java/io/questdb/cairo/sql/PageFrameMemoryRecord.java, core/src/main/java/io/questdb/cairo/sql/Record.java, core/src/main/java/io/questdb/cairo/sql/VirtualRecord.java, core/src/main/java/io/questdb/griffin/engine/groupby/FillRangeRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/SelectedRecord.java, core/src/test/java/io/questdb/test/griffin/OrderByWithFilterTest.java
`getLongAsIPv4` was not supported for `SelectedRecord`. This was required by `LongSortedLightRecordCursor`, and presented as an internal server error.
The workaround before this fix is to add an extra column with a cast, causing a `VirtualRecord` to be produced, which had this function implemented.
=> fix(sql): fix UnsupportedOperationException thrown when sorting an IPv4 column

core/src/main/java/io/questdb/griffin/engine/table/ShowCreateTableRecordCursorFactory.java, core/src/test/java/io/questdb/test/TelemetryTest.java, core/src/test/java/io/questdb/test/griffin/ShowCreateTableTest.java
The current impl elided the `PARTITION BY` clause when it was equivalent to `PARTITION BY NONE`.
Unfortunately,  `BYPASS WAL` would still be printed, leading to invalid syntax.
Rather than elide them, both will be printed to make it explicit that the table is non-partitioned and non-WAL.
Before:
```sql
timestamp(ts) BYPASS WAL;
```
After:
```sql
timestamp(ts) PARTITION BY NONE BYPASS WAL;
```
=> fix(sql): `SHOW CREATE TABLE` provides invalid ddl when table is not partitioned

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/test/java/io/questdb/test/PropServerConfigurationTest.java
fix occasional config parsing error when the context path is set per service
=> fix(core): fix occasional config parsing error when the context path is set per service

core/src/main/java/io/questdb/DynamicPropServerConfiguration.java, core/src/test/java/io/questdb/test/DynamicPropServerConfigurationTest.java
Unknown properties are now handled consistently and ignored when reloading server config.
=> chore(core): ignore unknown properties when reloading server config

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/pool/AbstractMultiTenantPool.java, core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java
Found by fuzz tests
When the table is created from ILP a concurrent update can fail with "table busy" error.
This PR unlocks table reading and metadata early to prevent such exceptions
=> fix(core): fix updates failing with table busy when non-WAL table is created from ILP

core/pom.xml
upgrade web console to 0.7.5
Includes two UI fixes:
- Fix floating-point regex capturing words beginning with 'E' [#394](https://github.com/questdb/ui/pull/394)
- Prevent login loop when token expires without a valid refresh token [#395](https://github.com/questdb/ui/pull/395)
=> chore(ui): upgrade web console to 0.7.5

core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/test/java/io/questdb/test/fuzz/FuzzChangeColumnTypeOperation.java, core/src/test/java/io/questdb/test/fuzz/FuzzDropColumnOperation.java, core/src/test/java/io/questdb/test/fuzz/FuzzDropPartitionOperation.java, core/src/test/java/io/questdb/test/fuzz/FuzzRenameColumnOperation.java, core/src/test/java/io/questdb/test/fuzz/FuzzTransactionGenerator.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
Before v8.2.2 differences in column name casing in change column type SQL failed in the Apply WAL stage on Linux. This is quite unpleasant to deal with, the table is suspended.
It is fixed in 8.2.2 as a side effect of PR https://github.com/questdb/questdb/pull/5242/files#diff-92e19a7ebb8d2d8603f78fa9cbef967a936887bed8476a0a3e70c736c65ecc41 and this PR adds fuzz tests that randomly change column name casing in fuzz tests.
Fuzz tests discovered that there is still sensitivity in column name casing, this is addressed in `WalWriter` now.
=> fix(core): fix column name case sensitivity in alter column SQL

.github/workflows/pgwire_stable.yml, compat/src/test/php/composer.json, compat/src/test/php/runner.php, compat/src/test/scenarios_stable.sh, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGConnectionContextModern.java, core/src/main/java/io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java
fixes #5368
PHP clients were experiencing incorrect "cached plan must not change result type" errors. These errors were spurious and occurred due to improper handling of prepared statement cleanup.
When PHP clients use the SQL DEALLOCATE command to release named prepared statements:
- The `PGPipelineEntry` object was removed from the prepared statements map
- However, the entry was not returned to the object pool
- The entry also remained in a "dirty" state (was not cleared)
- When a connection closed and `pool.clear()` was called, these dirty entries became available for reuse by new connections
- Properly return `PGPipelineEntry` objects to the pool after deallocation via SQL `DEALLOCATE`
- Ensure entries are cleared before returning to the pool
Added a defensive check in …
=> fix(pgwire): compatibility with PHP PDO client

core/src/main/java/io/questdb/cairo/MetadataCache.java, core/src/test/java/io/questdb/test/cairo/MetadataCacheTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/ShowTablesTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/InformationSchemaColumnsFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/PgAttributeFunctionFactoryTest.java
This change fixes stale results returned by metadata functions when a table is dropped and recreated with the same name.
The bug affected the following table functions: tables(),
information_schema.columns() and pg_attribute().
Mitigation before this fix is released: Disable query cache or execute `SELECT flush_query_cache()` after dropping a table.
=> fix(sql): prevent stale metadata after table DROP and (re-)CREATE

core/src/main/java/io/questdb/cairo/mv/MatViewDefinition.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/MatViewsFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TablesFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperation.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationBuilderImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationImpl.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/WorkerPoolManagerTest.java, core/src/test/java/io/questdb/test/cairo/BitmapIndexTest.java, core/src/test/java/io/questdb/test/cairo/MetadataCacheTest.java, core/src/test/java/io/questdb/test/cairo/mv/CreateMatViewTest.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewGraphImplTest.java, core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java, core/src/test/java/io/questdb/test/griffin/KeywordAsTableNameTest.java, core/src/test/java/io/questdb/test/griffin/ShowTablesTest.java, core/src/test/java/io/questdb/test/griffin/SqlUtilTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/bin/Base64FunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/date/TimestampCeilFloorFunctionFactoryTest.java
Depends on #5414
Also renames `isMatView` column to `matView` in `tables()` SQL function.
=> chore(core): persist refresh type in materialized view definition file

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PropertyKey.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java, core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/cairo/DefaultCairoConfiguration.java, core/src/main/java/io/questdb/cairo/IDGenerator.java, core/src/main/java/io/questdb/cairo/IDGeneratorFactory.java, core/src/main/java/io/questdb/cairo/wal/seq/TableSequencerImpl.java, core/src/main/resources/io/questdb/site/conf/server.conf, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/cairo/IDGeneratorTest.java, core/src/test/java/io/questdb/test/cairo/Overrides.java, pkg/ami/marketplace/assets/server.conf
Fix https://github.com/questdb/questdb/issues/5322
Add a batch IDAllocator when server running in sync mode.
=> chore(core): add batch IDAllocator when DB running in sync mode

core/src/main/java/io/questdb/cairo/BitmapIndexBwdNullReader.java, core/src/main/java/io/questdb/cairo/BitmapIndexFwdNullReader.java, core/src/test/java/io/questdb/test/cairo/BitmapIndexBwdNullReaderTest.java, core/src/test/java/io/questdb/test/cairo/BitmapIndexFwdNullReaderTest.java
Queries like
```sql
SELECT *
FROM my_table
WHERE sym = 'foobar'
ORDER BY ts DESC;
```
on tables with filtered indexed symbol column could return rows with NULL symbol values instead of the filtered value.
Also, fixes `FrameAppendFuzzTest#testFullRandom()` failure that can be observed with this patch: edfaf8c39da1657ad0a24bff3a0982f05096b9ad
=> fix(sql): null values returned from index-based non-null filter in backward-scan query

core/src/main/java/io/questdb/cairo/SymbolMapReaderImpl.java, core/src/test/java/io/questdb/test/cairo/TableReaderReloadTest.java, core/src/test/java/io/questdb/test/griffin/ReaderReloadTest.java, core/src/test/java/io/questdb/test/griffin/SymbolTest.java
Refs #5427
Symbol readers didn't refresh "contains null" flag on table reader reload. As a result, NOT IN indexed symbol filter queries that use `FilterOnExcludedValuesRecordCursorFactory` could return wrong result set, without null values being included, if they were first run on empty table.
=> fix(sql): missing null symbol value in query with not in symbol filter

.github/prepare_rust_env.py, .github/workflows/rebuild_rust.yml, .github/workflows/rebuild_rust_test.yml, ci/rust-test-and-lint.yaml, ci/templates/steps.yml, ci/test-pipeline.yml
Fixed CI to install the required nightly Rust version.
The install script parses the `qdbr/rust-toolchain.toml` file as the source of the version to install.
=> ci(build): install the correct rust version

core/src/main/java/io/questdb/griffin/WhereClauseParser.java, core/src/test/java/io/questdb/test/griffin/engine/functions/eq/EqTimestampCursorFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/lt/GtTimestampCursorFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/lt/LtTimestampCursorFunctionFactoryTest.java
WHERE clauses like this one led to memory leaks due to missing close calls in `WhereClauseParser`:
```sql
WHERE ts = (SELECT ts::varchar FROM x LIMIT 2)
```
=> fix(sql): fix memory leaks when parsing sub-queries in timestamp filter

compat/src/test/java/io/questdb/compat/R2DBCTest.java
this was failing on platforms where ipv6 is preferred by default
=> test(sql): makes r2dbc test to use ipv4

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoException.java, core/src/main/java/io/questdb/cairo/wal/CopyWalSegmentUtils.java, core/src/main/java/io/questdb/cairo/wal/SegmentColumnRollSink.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java, core/src/main/java/io/questdb/network/AbstractIODispatcher.java, core/src/test/java/io/questdb/test/AbstractBootstrapTest.java, core/src/test/java/io/questdb/test/ServerMainTest.java, core/src/test/java/io/questdb/test/cairo/GenericRecordMetadataTest.java, core/src/test/java/io/questdb/test/cairo/fuzz/WalWriterFuzzTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/AbstractLineHttpFuzzTest.java, core/src/test/java/io/questdb/test/griffin/TableWriterAsyncCmdTest.java, core/src/test/java/io/questdb/test/griffin/engine/join/JoinRecordMetadataTest.java
fixes error on ILP commit
```
java.lang.AssertionError
at io.questdb.cairo.vm.MemoryPARWImpl.jumpTo(MemoryPARWImpl.java:406)
at io.questdb.cairo.wal.WalWriter.switchColumnsToNewSegmentRollColumn(WalWriter.java:1640)
at io.questdb.cairo.wal.WalWriter.switchColumnsToNewSegment(WalWriter.java:1628)
at io.questdb.cairo.wal.WalWriter.rollUncommittedToNewSegment(WalWriter.java:606)
at io.questdb.cairo.wal.WalWriter$MetadataWriterService.addColumn(WalWriter.java:1906)
at io.questdb.griffin.engine.ops.AlterOperation.applyAddColumn(AlterOperation.java:417)
at io.questdb.griffin.engine.ops.AlterOperation.apply(AlterOperation.java:142)
at io.questdb.cairo.wal.WalWriter.applyStructural(WalWriter.java:867)
at io.questdb.cairo.wal.WalWriter.apply(WalWriter.java:253)
at …
```
=> fix(core): fix rare ILP commit exception when writing large string values

core/src/main/java/io/questdb/cairo/CairoEngine.java, core/src/main/java/io/questdb/griffin/SqlParserCallback.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateMatViewOperationBuilderImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationBuilderImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationImpl.java, core/src/test/java/io/questdb/test/cairo/mv/CreateMatViewTest.java
Allows EntCairoEngine to use EntAllowAllSecurityContext instead of AllowAllSecurityContext.
Gets rid of SHOW CREATE TABLE/MAT VIEW related code duplication, and allows ent to reuse this code too.
required by https://github.com/questdb/questdb-enterprise/pull/582
=> chore(core): refactoring for explain create table/mat view ent fixes

ci/validate-pr-title/validate.js, core/src/main/java/io/questdb/cutlass/http/DefaultHttpServerConfiguration.java, utils/README.md, utils/pom.xml, utils/src/main/java/io/questdb/cliutil/Table2Ilp.java, utils/src/main/java/io/questdb/cliutil/Table2IlpCopier.java, utils/src/test/java/io/questdb/cliutil/Table2IlpTest.java
1. Fix the exception of missing pg driver when running utils.jar
```
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:8812/qdb
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:191)
at io.questdb.cliutil.Table2IlpCopier.getConnection(Table2IlpCopier.java:132)
at io.questdb.cliutil.Table2IlpCopier.copyTable(Table2IlpCopier.java:47)
at io.questdb.cliutil.Table2Ilp.main(Table2Ilp.java:49)
Failed to connect to the source
Total sent lines: 0
```
2. Support UUID column type
3. Allow to specify ILP destination connection string instead of host/port/keys. Connectoin strings can be used to write using ILP HTTP
=> chore(utils): include pg driver into utils jar

core/src/main/java/io/questdb/cairo/CairoException.java, core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java, core/src/test/java/io/questdb/test/DynamicPropServerConfigurationTest.java, core/src/test/java/io/questdb/test/ServerMainCleanStartupTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/AbstractLineHttpFuzzTest.java
Before
```
2025-03-19T18:40:36.224663Z C i.q.g.e.o.AlterOperation could not alter table [table=WEATHER0~4, command=1, msg=duplicate column [name=location], errno=-100]
2025-03-19T18:40:36.224721Z C i.q.g.e.o.AlterOperation could not alter table [table=WEATHER0~4, command=1, msg=duplicate column [name=location], errno=-100]
```
After
```
2025-03-19T18:41:14.297188Z I i.q.g.e.o.AlterOperation could not alter table [table=weather1~4, command=1, msg=duplicate column [name=humidity1], errno=-100]
2025-03-19T18:41:14.297238Z I i.q.g.e.o.AlterOperation could not alter table [table=weather1~4, command=1, msg=duplicate column [name=humidity1], errno=-100]
```
Change is in the logging level.
Also fixed few flaky tests:
- `ServerMainCleanStartupTest.testServerMainCleanStart`
- …
=> chore(ilp): make ilp concurrent add column log info level

core/src/test/java/io/questdb/test/cutlass/pgwire/PreparedStatementInvalidationTest.java
Fix a test that was causing spurious failures due to a race condition. The test starts an auxiliary thread that allocates a thread-local Path instance. Ensure this thread-local is properly cleared before the main test thread completes to prevent spurious memory leak failures.
=> test(pgwire): fix racy test with thread-local memory leak

core/src/main/java/io/questdb/cairo/MetadataCache.java, core/src/test/java/io/questdb/test/cairo/MetadataCacheTest.java
Fix replication failure to rename the table on the replica
```
2025-03-19T09:53:43.8653242Z java.lang.NullPointerException: Cannot read field "columnOrderMap" because "fromTab" is null
2025-03-19T09:53:43.8653837Z 	at io.questdb.cairo.CairoTable.<init>(CairoTable.java:57)
2025-03-19T09:53:43.8654443Z 	at io.questdb.cairo.MetadataCache$MetadataCacheWriterImpl.renameTable(MetadataCache.java:600)
2025-03-19T09:53:43.8655065Z 	at io.questdb.cairo.TableNameRegistryRW.renameToNew(TableNameRegistryRW.java:175)
2025-03-19T09:53:43.8655745Z 	at io.questdb.cairo.TableNameRegistryRW.rename(TableNameRegistryRW.java:143)
2025-03-19T09:53:43.8656803Z 	at io.questdb.cairo.CairoEngine.applyTableRename(CairoEngine.java:295)
2025-03-19T09:53:43.8657675Z 	at …
```
=> chore(core): fix rare table rename failure on replica on after restart

core/src/main/java/io/questdb/cairo/mv/WalTxnRangeLoader.java, core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/main/java/io/questdb/cairo/wal/WalEventCursor.java, core/src/main/java/io/questdb/cairo/wal/WalEventReader.java, core/src/main/java/io/questdb/cairo/wal/WalEventWriter.java, core/src/main/java/io/questdb/cairo/wal/WalReader.java, core/src/main/java/io/questdb/cairo/wal/WalTxnDetails.java, core/src/main/java/io/questdb/cairo/wal/WalTxnType.java, core/src/main/java/io/questdb/cairo/wal/WalUtils.java, core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java
This PR adds some stub code to handle a new WAL-E records (`MAT_VIEW_DATA` and `MAT_VIEW_INVALIDATION`) .
The current file format is **not** changed, and the code doesn't add any new features yet.
=> chore(wal): add stub code for future WAL-E format handling

core/src/main/java/io/questdb/griffin/engine/groupby/GroupByUtils.java, core/src/test/java/io/questdb/test/griffin/GroupByTest.java
When `assembleGroupByFunctions()` processes columns, it incorrectly excludes timestamps from the grouping keys in `outKeyType`s. While the function doesn't consider timestamp to be a grouping key, the downstream RecordSink still attempts to write to this non-existent column.
fixes #5526
=> fix(sql): crash when GROUP BY key includes timestamp

core/src/test/java/io/questdb/test/cutlass/http/HttpQueryTestBuilder.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpSenderFailureTest.java, core/src/test/java/io/questdb/test/cutlass/http/line/LineHttpsSenderTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/AbstractLineTcpReceiverTest.java, core/src/test/java/io/questdb/test/cutlass/line/tcp/AlterWalTableLineTcpReceiverTest.java, core/src/test/java/io/questdb/test/log/LogFactoryTest.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
- inlined constant args (please don't proleferate those)
- added exception to `assertEventually()` so that we don't need to have wrappers all over
- inlined lambdas and removed IntelliJ warnings 
Majority of the clean up is in Ent tandem: https://github.com/questdb/questdb-enterprise/pull/592
=> test(core): clean up test infastructure

core/rust/qdb-core/src/col_driver/varchar.rs, core/src/main/java/io/questdb/cutlass/http/client/HttpClient.java
While benchmarking ILP over HTTP with small batch sizes, we found the performance to be very poor (16 request per second). We tracked it down to Nagle's algorithm being on by default, causing the TCP client socket to wait for some time before sending the data after it got it from the application.
This change sets the `TCP_NODELAY` flag on the TCP connection used in `HttpClient`.
=> chore(core): disable Nagle's algorithm in HttpClient (set TCP_NODELAY flag)

core/src/main/java/io/questdb/TelemetryConfigLogger.java
`TelemetryConfigLogger` used `ADD COLUMN` instead of `ADD COLUMN IF NOT EXISTS`.
That meant the log would be spammed with errors on startup:
```
2025-04-11T11:28:53.524232Z E i.q.g.e.QueryProgress err [id=-1, sql=`ALTER TABLE telemetry_config ADD COLUMN version symbol`, principal=admin, cache=false, jit=true, time=12798000, msg=column 'version' already exists, errno=0, pos=40]
2025-04-11T11:28:53.524718Z E i.q.g.e.QueryProgress err [id=-1, sql=`ALTER TABLE telemetry_config ADD COLUMN os symbol`, principal=admin, cache=false, jit=true, time=336300, msg=column 'os' already exists, errno=0, pos=40]
2025-04-11T11:28:53.524951Z E i.q.g.e.QueryProgress err [id=-1, sql=`ALTER TABLE telemetry_config ADD COLUMN package symbol`, principal=admin, cache=false, jit=true, time=101800, msg=column …
```
=> chore(sql): fix startup errors migrating telemetry_config

core/src/main/java/io/questdb/network/IODispatcherLinux.java, core/src/main/java/io/questdb/network/IODispatcherWindows.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Fixes #5559
This PR resolves an issue in `IODispatcherLinux` where it attempts to close an uninitialized `epoll` instance.
This results in a misleading error message that obscures the actual root cause.  
The error message "Cannot invoke "io.questdb.network.Epoll.close()" is misleading and hides the actual exception: `NetworkError("could not bind socket")`.
See `IODispatcherTest.testNetworkErrorCouldNotBindSocket `for details
=> fix(core): fix `cannot invoke "io.questdb.network.Epoll.close()"` error

core/src/main/java/io/questdb/griffin/engine/functions/catalogue/MatViewsFunctionFactory.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewStateTest.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewTest.java
This PR fixes https://github.com/questdb/questdb/issues/5483 by renaming columns in the `materialized_view()` output to improve clarity:
-  `base_table_txn` → `refresh_base_table_txn`
(Represents the base table transaction up to which the materialized view is current)
-  `applied_base_table_txn` → `base_table_txn`
(Represents the last applied transaction of the base table)
The telemetry table continues to use the old column name `base_table_txn` with the meaning of `refresh_base_table_txn`.
This was kept unchanged for compatibility reasons.
Documentation updates will be handled in a separate PR.
=> chore(sql): breaking change 💥 - improve column name clarity in materialized_view() function

core/pom.xml
- array type support [#391](https://github.com/questdb/ui/pull/391)
- minor improvements to tests and performance [#406](https://github.com/questdb/ui/pull/406)
- show JSON parsing error in case of an invalid query result [#411](https://github.com/questdb/ui/pull/411)
- open a new tab when query param exists and metrics tab is open [#415](https://github.com/questdb/ui/pull/415)
- fix incorrect unit normalisation for wal row throughput [#414](https://github.com/questdb/ui/pull/414)
- don't use navigator.clipboard in insecure context [#417](https://github.com/questdb/ui/pull/417)
- workaround for broken safari copy schema mechanism [#418](https://github.com/questdb/ui/pull/418)
=> chore(ui): upgrade web console to 0.7.9

core/src/main/java/io/questdb/cairo/CairoException.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
Before executing the `checkpoint create` query, the timer for the query start was not set.
=> fix(sql): add reset query timeout timer before `checkpoint create`

core/src/main/java/io/questdb/cairo/wal/WalWriter.java, core/src/main/java/io/questdb/griffin/ExpressionParser.java, core/src/main/java/io/questdb/griffin/SqlCompilerImpl.java, core/src/main/java/io/questdb/griffin/engine/ops/AlterOperation.java, core/src/main/java/io/questdb/griffin/engine/ops/AlterOperationBuilder.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java, core/src/test/java/io/questdb/test/griffin/AlterTableAlterColumnTest.java, core/src/test/java/io/questdb/test/griffin/AlterTableAlterSymbolColumnCacheFlagTest.java, core/src/test/java/io/questdb/test/griffin/AlterTableChangeColumnTypeTest.java, core/src/test/java/io/questdb/test/griffin/CheckpointTest.java
Also fixes insufficient validation in ALTER TABLE SYMBOL CAPACITY. Statements like `alter table x alter column sym symbol capacity;` or `alter materialized view x alter column sym symbol cache;` were accepted and led to default capacity being used as the new value.
=> feat(sql): alter materialized view symbol capacity

ci/github-release-pipeline.yml, ci/templates/self-hosted-jobs.yml
We're running ubuntu-latest, which can toggle between 22.04 and 24.04. The aws package is not included in ubuntu 24.04, and even the one in 22.04 is an old cli version.
By pinning to MSFT's ubuntu 24.04 build, they include aws cli v2 so we don't run into these issues in the future.
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#cli-tools
Our syntax for self-hosted runners is no longer valid, so we update that as well
=> chore(build): fix Azure Pipelines

core/src/main/java/io/questdb/cairo/mv/MatViewRefreshExecutionContext.java, core/src/main/java/io/questdb/cairo/mv/MatViewRefreshJob.java, core/src/main/java/io/questdb/cairo/mv/MatViewRefreshTask.java, core/src/main/java/io/questdb/cairo/mv/MatViewState.java, core/src/main/java/io/questdb/cairo/mv/MatViewStateStoreImpl.java, core/src/main/java/io/questdb/griffin/SqlExecutionContext.java, core/src/main/java/io/questdb/griffin/SqlExecutionContextImpl.java, core/src/main/java/io/questdb/griffin/engine/QueryProgress.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/MatViewsFunctionFactory.java, core/src/test/java/io/questdb/test/cairo/mv/CreateMatViewTest.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewStateTest.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewTest.java, core/src/test/java/io/questdb/test/griffin/engine/table/AsyncFilteredRecordCursorFactoryTest.java
- Add `last_refresh_started_timestamp` to the` materialized_views()` output.
- When a refresh is running, the `view_status` column in the` materialized_views()` output is set to "refreshing".
- Include `refreshMinTs` and `refreshMaxTs` from materialized view refreshes in `QueryProgress` logging.
=> chore(sql):  add last_refresh_started_timestamp to materialized_views() output

benchmarks/src/main/java/org/questdb/TxnScoreboardV2Benchmark.java, core/src/main/java/io/questdb/cairo/TxnScoreboardV2.java, core/src/test/java/io/questdb/test/cairo/TxnScoreboardTest.java
Add bitmap index for `TxnScoreboardV2`, to accelerate  the scan of txn entries, especially when the "valid" txn entries is sparse
**benchmark result**
benchmark setup
```
public void setup() {
scoreboard = new TxnScoreboardV2(entryCount);
scoreboard.acquireTxn(160, 100);
}
```
bitmap index ====>
```
Benchmark                                   Mode  Cnt  Score   Error  Units
TxnScoreboardV2Benchmark.acquireAndRelease  avgt    2  0.473          us/op
TxnScoreboardV2Benchmark.activeReaderCount  avgt    2  0.004          us/op
TxnScoreboardV2Benchmark.mixed              avgt    2  0.258          us/op
TxnScoreboardV2Benchmark.rangeAvailable     avgt    2  0.007          us/op
```
master branch ====>
```
TxnScoreboardV2Benchmark.acquireAndRelease  avgt    2  0.325          us/op …
```
=> chore(core): add bitmap index for `TxnScoreboardV2`

core/src/main/java/io/questdb/cairo/ColumnPurgeJob.java, core/src/main/java/io/questdb/cairo/ColumnPurgeOperator.java, core/src/test/java/io/questdb/test/AbstractCairoTest.java, core/src/test/java/io/questdb/test/cairo/TableNameRegistryTest.java, core/src/test/java/io/questdb/test/cairo/fuzz/WalWriterFuzzTest.java, core/src/test/java/io/questdb/test/cairo/mv/CreateMatViewTest.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalPurgeJobTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalTableSqlTest.java, core/src/test/java/io/questdb/test/cairo/wal/WalWriterTest.java, core/src/test/java/io/questdb/test/cutlass/http/ScoreboardHandlingTest.java, core/src/test/java/io/questdb/test/cutlass/http/TestHttpClient.java, core/src/test/java/io/questdb/test/tools/TestUtils.java
The test I added would reproduce the problem only occasionally. The problem emanates out of the async column purge job.
Refactored purge operator to have fixed, final scoreboard usage mode. This avoids the code to deal possible mode switches. E.g. what and when should or should not be null. Mode switching is disallowed and mode is a final value in the constructor.
=> chore(core): fix potential crash/leak in scoreboard v2 courtesy of the column purge job

core/src/main/java/io/questdb/cairo/mv/MatViewStateStoreImpl.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewTest.java
When creating a materialized view, if the base table name used different case letters, automatic incremental refresh wouldn't happen on the newly created view.
=> fix(sql): case sensitive base table name when creating materialized view

core/rust/qdb-core/src/error.rs, core/src/main/java/io/questdb/griffin/engine/functions/conditional/CaseFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/CoalesceFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/conditional/SwitchFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/ListFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/LongSequenceFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStringListFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndSymbolListFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndVarcharListFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/str/ConcatFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/table/HydrateTableMetadataFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CaseFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/conditional/CoalesceFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/str/ConcatFunctionFactoryTest.java
`greatest()` and `least()` are fixed in #5669
=> fix(sql): NullPointerException when calling vararg functions with no arguments

core/rust/qdb-core/src/error.rs, core/src/main/java/io/questdb/cairo/CairoColumn.java, core/src/main/java/io/questdb/cairo/CairoTable.java, core/src/main/java/io/questdb/cairo/MetadataCache.java, core/src/main/java/io/questdb/cairo/TableReaderMetadata.java, core/src/main/java/io/questdb/cairo/TableUtils.java, core/src/main/java/io/questdb/cairo/TableWriterMetadata.java, core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TablesFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/table/ShowColumnsRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/table/ShowCreateTableRecordCursorFactory.java, core/src/test/java/io/questdb/test/cairo/MetadataCacheTest.java, core/src/test/java/io/questdb/test/cairo/mig/EngineMigrationTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/catalogue/TablesBootstrapTest.java
Table metadata commands, such as `tables()` and `SHOW CREATE TABLE...`, incorrectly displayed which column is the designated timestamp because of a bug in metadata cache.
When a column positioned before the designated timestamp was dropped, the index of the designated timestamp column did not get adjusted.
This meant that the index pointed to the column behind the actual timestamp, and we displayed incorrect information.
Restart did not help either, because we never remove columns from the metadata files, just mark them as dropped.
On startup the cache does not load the dropped columns, and the timestamp index was just taken from the file as is without accounting for the dropped columns.
Fix is to use the writer index of the timestamp column to mark the designated timestamp column, the …
=> fix(core): fixed table metadata commands, incorrectly displayed which column is the designated timestamp

.github/workflows/danger.yml
Danger GitHub Action started failing due to outdated Node.js version. Upgrading to the current LTS version, v22.
=> chore(build): Fix outdated Node.js for Danger GitHub Action

core/src/main/java/io/questdb/PropServerConfiguration.java, core/src/main/java/io/questdb/PublicPassthroughConfiguration.java, core/src/main/java/io/questdb/ServerConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfiguration.java, core/src/main/java/io/questdb/cairo/CairoConfigurationWrapper.java, core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/HttpResponseHeader.java, core/src/main/java/io/questdb/cutlass/http/HttpResponseSink.java, core/src/main/java/io/questdb/cutlass/http/processors/RejectProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/RejectProcessorImpl.java, core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessor.java, core/src/main/java/io/questdb/cutlass/http/processors/SettingsProcessorState.java, core/src/main/java/io/questdb/cutlass/http/processors/TableStatusCheckProcessor.java, core/src/main/java/io/questdb/preferences/SettingsStore.java, core/src/test/java/io/questdb/test/cutlass/http/SettingsEndpointTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/json/JsonExtractVarcharFunctionFactoryTest.java, core/src/test/java/io/questdb/test/preferences/SettingsStoreConcurrentTest.java
Content length was calculated incorrectly for non-ASCII content in `HttpResponseSink.sendStatus...()` methods.
Because of the incorrect content length the browser stopped reading the HTTP body early, resulting in malformed JSON messages which subsequently broke the web console.
Changed all `HttpResponseSink.sendStatus...()` methods to take `Utf8Sequence` as a message, and content length is calculated by calling `Utf8Sequence.size()`. 
fixes https://github.com/questdb/questdb/issues/5698
required by https://github.com/questdb/questdb-enterprise/pull/621
=> fix(core): fix for emoji in instance name breaking web console

.github/workflows/pgwire_stable.yml
The workflow was triggering on every pull request `edited` event, including for non-code changes like editing the title or description.
Remaining triggers:
- opened: a pull request is created
- reopened: a previously closed pull request is opened again
- synchronize: new commits are pushed to the pull request branch
=> ci(pgwire): reduce unnecessary runs of PGWire workflow

core/src/test/java/io/questdb/test/griffin/CreateTableFuzzTest.java
QuestDB used to misreport an error position in
CREATE as SELECT errors. CreateTableFuzzTest compensates for this misreported position
https://github.com/questdb/questdb/commit/d6cbc8376232c761bd7df7c6e31f5e9984d65a28 fixed the error position reporting -> we have to remove the error position compensation.
=> test(sql): remove error position compensation

core/src/main/resources/io/questdb/site/conf/server.conf
There are 2 `cairo.wal.writer.data.append.page.size` in the comments in the `server.conf`. It might be a typo, and the second one might be `cairo.wal.writer.event.append.page.size`.
=> chore(core): add missing conf name `cairo.wal.writer.event.append.page.size` in the comments in server.conf

core/src/main/java/io/questdb/griffin/PostOrderTreeTraversalAlgo.java, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/test/java/io/questdb/test/griffin/DeclareTest.java
This PR fixes #5804 by deepCloning `ExpressionNode`s that are used to replace variables.
When SqlParser replaces declare variables with constant expressions, it was re-using the original `ExpressionNode` instances instead of cloning them. Because `PostOrderTreeTraversalAlgo` relies on reference comparison to track traversal state, sharing the same node instance between the lhs and rhs of an expression can trick the algorithm into thinking it has already processed lhs.
The problematic check:
```java
// PostOrderTreeTraversalAlgo
if (peek.lhs != null && lastVisited != peek.lhs) { // lastVisited may actually be peek.rhs,
node = peek.lhs;
}
```
Example of a failing query:
```sql
DECLARE
@ts := '2025-07-02T13:00:00.000000Z',
@int := interval(@ts, @ts)
SELECT @int;
```
=> fix(sql): exception thrown when same DECLARE variable used in 2-params function 

.github/workflows/r_test.yml
The equivalent of https://github.com/questdb/questdb/pull/5743 except for R tests.
R tests are not exercised in the usual PGWire test suite and I forgot about this in #5743
will it run?
=> ci(pgwire): reduce unnecessary runs of R workflow

core/src/main/java/io/questdb/cutlass/http/processors/JsonQueryProcessorState.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java
This PR (with [ui#452](https://github.com/questdb/ui/pull/452)) fixes a bug that occurs when users have commas in their column names and uses the `cols` query parameter in the HTTP processor.
In order to fix the bug, [ui#452](https://github.com/questdb/ui/pull/452) stringifies column names before sending them through the wire and this PR handles double quotes and escape character.
=> fix(http): fix exception thrown when using escaped column names

compat/src/test/resources/test_cases.yaml, core/src/main/java/io/questdb/griffin/SqlParser.java, core/src/main/java/io/questdb/griffin/engine/ops/CreateTableOperationImpl.java, core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
This PR fixes a bug that allowed users to create tables with invalid column names. Such tables could not be altered later.
=> fix(sql): validate column aliases in CREATE TABLE statements

core/src/main/java/io/questdb/griffin/engine/functions/constants/SymbolConstant.java, core/src/test/java/io/questdb/test/griffin/CompiledFilterTest.java
We had some unquoting logic that didn't account for this edge case.
We should still review why upstream code was sending such a filter.
=> fix(sql): exception when JIT compiling a filter like `WHERE symbol = ''''`

core/src/main/java/io/questdb/griffin/engine/groupby/YearTimestampSampler.java, core/src/main/java/io/questdb/std/datetime/microtime/Timestamps.java, core/src/test/java/io/questdb/test/cairo/mv/MatViewTest.java, core/src/test/java/io/questdb/test/griffin/engine/groupby/YearTimestampSamplerTest.java
Fixes #6029
`YearTimestampSampler` sampler had a bug around rounding. Namely, when the rounded year was a leap year and the input year wasn't, the returned result was incorrect.
This bug manifested itself in materialized view refresh where the lo value of a range replace commit could end up being greater than the minimal timestamp of the transaction. The reason is that the range replace lo was calculated based on `YearTimestampSampler#round()`.
=> fix(core): incorrect year rounding in case of leap years

core/src/main/java/io/questdb/cairo/TableWriter.java, core/src/main/java/io/questdb/cairo/TableWriterSegmentFileCache.java, core/src/test/java/io/questdb/test/cairo/BitmapIndexConcurrentTest.java
A file descriptor leak was found by fuzz tests. This PR fixes a file descriptor leak that occurs when a table is dropped and WAL (Write-Ahead Log) files are being purged concurrently with TableWriter operations. The leak happens due to double-closing of file descriptors when exceptions occur during WAL file operations. The scenario is
- A table is dropped
- WAL Purge job starts deleting the WAL files
- TableWriter may be at this moment try to open the WAL files that are being deleted
- TableWriter gets an exception on WAL file open and closes the open WAL files
- Then, on closing the TableWriter object, the WAL files are closed the second time and fail because of the double close guard in FdCache.
- The last exception aborts TableWriter cleanup and leads to a file descriptor leak.
The fix …
=> fix(core): fix potential File Descriptor leak on table drop

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
In rare cases where queries execute while a table is being ALTERed simultaneously, memory could leak during internal query retries. This edge case only affected systems with concurrent schema modifications and queries on the same table. While queries completed successfully through automatic retries, memory from failed attempts was not released.
The issue occurred when the SQL compiler attempted to create a filter during query compilation:
1. Compiler creates a factory
2. Attempts to wrap it in a filter
3. Filter creation tries to obtain a cursor, which can fail due to `TableReferenceOutOfDateException`
4. On failure, the factory wasn't being freed before the retry
=> fix(sql): memory leak when querying a table which is being ALTERed concurrently

core/src/main/java/io/questdb/cairo/TableWriter.java
The old version was missing a closing quote. VS.Code syntax highlighting was really confused and log scrappers probably too.
=> chore(core): improve TableWriter logging consistency

core/src/main/java/io/questdb/std/MmapCache.java
- When count==1 (can extend in-place): No refcount changes on mremap0() failure.
- When count>1 (need new mapping): Only decrement old mapping's refcount if mmap0() succeeds. On failure, caller retains old mapping per POSIX semantics.
Previously decremented unconditionally in count>1 case, causing refcount underflow when mmap0() failed.
=> fix(mmap): correct reference counting in mremap failures scenarios

core/src/main/java/io/questdb/cairo/TableReader.java
A partition removal followed by a schema change could cause a memory and file descriptor leak
It's fixing a FD and memory leak found by a fuzz test. 
WIP. 
Scenario:
1. Partition gets deleted -> stale bitmap indexes left in `bitmapIndexes` list beyond a valid range (at position not references by any column)
2. Eventually, a table schema change triggers `createNewColumnList()`
3. `createNewColumnList()` creates a new  `bitmapIndexes` list but only copies indexes from the old list within a valid range
4. The stale indexes beyond the range are not included in the new bitmap index list
5. When old arrays are replaced with new ones, those stale indexes are orphaned - they remain open but unreachable
6. FD leak - the file descriptors for those bitmap indexes are never closed
Note: 
I am not …
=> fix(core): fix rare index reader memory on partition drop

core/src/main/java/io/questdb/cairo/wal/ApplyWal2TableJob.java, core/src/test/java/io/questdb/test/cairo/wal/WalTableSqlTest.java
After the table got suspended because of a corrupt WAL, the `wal_tables` query displayed a very out-of-date number on writerTxn. This fixes the bug where, while handling exceptions, the Seq Table Tracker is updated to the table `txn` number rather than `seqTxn`.
=> fix(core): fix suspended tables showing wrong writerTxn in wal_tables

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/model/QueryModel.java, core/src/test/java/io/questdb/test/cairo/BitmapIndexConcurrentFuzzTest.java, core/src/test/java/io/questdb/test/griffin/SqlCompilerImplTest.java
Try to close #6078 
```
select distinct x1 as a, a from tab1;
ERROR:  Cannot invoke "io.questdb.griffin.model.QueryColumn.getAst()" because "thatColumn" is null
LINE 1: select distinct x1 as a, a from tab1;
```
=> fix(sql): fix NPE when distinct query contains columns with dependencies.

core/src/main/resources/io/questdb/site/conf/server.conf, pkg/ami/marketplace/assets/server.conf
The description in server.conf specifies 16 readers, but the actual implementation in AbstractMultiTenantPool has 32 readers per segment.
=> docs(core): fix the description of the number of readers per segment

core/src/main/java/io/questdb/cairo/vm/MemoryCMRImpl.java, core/src/main/java/io/questdb/griffin/SqlOptimiser.java
found by a fuzz test:
```
testWalWriteTinyO3Memory - random seeds: 990968392657L, 1757173721663L
```
----
Removed implicit contract that failure to extend memory will close the memory.
=> fix(core): fix incorrect error handling, which can leave table reader in an inconsistent state

core/src/main/java/io/questdb/std/Files.java, core/src/test/java/io/questdb/test/FilesTest.java
The test starts 2 threads, each attempting to allocate 2/3 of free space using posix_fallocate(). On filesystems like ext4, this creates sparse files that reserve space without consuming it immediately. However, tmpfs doesn't support sparse files and materializes the entire allocation in RAM, causing memory exhaustion that affects other processes and /tmp operations.
Skip this test when running on tmpfs to prevent system instability.
=> test(core): skip FilesTest.testAllocateConcurrent() on tmpfs

core/src/main/java/io/questdb/cutlass/http/HttpConnectionContext.java, core/src/main/java/io/questdb/cutlass/http/HttpRequestProcessorSelector.java, core/src/main/java/io/questdb/cutlass/http/HttpRequestValidator.java, core/src/main/java/io/questdb/cutlass/http/HttpServer.java, core/src/main/java/io/questdb/cutlass/http/processors/RejectProcessorImpl.java, core/src/test/java/io/questdb/test/cutlass/http/HttpServerTest.java, core/src/test/java/io/questdb/test/cutlass/http/IODispatcherTest.java, core/src/test/java/io/questdb/test/cutlass/http/WaitProcessorTest.java
Chore because we have default processor registered.
This can happen only in tests.
=> chore(core): reject unhandled HTTP requests if there is no default processor

core/src/main/java/io/questdb/cairo/TableReader.java
Fixes assertion error found by fuzz tests:
```
java.lang.AssertionError
at io.questdb@9.0.4-SNAPSHOT/io.questdb.cairo.TableReader.getBitmapIndexReader(TableReader.java:261)
at io.questdb@9.0.4-SNAPSHOT/io.questdb.griffin.engine.table.FwdTableReaderPageFrameCursor$TableReaderPageFrame.getBitmapIndexReader(FwdTableReaderPageFrameCursor.java:332)
at io.questdb@9.0.4-SNAPSHOT/io.questdb.griffin.engine.table.SymbolIndexRowCursorFactory.getCursor(SymbolIndexRowCursorFactory.java:60)
at io.questdb@9.0.4-SNAPSHOT/io.questdb.griffin.engine.table.PageFrameRecordCursorImpl.hasNext(PageFrameRecordCursorImpl.java:107)
at io.questdb@9.0.4-SNAPSHOT/io.questdb.griffin.engine.groupby.GroupByRecordCursorFactory$GroupByRecordCursor.buildDataMap(GroupByRecordCursorFactory.java:251)
at …
```
=> fix(core): rare assertion error in SQL after metadata change

core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpLegacyWriterJob.java, core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
Found in https://github.com/questdb/questdb/pull/6076/checks?check_run_id=51432033257
The root cause is that `TableUpdateDetails` releases the writer when an exception occurs.
non-WAL tables lack null writer validation before use.
```
2025-09-28T14:13:19.9561634Z 2025-09-28T14:13:19.943713Z E i.q.c.l.t.LineTcpMeasurementEvent could not write line protocol measurement [tableName=weather3~, message=Cannot invoke "io.questdb.cairo.TableWriterAPI.getMetadataVersion()" because "writer" is null, trace: 
2025-09-28T14:13:19.9562638Z java.lang.NullPointerException: Cannot invoke "io.questdb.cairo.TableWriterAPI.getMetadataVersion()" because "writer" is null
2025-09-28T14:13:19.9563496Z 	at io.questdb.cutlass.line.tcp.LineTcpMeasurementEvent.append(LineTcpMeasurementEvent.java:125) …
```
=> test(ilp): handle null writer for non-wal table

core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java, core/src/main/java/io/questdb/griffin/engine/join/AsOfJoinIndexedRecordCursorFactory.java, core/src/main/java/io/questdb/griffin/engine/join/ChainedSymbolShortCircuit.java, core/src/main/java/io/questdb/griffin/engine/join/DisabledSymbolShortCircuit.java, core/src/main/java/io/questdb/griffin/engine/join/SingleStringSymbolShortCircuit.java, core/src/main/java/io/questdb/griffin/engine/join/SingleSymbolSymbolShortCircuit.java, core/src/main/java/io/questdb/griffin/engine/join/SingleVarcharSymbolShortCircuit.java, core/src/main/java/io/questdb/griffin/engine/join/SymbolShortCircuit.java, core/src/test/java/io/questdb/test/griffin/AsOfJoinTest.java
`AsOfJoinIndexedRecordCursorFactory` currently has a bug and fails when the LHS column is not SYMBOL, but STRING or VARCHAR.
This PR broadens the scope of `SymbolShortCircuit`, which already polymorphic in the LHS column type, to let the record factory access the master value in all cases.
=> chore(core): polymorphic AsOfJoinIndexedRecordCursorFactory

.gitignore, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndSymbolWeightedFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndSymbolZipfFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/rnd/RndSymbolWeightedFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/rnd/RndSymbolZipfFunctionFactoryTest.java
Generates Zipf/Power Law Distribution of symbols from the list. The probability of symbol decays from left to right with given 'alpha' velocity.
Usage:
```sql
select rnd_symbol_zipf('AAPL', 'MSFT', 'GOOGL', 'TSLA', 'AMZN', 5.3) from long_sequence(100_000);
```
Also added weighted, but more verbose function:
```sql
select rnd_symbol_weighted('AAPL', 50, 'MSFT', 30, 'GOOGL', 15, 'TSLA', 5) from long_sequence(100_000);
```
=> feat(sql): `rnd_symbol_zipf()` function for generating skewed symbol distributions 

core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndSymbolZipfFunctionFactory.java, core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndSymbolZipfNFunctionFactory.java, core/src/test/java/io/questdb/test/griffin/engine/functions/rnd/RndSymbolZipfFunctionFactoryTest.java, core/src/test/java/io/questdb/test/griffin/engine/functions/rnd/RndSymbolZipfNFunctionFactoryTest.java
Useful in testing algorithms with high-cardinality symbols that have skewed distribution of rows.
=> feat(sql): rnd_symbol_zipfn() function - generates high cardinality symbols with Zipf/Power Law Distribution

core/src/main/java/io/questdb/griffin/engine/groupby/vect/GroupByVectorAggregateJob.java, core/src/test/java/io/questdb/test/griffin/engine/QueryExecutionTimeoutTest.java
When a query is cancelled, `GroupByVectorAggregateJob` would log the error with critical level since it wasn't handling errors properly.
=> fix(sql): avoid critical level logs on vectorized group by query cancellation
